/* tslint:disable */
/* eslint-disable */
/**
 * Omnismith API
 * API Documentation for Omnismith
 *
 * The version of the OpenAPI document: 1.0.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateAccessToken201Response,
  CreateAccessTokenRequest,
  ErrorResponse,
  ListAccessTokens200Response,
  ValidationErrorResponse,
} from '../models/index';
import {
    CreateAccessToken201ResponseFromJSON,
    CreateAccessToken201ResponseToJSON,
    CreateAccessTokenRequestFromJSON,
    CreateAccessTokenRequestToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    ListAccessTokens200ResponseFromJSON,
    ListAccessTokens200ResponseToJSON,
    ValidationErrorResponseFromJSON,
    ValidationErrorResponseToJSON,
} from '../models/index';

export interface CreateAccessTokenOperationRequest {
    createAccessTokenRequest: CreateAccessTokenRequest;
}

export interface DeleteAccessTokenRequest {
    id: string;
}

/**
 * AccessTokensApi - interface
 * 
 * @export
 * @interface AccessTokensApiInterface
 */
export interface AccessTokensApiInterface {
    /**
     * Creates request options for createAccessToken without sending the request
     * @param {CreateAccessTokenRequest} createAccessTokenRequest 
     * @throws {RequiredError}
     * @memberof AccessTokensApiInterface
     */
    createAccessTokenRequestOpts(requestParameters: CreateAccessTokenOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * Generates a new programmatic API access token prefixed with `omni_` (e.g. `omni_live_secret_key_...`) for the authenticated user within the active project context. The token inherits the user\'s current role permissions and scopes for authenticating automated API clients and scripts. The raw secret key is returned exactly once in the response and cannot be recovered later.
     * @summary Create a programmatic API access token
     * @param {CreateAccessTokenRequest} createAccessTokenRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccessTokensApiInterface
     */
    createAccessTokenRaw(requestParameters: CreateAccessTokenOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateAccessToken201Response>>;

    /**
     * Generates a new programmatic API access token prefixed with `omni_` (e.g. `omni_live_secret_key_...`) for the authenticated user within the active project context. The token inherits the user\'s current role permissions and scopes for authenticating automated API clients and scripts. The raw secret key is returned exactly once in the response and cannot be recovered later.
     * Create a programmatic API access token
     */
    createAccessToken(requestParameters: CreateAccessTokenOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateAccessToken201Response>;

    /**
     * Creates request options for deleteAccessToken without sending the request
     * @param {string} id Unique UUIDv7 identifier of the access token to delete
     * @throws {RequiredError}
     * @memberof AccessTokensApiInterface
     */
    deleteAccessTokenRequestOpts(requestParameters: DeleteAccessTokenRequest): Promise<runtime.RequestOpts>;

    /**
     * Permanently revokes and removes a programmatic API access token by its unique identifier. Any future API request using the revoked secret key will immediately fail authentication with a 401 Unauthorized status.
     * @summary Delete an API access token
     * @param {string} id Unique UUIDv7 identifier of the access token to delete
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccessTokensApiInterface
     */
    deleteAccessTokenRaw(requestParameters: DeleteAccessTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Permanently revokes and removes a programmatic API access token by its unique identifier. Any future API request using the revoked secret key will immediately fail authentication with a 401 Unauthorized status.
     * Delete an API access token
     */
    deleteAccessToken(requestParameters: DeleteAccessTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for listAccessTokens without sending the request
     * @throws {RequiredError}
     * @memberof AccessTokensApiInterface
     */
    listAccessTokensRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * Retrieves all active and expired programmatic API access tokens created by the authenticated user for the active project context. Returns token metadata including unique ID, user-assigned label, creation date, expiration timestamp, and last used timestamp. Note: raw secret API keys are only displayed once upon generation and are never returned in list responses.
     * @summary List API access tokens
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccessTokensApiInterface
     */
    listAccessTokensRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListAccessTokens200Response>>;

    /**
     * Retrieves all active and expired programmatic API access tokens created by the authenticated user for the active project context. Returns token metadata including unique ID, user-assigned label, creation date, expiration timestamp, and last used timestamp. Note: raw secret API keys are only displayed once upon generation and are never returned in list responses.
     * List API access tokens
     */
    listAccessTokens(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListAccessTokens200Response>;

}

/**
 * 
 */
export class AccessTokensApi extends runtime.BaseAPI implements AccessTokensApiInterface {

    /**
     * Creates request options for createAccessToken without sending the request
     */
    async createAccessTokenRequestOpts(requestParameters: CreateAccessTokenOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createAccessTokenRequest'] == null) {
            throw new runtime.RequiredError(
                'createAccessTokenRequest',
                'Required parameter "createAccessTokenRequest" was null or undefined when calling createAccessToken().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/access-tokens`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateAccessTokenRequestToJSON(requestParameters['createAccessTokenRequest']),
        };
    }

    /**
     * Generates a new programmatic API access token prefixed with `omni_` (e.g. `omni_live_secret_key_...`) for the authenticated user within the active project context. The token inherits the user\'s current role permissions and scopes for authenticating automated API clients and scripts. The raw secret key is returned exactly once in the response and cannot be recovered later.
     * Create a programmatic API access token
     */
    async createAccessTokenRaw(requestParameters: CreateAccessTokenOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateAccessToken201Response>> {
        const requestOptions = await this.createAccessTokenRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateAccessToken201ResponseFromJSON(jsonValue));
    }

    /**
     * Generates a new programmatic API access token prefixed with `omni_` (e.g. `omni_live_secret_key_...`) for the authenticated user within the active project context. The token inherits the user\'s current role permissions and scopes for authenticating automated API clients and scripts. The raw secret key is returned exactly once in the response and cannot be recovered later.
     * Create a programmatic API access token
     */
    async createAccessToken(requestParameters: CreateAccessTokenOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateAccessToken201Response> {
        const response = await this.createAccessTokenRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteAccessToken without sending the request
     */
    async deleteAccessTokenRequestOpts(requestParameters: DeleteAccessTokenRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteAccessToken().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/access-tokens/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Permanently revokes and removes a programmatic API access token by its unique identifier. Any future API request using the revoked secret key will immediately fail authentication with a 401 Unauthorized status.
     * Delete an API access token
     */
    async deleteAccessTokenRaw(requestParameters: DeleteAccessTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteAccessTokenRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Permanently revokes and removes a programmatic API access token by its unique identifier. Any future API request using the revoked secret key will immediately fail authentication with a 401 Unauthorized status.
     * Delete an API access token
     */
    async deleteAccessToken(requestParameters: DeleteAccessTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteAccessTokenRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for listAccessTokens without sending the request
     */
    async listAccessTokensRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/access-tokens`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieves all active and expired programmatic API access tokens created by the authenticated user for the active project context. Returns token metadata including unique ID, user-assigned label, creation date, expiration timestamp, and last used timestamp. Note: raw secret API keys are only displayed once upon generation and are never returned in list responses.
     * List API access tokens
     */
    async listAccessTokensRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListAccessTokens200Response>> {
        const requestOptions = await this.listAccessTokensRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListAccessTokens200ResponseFromJSON(jsonValue));
    }

    /**
     * Retrieves all active and expired programmatic API access tokens created by the authenticated user for the active project context. Returns token metadata including unique ID, user-assigned label, creation date, expiration timestamp, and last used timestamp. Note: raw secret API keys are only displayed once upon generation and are never returned in list responses.
     * List API access tokens
     */
    async listAccessTokens(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListAccessTokens200Response> {
        const response = await this.listAccessTokensRaw(initOverrides);
        return await response.value();
    }

}
