/* tslint:disable */
/* eslint-disable */
/**
 * Omnismith API
 * API Documentation for Omnismith
 *
 * The version of the OpenAPI document: 1.0.14
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  ListPushDevices200Response,
  RegisterPushDevice201Response,
  RegisterPushDeviceRequest,
  UnregisterPushDeviceRequest,
  ValidationErrorResponse,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    ListPushDevices200ResponseFromJSON,
    ListPushDevices200ResponseToJSON,
    RegisterPushDevice201ResponseFromJSON,
    RegisterPushDevice201ResponseToJSON,
    RegisterPushDeviceRequestFromJSON,
    RegisterPushDeviceRequestToJSON,
    UnregisterPushDeviceRequestFromJSON,
    UnregisterPushDeviceRequestToJSON,
    ValidationErrorResponseFromJSON,
    ValidationErrorResponseToJSON,
} from '../models/index';

export interface ListPushDevicesRequest {
    xOmnismithProjectId?: string;
}

export interface RegisterPushDeviceOperationRequest {
    registerPushDeviceRequest: RegisterPushDeviceRequest;
    xOmnismithProjectId?: string;
}

export interface UnregisterPushDeviceOperationRequest {
    unregisterPushDeviceRequest: UnregisterPushDeviceRequest;
    xOmnismithProjectId?: string;
}

/**
 * AutomationPushDevicesApi - interface
 * 
 * @export
 * @interface AutomationPushDevicesApiInterface
 */
export interface AutomationPushDevicesApiInterface {
    /**
     * Creates request options for listPushDevices without sending the request
     * @param {string} [xOmnismithProjectId] The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential\&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time.
     * @throws {RequiredError}
     * @memberof AutomationPushDevicesApiInterface
     */
    listPushDevicesRequestOpts(requestParameters: ListPushDevicesRequest): Promise<runtime.RequestOpts>;

    /**
     * Retrieves all Firebase Cloud Messaging (FCM) mobile push devices registered under the authenticated user account for receiving automated push alerts. Device registration tokens are masked in the output for security.
     * @summary List registered push devices
     * @param {string} [xOmnismithProjectId] The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential\&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AutomationPushDevicesApiInterface
     */
    listPushDevicesRaw(requestParameters: ListPushDevicesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListPushDevices200Response>>;

    /**
     * Retrieves all Firebase Cloud Messaging (FCM) mobile push devices registered under the authenticated user account for receiving automated push alerts. Device registration tokens are masked in the output for security.
     * List registered push devices
     */
    listPushDevices(requestParameters: ListPushDevicesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListPushDevices200Response>;

    /**
     * Creates request options for registerPushDevice without sending the request
     * @param {RegisterPushDeviceRequest} registerPushDeviceRequest 
     * @param {string} [xOmnismithProjectId] The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential\&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time.
     * @throws {RequiredError}
     * @memberof AutomationPushDevicesApiInterface
     */
    registerPushDeviceRequestOpts(requestParameters: RegisterPushDeviceOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * Registers an FCM device token under the authenticated user account to receive real-time push notifications from automation action triggers. If the token is already registered, its device name and activity timestamp are updated.
     * @summary Register a mobile push notification device
     * @param {RegisterPushDeviceRequest} registerPushDeviceRequest 
     * @param {string} [xOmnismithProjectId] The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential\&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AutomationPushDevicesApiInterface
     */
    registerPushDeviceRaw(requestParameters: RegisterPushDeviceOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RegisterPushDevice201Response>>;

    /**
     * Registers an FCM device token under the authenticated user account to receive real-time push notifications from automation action triggers. If the token is already registered, its device name and activity timestamp are updated.
     * Register a mobile push notification device
     */
    registerPushDevice(requestParameters: RegisterPushDeviceOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RegisterPushDevice201Response>;

    /**
     * Creates request options for unregisterPushDevice without sending the request
     * @param {UnregisterPushDeviceRequest} unregisterPushDeviceRequest 
     * @param {string} [xOmnismithProjectId] The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential\&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time.
     * @throws {RequiredError}
     * @memberof AutomationPushDevicesApiInterface
     */
    unregisterPushDeviceRequestOpts(requestParameters: UnregisterPushDeviceOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * Removes an FCM push notification device token from the authenticated user profile, stopping all future automation push notifications directed to that device.
     * @summary Unregister a mobile push notification device
     * @param {UnregisterPushDeviceRequest} unregisterPushDeviceRequest 
     * @param {string} [xOmnismithProjectId] The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential\&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AutomationPushDevicesApiInterface
     */
    unregisterPushDeviceRaw(requestParameters: UnregisterPushDeviceOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Removes an FCM push notification device token from the authenticated user profile, stopping all future automation push notifications directed to that device.
     * Unregister a mobile push notification device
     */
    unregisterPushDevice(requestParameters: UnregisterPushDeviceOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class AutomationPushDevicesApi extends runtime.BaseAPI implements AutomationPushDevicesApiInterface {

    /**
     * Creates request options for listPushDevices without sending the request
     */
    async listPushDevicesRequestOpts(requestParameters: ListPushDevicesRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xOmnismithProjectId'] != null) {
            headerParameters['X-Omnismith-Project-Id'] = String(requestParameters['xOmnismithProjectId']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/automation/push-devices`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieves all Firebase Cloud Messaging (FCM) mobile push devices registered under the authenticated user account for receiving automated push alerts. Device registration tokens are masked in the output for security.
     * List registered push devices
     */
    async listPushDevicesRaw(requestParameters: ListPushDevicesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListPushDevices200Response>> {
        const requestOptions = await this.listPushDevicesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListPushDevices200ResponseFromJSON(jsonValue));
    }

    /**
     * Retrieves all Firebase Cloud Messaging (FCM) mobile push devices registered under the authenticated user account for receiving automated push alerts. Device registration tokens are masked in the output for security.
     * List registered push devices
     */
    async listPushDevices(requestParameters: ListPushDevicesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListPushDevices200Response> {
        const response = await this.listPushDevicesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for registerPushDevice without sending the request
     */
    async registerPushDeviceRequestOpts(requestParameters: RegisterPushDeviceOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['registerPushDeviceRequest'] == null) {
            throw new runtime.RequiredError(
                'registerPushDeviceRequest',
                'Required parameter "registerPushDeviceRequest" was null or undefined when calling registerPushDevice().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xOmnismithProjectId'] != null) {
            headerParameters['X-Omnismith-Project-Id'] = String(requestParameters['xOmnismithProjectId']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/automation/push-devices`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RegisterPushDeviceRequestToJSON(requestParameters['registerPushDeviceRequest']),
        };
    }

    /**
     * Registers an FCM device token under the authenticated user account to receive real-time push notifications from automation action triggers. If the token is already registered, its device name and activity timestamp are updated.
     * Register a mobile push notification device
     */
    async registerPushDeviceRaw(requestParameters: RegisterPushDeviceOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RegisterPushDevice201Response>> {
        const requestOptions = await this.registerPushDeviceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RegisterPushDevice201ResponseFromJSON(jsonValue));
    }

    /**
     * Registers an FCM device token under the authenticated user account to receive real-time push notifications from automation action triggers. If the token is already registered, its device name and activity timestamp are updated.
     * Register a mobile push notification device
     */
    async registerPushDevice(requestParameters: RegisterPushDeviceOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RegisterPushDevice201Response> {
        const response = await this.registerPushDeviceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for unregisterPushDevice without sending the request
     */
    async unregisterPushDeviceRequestOpts(requestParameters: UnregisterPushDeviceOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['unregisterPushDeviceRequest'] == null) {
            throw new runtime.RequiredError(
                'unregisterPushDeviceRequest',
                'Required parameter "unregisterPushDeviceRequest" was null or undefined when calling unregisterPushDevice().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xOmnismithProjectId'] != null) {
            headerParameters['X-Omnismith-Project-Id'] = String(requestParameters['xOmnismithProjectId']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/automation/push-devices`;

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: UnregisterPushDeviceRequestToJSON(requestParameters['unregisterPushDeviceRequest']),
        };
    }

    /**
     * Removes an FCM push notification device token from the authenticated user profile, stopping all future automation push notifications directed to that device.
     * Unregister a mobile push notification device
     */
    async unregisterPushDeviceRaw(requestParameters: UnregisterPushDeviceOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.unregisterPushDeviceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Removes an FCM push notification device token from the authenticated user profile, stopping all future automation push notifications directed to that device.
     * Unregister a mobile push notification device
     */
    async unregisterPushDevice(requestParameters: UnregisterPushDeviceOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.unregisterPushDeviceRaw(requestParameters, initOverrides);
    }

}
