/* tslint:disable */
/* eslint-disable */
/**
 * Omnismith API
 * API Documentation for Omnismith
 *
 * The version of the OpenAPI document: 1.0.11
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateEntity201Response,
  CreateEntityRequest,
  EntityResponse,
  ErrorResponse,
  ExportEntitiesRequest,
  GetEntityChart200Response,
  GetEntityHistory200Response,
  ImportEntities200Response,
  IngestMetricsRequest,
  SearchEntities200Response,
  SearchEntitiesRequest,
  SemanticSearchEntitiesRequest,
  SemanticSearchResultItem,
  UpdateEntityRequest,
  ValidationErrorResponse,
} from '../models/index';
import {
    CreateEntity201ResponseFromJSON,
    CreateEntity201ResponseToJSON,
    CreateEntityRequestFromJSON,
    CreateEntityRequestToJSON,
    EntityResponseFromJSON,
    EntityResponseToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    ExportEntitiesRequestFromJSON,
    ExportEntitiesRequestToJSON,
    GetEntityChart200ResponseFromJSON,
    GetEntityChart200ResponseToJSON,
    GetEntityHistory200ResponseFromJSON,
    GetEntityHistory200ResponseToJSON,
    ImportEntities200ResponseFromJSON,
    ImportEntities200ResponseToJSON,
    IngestMetricsRequestFromJSON,
    IngestMetricsRequestToJSON,
    SearchEntities200ResponseFromJSON,
    SearchEntities200ResponseToJSON,
    SearchEntitiesRequestFromJSON,
    SearchEntitiesRequestToJSON,
    SemanticSearchEntitiesRequestFromJSON,
    SemanticSearchEntitiesRequestToJSON,
    SemanticSearchResultItemFromJSON,
    SemanticSearchResultItemToJSON,
    UpdateEntityRequestFromJSON,
    UpdateEntityRequestToJSON,
    ValidationErrorResponseFromJSON,
    ValidationErrorResponseToJSON,
} from '../models/index';

export interface CreateEntityOperationRequest {
    createEntityRequest: CreateEntityRequest;
}

export interface DeleteEntityRequest {
    id: string;
}

export interface ExportEntitiesOperationRequest {
    templateId: string;
    exportEntitiesRequest: ExportEntitiesRequest;
    sortField?: string | null;
    sortDirection?: ExportEntitiesOperationSortDirectionEnum;
}

export interface GetEntityRequest {
    id: string;
    attributeKey?: GetEntityAttributeKeyEnum;
}

export interface GetEntityChartRequest {
    id: string;
    attributeIds: string;
    start: number;
    end: number;
    aggregateFunc?: GetEntityChartAggregateFuncEnum;
    bucketWidth?: GetEntityChartBucketWidthEnum;
}

export interface GetEntityHistoryRequest {
    id: string;
    page?: number;
    limit?: number;
    sortBy?: GetEntityHistorySortByEnum;
    sortDirection?: GetEntityHistorySortDirectionEnum;
    search?: string;
    attributeIds?: string;
    start?: Date;
    end?: Date;
    authorEmail?: string;
}

export interface ImportEntitiesRequest {
    templateId: string;
    file: Blob;
}

export interface IngestEntityMetricsRequest {
    id: string;
    ingestMetricsRequest: IngestMetricsRequest;
}

export interface SearchEntitiesOperationRequest {
    templateId: string;
    searchEntitiesRequest: SearchEntitiesRequest;
    limit?: number;
    offset?: number;
    sortField?: string | null;
    sortDirection?: SearchEntitiesOperationSortDirectionEnum;
    attributeKey?: SearchEntitiesOperationAttributeKeyEnum;
}

export interface SemanticSearchEntitiesOperationRequest {
    semanticSearchEntitiesRequest: SemanticSearchEntitiesRequest;
}

export interface UpdateEntityOperationRequest {
    id: string;
    updateEntityRequest: UpdateEntityRequest;
}

/**
 * EntityApi - interface
 * 
 * @export
 * @interface EntityApiInterface
 */
export interface EntityApiInterface {
    /**
     * Creates request options for createEntity without sending the request
     * @param {CreateEntityRequest} createEntityRequest 
     * @throws {RequiredError}
     * @memberof EntityApiInterface
     */
    createEntityRequestOpts(requestParameters: CreateEntityOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * Creates a new dynamic entity record conforming to a template schema.  ### Template Association Specify the target schema via either `template_id` (UUID) or `template_slug` (human-readable slug).  ### Dynamic Attribute Values (`attribute_values`) Each attribute entry supports identifier resolution and accepts either: - `attribute_id`: Canonical attribute UUID - `attribute_slug`: Attribute slug identifier (e.g. `price`, `sku`, `status`)  ### Value Formatting Rules - **Dimension - Text / Markdown**: UTF-8 string value (e.g., `\"Wireless Headphones\"`) - **Dimension - Number**: Numeric string representation (e.g., `\"129.99\"`, `\"42\"`) - **Dimension - Boolean**: Strict boolean representation: `\"true\"`, `\"false\"`, `\"1\"`, or `\"0\"` - **Dimension - Date & Datetime**: Formatted as `YYYY-MM-DD` (date) or `YYYY-MM-DD HH:MM:SS` / ISO 8601 `YYYY-MM-DDTHH:MM:SSZ` (datetime) - **Dimension - File & Image**: UUID string of a pre-uploaded workspace file asset - **List Attribute**: Must provide the exact UUID string of a valid defined `ListItem` option - **Reference Attribute**: Must provide the exact UUID string of an existing referenced `Entity`  ### Metric Telemetry Persistence Any metric attributes included in `attribute_values` are published directly to the metric ingestion pipeline and recorded in time-series telemetry storage.
     * @summary Create a new dynamic entity
     * @param {CreateEntityRequest} createEntityRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EntityApiInterface
     */
    createEntityRaw(requestParameters: CreateEntityOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateEntity201Response>>;

    /**
     * Creates a new dynamic entity record conforming to a template schema.  ### Template Association Specify the target schema via either `template_id` (UUID) or `template_slug` (human-readable slug).  ### Dynamic Attribute Values (`attribute_values`) Each attribute entry supports identifier resolution and accepts either: - `attribute_id`: Canonical attribute UUID - `attribute_slug`: Attribute slug identifier (e.g. `price`, `sku`, `status`)  ### Value Formatting Rules - **Dimension - Text / Markdown**: UTF-8 string value (e.g., `\"Wireless Headphones\"`) - **Dimension - Number**: Numeric string representation (e.g., `\"129.99\"`, `\"42\"`) - **Dimension - Boolean**: Strict boolean representation: `\"true\"`, `\"false\"`, `\"1\"`, or `\"0\"` - **Dimension - Date & Datetime**: Formatted as `YYYY-MM-DD` (date) or `YYYY-MM-DD HH:MM:SS` / ISO 8601 `YYYY-MM-DDTHH:MM:SSZ` (datetime) - **Dimension - File & Image**: UUID string of a pre-uploaded workspace file asset - **List Attribute**: Must provide the exact UUID string of a valid defined `ListItem` option - **Reference Attribute**: Must provide the exact UUID string of an existing referenced `Entity`  ### Metric Telemetry Persistence Any metric attributes included in `attribute_values` are published directly to the metric ingestion pipeline and recorded in time-series telemetry storage.
     * Create a new dynamic entity
     */
    createEntity(requestParameters: CreateEntityOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateEntity201Response>;

    /**
     * Creates request options for deleteEntity without sending the request
     * @param {string} id Unique entity identifier (UUID) to soft-delete
     * @throws {RequiredError}
     * @memberof EntityApiInterface
     */
    deleteEntityRequestOpts(requestParameters: DeleteEntityRequest): Promise<runtime.RequestOpts>;

    /**
     * Marks an entity record as soft-deleted by setting its `deleted_at` timestamp.  Soft-deleted entities are immediately excluded from standard entity searches, BI row queries, and direct retrieval endpoints. Associated historical change logs and time-series telemetry remain preserved for audit compliance.
     * @summary Soft-delete an entity record
     * @param {string} id Unique entity identifier (UUID) to soft-delete
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EntityApiInterface
     */
    deleteEntityRaw(requestParameters: DeleteEntityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Marks an entity record as soft-deleted by setting its `deleted_at` timestamp.  Soft-deleted entities are immediately excluded from standard entity searches, BI row queries, and direct retrieval endpoints. Associated historical change logs and time-series telemetry remain preserved for audit compliance.
     * Soft-delete an entity record
     */
    deleteEntity(requestParameters: DeleteEntityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for exportEntities without sending the request
     * @param {string} templateId Unique identifier (UUID) of the template schema to export
     * @param {ExportEntitiesRequest} exportEntitiesRequest 
     * @param {string} [sortField] Attribute UUID, attribute slug, or standard field (id, created_at, updated_at, deleted_at) to sort by
     * @param {'asc' | 'desc'} [sortDirection] Sort direction: \&quot;asc\&quot; (ascending) or \&quot;desc\&quot; (descending)
     * @throws {RequiredError}
     * @memberof EntityApiInterface
     */
    exportEntitiesRequestOpts(requestParameters: ExportEntitiesOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * Exports entity records of a template schema matching filter criteria as a streaming CSV download.  ### Re-importable CSV Schema Format The generated CSV conforms to the Omnismith two-row metadata specification, making it directly compatible with `POST /entities/import/{template_id}`: - **Row 1**: Display column names and attribute aliases. - **Row 2**: Metadata row prefixed with `#` containing attribute UUIDs and column IDs (e.g. `#id`, `#018b2f1b-8c1a...`). - **Row 3+**: Entity data records.  ### Filter & Search Model Accepts the same filtering payload as `SearchEntities`: structured `filters` (supporting `eq`, `neq`, `gt`, `lt`, `like`, `not-like`, `empty`, `not-empty`) and `global_search` text queries.  ### Sorting Sort results via `sort_field` (attribute UUID, slug, or standard timestamp) and `sort_direction` (`asc`/`desc`).
     * @summary Export entities to structured CSV file
     * @param {string} templateId Unique identifier (UUID) of the template schema to export
     * @param {ExportEntitiesRequest} exportEntitiesRequest 
     * @param {string} [sortField] Attribute UUID, attribute slug, or standard field (id, created_at, updated_at, deleted_at) to sort by
     * @param {'asc' | 'desc'} [sortDirection] Sort direction: \&quot;asc\&quot; (ascending) or \&quot;desc\&quot; (descending)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EntityApiInterface
     */
    exportEntitiesRaw(requestParameters: ExportEntitiesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>>;

    /**
     * Exports entity records of a template schema matching filter criteria as a streaming CSV download.  ### Re-importable CSV Schema Format The generated CSV conforms to the Omnismith two-row metadata specification, making it directly compatible with `POST /entities/import/{template_id}`: - **Row 1**: Display column names and attribute aliases. - **Row 2**: Metadata row prefixed with `#` containing attribute UUIDs and column IDs (e.g. `#id`, `#018b2f1b-8c1a...`). - **Row 3+**: Entity data records.  ### Filter & Search Model Accepts the same filtering payload as `SearchEntities`: structured `filters` (supporting `eq`, `neq`, `gt`, `lt`, `like`, `not-like`, `empty`, `not-empty`) and `global_search` text queries.  ### Sorting Sort results via `sort_field` (attribute UUID, slug, or standard timestamp) and `sort_direction` (`asc`/`desc`).
     * Export entities to structured CSV file
     */
    exportEntities(requestParameters: ExportEntitiesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob>;

    /**
     * Creates request options for getEntity without sending the request
     * @param {string} id Unique entity identifier (UUID)
     * @param {'id' | 'slug'} [attributeKey] Format for attribute_values dictionary keys: \&quot;id\&quot; for attribute UUIDs or \&quot;slug\&quot; for human-readable attribute slugs
     * @throws {RequiredError}
     * @memberof EntityApiInterface
     */
    getEntityRequestOpts(requestParameters: GetEntityRequest): Promise<runtime.RequestOpts>;

    /**
     * Retrieves the full hydrated record for a dynamic entity by its unique identifier (UUID).  ### Attribute Key Formatting (`attribute_key`) The `attribute_key` query parameter controls the dictionary keys in `attribute_values`: - `\"id\"` (default): Keys are canonical attribute UUIDs (e.g. `018b2f1b-8c1a...`). - `\"slug\"`: Keys are human-readable attribute slugs (e.g. `price`, `sku`, `category`), which is recommended for API consumers and AI agent workflows.  ### Hydrated Attribute Values The returned `attribute_values` object includes both raw serialized values and resolved display labels (`custom_value`) for references and list options.
     * @summary Get an entity record by ID
     * @param {string} id Unique entity identifier (UUID)
     * @param {'id' | 'slug'} [attributeKey] Format for attribute_values dictionary keys: \&quot;id\&quot; for attribute UUIDs or \&quot;slug\&quot; for human-readable attribute slugs
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EntityApiInterface
     */
    getEntityRaw(requestParameters: GetEntityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityResponse>>;

    /**
     * Retrieves the full hydrated record for a dynamic entity by its unique identifier (UUID).  ### Attribute Key Formatting (`attribute_key`) The `attribute_key` query parameter controls the dictionary keys in `attribute_values`: - `\"id\"` (default): Keys are canonical attribute UUIDs (e.g. `018b2f1b-8c1a...`). - `\"slug\"`: Keys are human-readable attribute slugs (e.g. `price`, `sku`, `category`), which is recommended for API consumers and AI agent workflows.  ### Hydrated Attribute Values The returned `attribute_values` object includes both raw serialized values and resolved display labels (`custom_value`) for references and list options.
     * Get an entity record by ID
     */
    getEntity(requestParameters: GetEntityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityResponse>;

    /**
     * Creates request options for getEntityChart without sending the request
     * @param {string} id Unique entity identifier (UUID)
     * @param {string} attributeIds Comma-separated metric attribute UUIDs to aggregate
     * @param {number} start Start timestamp as Unix epoch in seconds
     * @param {number} end End timestamp as Unix epoch in seconds
     * @param {'sum' | 'avg' | 'min' | 'max' | 'count' | 'first' | 'last'} [aggregateFunc] Aggregation function applied within each bucket
     * @param {'1 second' | '5 seconds' | '10 seconds' | '1 minute' | '5 minutes' | '10 minutes' | '15 minutes' | '30 minutes' | '1 hour' | '6 hours' | '12 hours' | '1 day' | '1 week' | '1 month'} [bucketWidth] Time bucket width interval (e.g. 1 minute, 5 minutes, 1 hour, 1 day)
     * @throws {RequiredError}
     * @memberof EntityApiInterface
     */
    getEntityChartRequestOpts(requestParameters: GetEntityChartRequest): Promise<runtime.RequestOpts>;

    /**
     * Retrieves aggregated, time-bucketed metric time-series data for an entity.  ### Metric Attribute Filtering (`attribute_ids`) Pass one or more comma-separated metric attribute UUIDs to aggregate across the query window.  ### Aggregation Functions (`aggregate_func`) Supported aggregation operations within each bucket: - `avg` (default): Arithmetic mean of values - `sum`: Sum total of values - `min` / `max`: Minimum / Maximum observed value - `count`: Number of recorded observations - `first` / `last`: Earliest / Latest observation within the time bucket  ### Time Intervals & Bucket Widths (`bucket_width`) Values follow standard time interval notation: `1 second`, `5 seconds`, `10 seconds`, `1 minute` (1m), `5 minutes` (5m), `10 minutes`, `15 minutes`, `30 minutes`, `1 hour` (1h), `6 hours`, `12 hours`, `1 day` (1d), `1 week`, `1 month`.  ### Query Window (`start` & `end`) Query range is defined by `start` and `end` timestamps supplied as integer Unix epoch seconds.
     * @summary Get entity chart time-series data
     * @param {string} id Unique entity identifier (UUID)
     * @param {string} attributeIds Comma-separated metric attribute UUIDs to aggregate
     * @param {number} start Start timestamp as Unix epoch in seconds
     * @param {number} end End timestamp as Unix epoch in seconds
     * @param {'sum' | 'avg' | 'min' | 'max' | 'count' | 'first' | 'last'} [aggregateFunc] Aggregation function applied within each bucket
     * @param {'1 second' | '5 seconds' | '10 seconds' | '1 minute' | '5 minutes' | '10 minutes' | '15 minutes' | '30 minutes' | '1 hour' | '6 hours' | '12 hours' | '1 day' | '1 week' | '1 month'} [bucketWidth] Time bucket width interval (e.g. 1 minute, 5 minutes, 1 hour, 1 day)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EntityApiInterface
     */
    getEntityChartRaw(requestParameters: GetEntityChartRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetEntityChart200Response>>;

    /**
     * Retrieves aggregated, time-bucketed metric time-series data for an entity.  ### Metric Attribute Filtering (`attribute_ids`) Pass one or more comma-separated metric attribute UUIDs to aggregate across the query window.  ### Aggregation Functions (`aggregate_func`) Supported aggregation operations within each bucket: - `avg` (default): Arithmetic mean of values - `sum`: Sum total of values - `min` / `max`: Minimum / Maximum observed value - `count`: Number of recorded observations - `first` / `last`: Earliest / Latest observation within the time bucket  ### Time Intervals & Bucket Widths (`bucket_width`) Values follow standard time interval notation: `1 second`, `5 seconds`, `10 seconds`, `1 minute` (1m), `5 minutes` (5m), `10 minutes`, `15 minutes`, `30 minutes`, `1 hour` (1h), `6 hours`, `12 hours`, `1 day` (1d), `1 week`, `1 month`.  ### Query Window (`start` & `end`) Query range is defined by `start` and `end` timestamps supplied as integer Unix epoch seconds.
     * Get entity chart time-series data
     */
    getEntityChart(requestParameters: GetEntityChartRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetEntityChart200Response>;

    /**
     * Creates request options for getEntityHistory without sending the request
     * @param {string} id Unique entity identifier (UUID)
     * @param {number} [page] 1-based page number for pagination
     * @param {number} [limit] Number of history records per page (1-100)
     * @param {'created_at' | 'attribute_id' | 'value'} [sortBy] Field to sort change logs by
     * @param {'asc' | 'desc'} [sortDirection] Sort direction: \&quot;asc\&quot; (ascending) or \&quot;desc\&quot; (descending)
     * @param {string} [search] Free-text search filter matching against old and new attribute values
     * @param {string} [attributeIds] Comma-separated attribute UUIDs to filter change history
     * @param {Date} [start] Filter change records occurring on or after this timestamp (ISO 8601 or YYYY-MM-DD HH:MM:SS format)
     * @param {Date} [end] Filter change records occurring on or before this timestamp (ISO 8601 or YYYY-MM-DD HH:MM:SS format)
     * @param {string} [authorEmail] Filter change records by author or actor email
     * @throws {RequiredError}
     * @memberof EntityApiInterface
     */
    getEntityHistoryRequestOpts(requestParameters: GetEntityHistoryRequest): Promise<runtime.RequestOpts>;

    /**
     * Retrieves the immutable change audit log for an entity\'s dimension attribute mutations.  ### Dedicated Dimension Audit Log Records all historical mutations to dimension, list, and reference attribute values. High-volume metric telemetry observations bypass this log and are stored in dedicated time-series storage, keeping the audit log clean and performant.  ### Filtering & Search - `attribute_ids`: Filter by one or more comma-separated attribute UUIDs. - `search`: Text search matching historical serialized values. - `start` and `end`: Filter history records within a timestamp window (ISO 8601 or `YYYY-MM-DD HH:MM:SS`). - `author_email`: Filter by the actor who performed the mutation.  ### Pagination & Sorting Supports 1-indexed pagination (`page`, `limit` up to 100) and sorting by `created_at`, `attribute_id`, or `value` (`asc`/`desc`).
     * @summary Get entity dimension change history
     * @param {string} id Unique entity identifier (UUID)
     * @param {number} [page] 1-based page number for pagination
     * @param {number} [limit] Number of history records per page (1-100)
     * @param {'created_at' | 'attribute_id' | 'value'} [sortBy] Field to sort change logs by
     * @param {'asc' | 'desc'} [sortDirection] Sort direction: \&quot;asc\&quot; (ascending) or \&quot;desc\&quot; (descending)
     * @param {string} [search] Free-text search filter matching against old and new attribute values
     * @param {string} [attributeIds] Comma-separated attribute UUIDs to filter change history
     * @param {Date} [start] Filter change records occurring on or after this timestamp (ISO 8601 or YYYY-MM-DD HH:MM:SS format)
     * @param {Date} [end] Filter change records occurring on or before this timestamp (ISO 8601 or YYYY-MM-DD HH:MM:SS format)
     * @param {string} [authorEmail] Filter change records by author or actor email
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EntityApiInterface
     */
    getEntityHistoryRaw(requestParameters: GetEntityHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetEntityHistory200Response>>;

    /**
     * Retrieves the immutable change audit log for an entity\'s dimension attribute mutations.  ### Dedicated Dimension Audit Log Records all historical mutations to dimension, list, and reference attribute values. High-volume metric telemetry observations bypass this log and are stored in dedicated time-series storage, keeping the audit log clean and performant.  ### Filtering & Search - `attribute_ids`: Filter by one or more comma-separated attribute UUIDs. - `search`: Text search matching historical serialized values. - `start` and `end`: Filter history records within a timestamp window (ISO 8601 or `YYYY-MM-DD HH:MM:SS`). - `author_email`: Filter by the actor who performed the mutation.  ### Pagination & Sorting Supports 1-indexed pagination (`page`, `limit` up to 100) and sorting by `created_at`, `attribute_id`, or `value` (`asc`/`desc`).
     * Get entity dimension change history
     */
    getEntityHistory(requestParameters: GetEntityHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetEntityHistory200Response>;

    /**
     * Creates request options for importEntities without sending the request
     * @param {string} templateId Unique identifier (UUID) of the template schema to import entities into
     * @param {Blob} file CSV file exported from the export endpoint or matching its format
     * @throws {RequiredError}
     * @memberof EntityApiInterface
     */
    importEntitiesRequestOpts(requestParameters: ImportEntitiesRequest): Promise<runtime.RequestOpts>;

    /**
     * Bulk imports entity records into a template schema from a structured CSV file.  ### Upsert Semantics - **Update existing**: If a data row includes an `id` matching an existing entity UUID, that entity is updated. - **Create new**: If the `id` column is empty, omitted, or contains a new UUID, a new entity record is created.  ### Required 2-Row CSV Header Format The CSV file must follow the Omnismith two-row header format (identical to the output of `POST /entities/export/{template_id}`): - **Row 1 (Display Header)**: Human-readable attribute names or aliases (e.g. `ID`, `SKU`, `Price`, `Category`). - **Row 2 (Metadata Marker)**: Canonical attribute identifiers prefixed by `#` (e.g. `#id`, `#018b2f1b-8c1a...`, `#018b2f1b-8c1b...`). - **Row 3+ (Data Rows)**: Serialized entity values conforming to the template\'s attribute data types.  ### Attribute Value Validation - List attributes require valid `ListItem` option UUIDs. - Reference attributes require existing target `Entity` UUIDs. - Number/Date/Boolean fields must match required format syntax.  ### Execution Summary Returns an execution report detailing counts of created, updated, skipped, and failed rows, along with granular row/column error messages.
     * @summary Import entities from structured CSV file
     * @param {string} templateId Unique identifier (UUID) of the template schema to import entities into
     * @param {Blob} file CSV file exported from the export endpoint or matching its format
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EntityApiInterface
     */
    importEntitiesRaw(requestParameters: ImportEntitiesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ImportEntities200Response>>;

    /**
     * Bulk imports entity records into a template schema from a structured CSV file.  ### Upsert Semantics - **Update existing**: If a data row includes an `id` matching an existing entity UUID, that entity is updated. - **Create new**: If the `id` column is empty, omitted, or contains a new UUID, a new entity record is created.  ### Required 2-Row CSV Header Format The CSV file must follow the Omnismith two-row header format (identical to the output of `POST /entities/export/{template_id}`): - **Row 1 (Display Header)**: Human-readable attribute names or aliases (e.g. `ID`, `SKU`, `Price`, `Category`). - **Row 2 (Metadata Marker)**: Canonical attribute identifiers prefixed by `#` (e.g. `#id`, `#018b2f1b-8c1a...`, `#018b2f1b-8c1b...`). - **Row 3+ (Data Rows)**: Serialized entity values conforming to the template\'s attribute data types.  ### Attribute Value Validation - List attributes require valid `ListItem` option UUIDs. - Reference attributes require existing target `Entity` UUIDs. - Number/Date/Boolean fields must match required format syntax.  ### Execution Summary Returns an execution report detailing counts of created, updated, skipped, and failed rows, along with granular row/column error messages.
     * Import entities from structured CSV file
     */
    importEntities(requestParameters: ImportEntitiesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ImportEntities200Response>;

    /**
     * Creates request options for ingestEntityMetrics without sending the request
     * @param {string} id Unique entity identifier (UUID)
     * @param {IngestMetricsRequest} ingestMetricsRequest 
     * @throws {RequiredError}
     * @memberof EntityApiInterface
     */
    ingestEntityMetricsRequestOpts(requestParameters: IngestEntityMetricsRequest): Promise<runtime.RequestOpts>;

    /**
     * Ingests time-series metric observations for an entity record.  ### Batch Telemetry Ingestion Accepts a batch array of metric observations (`metric_values`). Each observation targets a metric attribute by `attribute_id` (UUID) or `attribute_slug` and specifies a numeric `value`.  ### High-Throughput Streaming Architecture Metric ingestion calls stream directly into the high-throughput telemetry ingestion pipeline. Asynchronous background consumers persist data points into tenant-scoped time-series storage configured with automated retention and continuous aggregation rollups.  ### Strict Metric Attribute Constraint Only attributes defined with `attribute_type: Metric` are accepted by this endpoint. Mutations to dimension, list, or reference attributes must use `PATCH /entities/{id}` instead.
     * @summary Ingest high-frequency metric observations for an entity
     * @param {string} id Unique entity identifier (UUID)
     * @param {IngestMetricsRequest} ingestMetricsRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EntityApiInterface
     */
    ingestEntityMetricsRaw(requestParameters: IngestEntityMetricsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Ingests time-series metric observations for an entity record.  ### Batch Telemetry Ingestion Accepts a batch array of metric observations (`metric_values`). Each observation targets a metric attribute by `attribute_id` (UUID) or `attribute_slug` and specifies a numeric `value`.  ### High-Throughput Streaming Architecture Metric ingestion calls stream directly into the high-throughput telemetry ingestion pipeline. Asynchronous background consumers persist data points into tenant-scoped time-series storage configured with automated retention and continuous aggregation rollups.  ### Strict Metric Attribute Constraint Only attributes defined with `attribute_type: Metric` are accepted by this endpoint. Mutations to dimension, list, or reference attributes must use `PATCH /entities/{id}` instead.
     * Ingest high-frequency metric observations for an entity
     */
    ingestEntityMetrics(requestParameters: IngestEntityMetricsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for searchEntities without sending the request
     * @param {string} templateId Template UUID or human-readable template slug
     * @param {SearchEntitiesRequest} searchEntitiesRequest 
     * @param {number} [limit] Maximum number of entity records to return (1-100)
     * @param {number} [offset] Zero-based pagination offset
     * @param {string} [sortField] Attribute UUID, attribute slug, or standard field (id, created_at, updated_at, deleted_at) to sort by
     * @param {'asc' | 'desc'} [sortDirection] Sort direction: \&quot;asc\&quot; (ascending) or \&quot;desc\&quot; (descending)
     * @param {'id' | 'slug'} [attributeKey] Format for attribute_values dictionary keys: \&quot;id\&quot; for attribute UUIDs or \&quot;slug\&quot; for human-readable attribute slugs
     * @throws {RequiredError}
     * @memberof EntityApiInterface
     */
    searchEntitiesRequestOpts(requestParameters: SearchEntitiesOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * Executes structured queries, full-text searches, and sorting across dynamic entities of a specified template schema.  ### Template Targeting (`template_id`) Accepts either a canonical template UUID (e.g. `018b2f1b-8c1a...`) or a human-readable template slug (e.g. `product_catalog`).  ### Structured Filters (`filters`) Filter conditions are specified in the request body as an array of filter objects: ```json [   {\"field\": \"status\", \"operator\": \"eq\", \"value\": \"018b2f1b-8c1a-75b3-8000-7f0000010020\"},   {\"field\": \"price\", \"operator\": \"gt\", \"value\": \"100\"},   {\"field\": \"name\", \"operator\": \"like\", \"value\": \"Pro\"} ] ``` - **`field`**: Target attribute UUID, attribute slug, or standard field (`id`, `created_at`, `updated_at`). - **`operator`**: Comparison operator: `eq` (equals), `neq` (not equals), `gt` (greater than), `lt` (less than), `like` (substring / trigram match), `not-like` (does not match), `empty` (is null or empty), `not-empty` (has value). - **`value`**: Target comparison value serialized as string.  ### Global Search (`global_search`) Performs accelerated full-text and GIN trigram matching across all string dimension attributes defined on the template.  ### Sorting & Pagination - **`sort_field`**: Attribute UUID, attribute slug, or standard entity fields (`id`, `created_at`, `updated_at`, `deleted_at`). - **`sort_direction`**: `asc` or `desc` (default: `asc` when `sort_field` is set, otherwise default sort is `created_at` DESC). - **`limit`** and **`offset`**: Bounded pagination (max 100 per page).  ### Attribute Key Formatting (`attribute_key`) Passing `attribute_key=\"slug\"` formats the returned `attribute_values` dictionary keys using human-readable attribute slugs instead of raw UUIDs.
     * @summary Search entities with filtering, sorting, and pagination
     * @param {string} templateId Template UUID or human-readable template slug
     * @param {SearchEntitiesRequest} searchEntitiesRequest 
     * @param {number} [limit] Maximum number of entity records to return (1-100)
     * @param {number} [offset] Zero-based pagination offset
     * @param {string} [sortField] Attribute UUID, attribute slug, or standard field (id, created_at, updated_at, deleted_at) to sort by
     * @param {'asc' | 'desc'} [sortDirection] Sort direction: \&quot;asc\&quot; (ascending) or \&quot;desc\&quot; (descending)
     * @param {'id' | 'slug'} [attributeKey] Format for attribute_values dictionary keys: \&quot;id\&quot; for attribute UUIDs or \&quot;slug\&quot; for human-readable attribute slugs
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EntityApiInterface
     */
    searchEntitiesRaw(requestParameters: SearchEntitiesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SearchEntities200Response>>;

    /**
     * Executes structured queries, full-text searches, and sorting across dynamic entities of a specified template schema.  ### Template Targeting (`template_id`) Accepts either a canonical template UUID (e.g. `018b2f1b-8c1a...`) or a human-readable template slug (e.g. `product_catalog`).  ### Structured Filters (`filters`) Filter conditions are specified in the request body as an array of filter objects: ```json [   {\"field\": \"status\", \"operator\": \"eq\", \"value\": \"018b2f1b-8c1a-75b3-8000-7f0000010020\"},   {\"field\": \"price\", \"operator\": \"gt\", \"value\": \"100\"},   {\"field\": \"name\", \"operator\": \"like\", \"value\": \"Pro\"} ] ``` - **`field`**: Target attribute UUID, attribute slug, or standard field (`id`, `created_at`, `updated_at`). - **`operator`**: Comparison operator: `eq` (equals), `neq` (not equals), `gt` (greater than), `lt` (less than), `like` (substring / trigram match), `not-like` (does not match), `empty` (is null or empty), `not-empty` (has value). - **`value`**: Target comparison value serialized as string.  ### Global Search (`global_search`) Performs accelerated full-text and GIN trigram matching across all string dimension attributes defined on the template.  ### Sorting & Pagination - **`sort_field`**: Attribute UUID, attribute slug, or standard entity fields (`id`, `created_at`, `updated_at`, `deleted_at`). - **`sort_direction`**: `asc` or `desc` (default: `asc` when `sort_field` is set, otherwise default sort is `created_at` DESC). - **`limit`** and **`offset`**: Bounded pagination (max 100 per page).  ### Attribute Key Formatting (`attribute_key`) Passing `attribute_key=\"slug\"` formats the returned `attribute_values` dictionary keys using human-readable attribute slugs instead of raw UUIDs.
     * Search entities with filtering, sorting, and pagination
     */
    searchEntities(requestParameters: SearchEntitiesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SearchEntities200Response>;

    /**
     * Creates request options for semanticSearchEntities without sending the request
     * @param {SemanticSearchEntitiesRequest} semanticSearchEntitiesRequest 
     * @throws {RequiredError}
     * @memberof EntityApiInterface
     */
    semanticSearchEntitiesRequestOpts(requestParameters: SemanticSearchEntitiesOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * Executes an approximate nearest neighbors (ANN) vector similarity search across entity dimension embeddings.  ### 768-Dimensional Embedding Vectors Requires a 768-dimensional float embedding array (`query_vector`) representing the query text or multimodal vector (e.g. generated by Google `text-embedding-004` or similar models).  ### Scoping & Filtering (`template_id`) Pass an optional `template_id` (UUID) or template slug to constrain the semantic search to records belonging to a specific template schema.  ### Cosine Similarity Threshold & Ranking (`threshold`) - `threshold`: Minimum cosine similarity score threshold (range `0.0` to `1.0`, default `0.5`). Observations below this similarity cutoff are discarded. - Matches are returned strictly ranked in descending order of `similarity_score`.  ### Attribute Key Formatting (`attribute_key`) Set `attribute_key=\"slug\"` to format the nested entity `attribute_values` dictionary keys as human-readable slugs instead of raw attribute UUIDs.
     * @summary Perform semantic vector similarity search on entities
     * @param {SemanticSearchEntitiesRequest} semanticSearchEntitiesRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EntityApiInterface
     */
    semanticSearchEntitiesRaw(requestParameters: SemanticSearchEntitiesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SemanticSearchResultItem>>>;

    /**
     * Executes an approximate nearest neighbors (ANN) vector similarity search across entity dimension embeddings.  ### 768-Dimensional Embedding Vectors Requires a 768-dimensional float embedding array (`query_vector`) representing the query text or multimodal vector (e.g. generated by Google `text-embedding-004` or similar models).  ### Scoping & Filtering (`template_id`) Pass an optional `template_id` (UUID) or template slug to constrain the semantic search to records belonging to a specific template schema.  ### Cosine Similarity Threshold & Ranking (`threshold`) - `threshold`: Minimum cosine similarity score threshold (range `0.0` to `1.0`, default `0.5`). Observations below this similarity cutoff are discarded. - Matches are returned strictly ranked in descending order of `similarity_score`.  ### Attribute Key Formatting (`attribute_key`) Set `attribute_key=\"slug\"` to format the nested entity `attribute_values` dictionary keys as human-readable slugs instead of raw attribute UUIDs.
     * Perform semantic vector similarity search on entities
     */
    semanticSearchEntities(requestParameters: SemanticSearchEntitiesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SemanticSearchResultItem>>;

    /**
     * Creates request options for updateEntity without sending the request
     * @param {string} id Unique entity identifier (UUID)
     * @param {UpdateEntityRequest} updateEntityRequest 
     * @throws {RequiredError}
     * @memberof EntityApiInterface
     */
    updateEntityRequestOpts(requestParameters: UpdateEntityOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * Updates specific dynamic attribute values for an existing entity record.  ### Dynamic Attribute Values (`attribute_values`) Submit one or more attribute value updates. Each entry supports identifier resolution via: - `attribute_id`: Canonical attribute UUID - `attribute_slug`: Attribute slug identifier (e.g. `price`, `sku`, `status`)  ### Value Formatting Rules - **Dimension - Text / Markdown**: UTF-8 string value - **Dimension - Number**: Numeric string representation (e.g. `\"149.99\"`) - **Dimension - Boolean**: Boolean representation: `\"true\"`, `\"false\"`, `\"1\"`, or `\"0\"` - **Dimension - Date & Datetime**: Formatted as `YYYY-MM-DD` or `YYYY-MM-DD HH:MM:SS` / ISO 8601 `YYYY-MM-DDTHH:MM:SSZ` - **Dimension - File & Image**: UUID string of a pre-uploaded workspace file asset - **List Attribute**: Must provide the exact UUID string of a valid defined `ListItem` option - **Reference Attribute**: Must provide the exact UUID string of an existing referenced `Entity`  ### Audit Trail & Metrics - Dimension updates are recorded in the append-only entity dimension change history log. - Metric attribute values submitted here are dispatched to the metric streaming pipeline for time-series aggregation.
     * @summary Update entity attribute values
     * @param {string} id Unique entity identifier (UUID)
     * @param {UpdateEntityRequest} updateEntityRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EntityApiInterface
     */
    updateEntityRaw(requestParameters: UpdateEntityOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Updates specific dynamic attribute values for an existing entity record.  ### Dynamic Attribute Values (`attribute_values`) Submit one or more attribute value updates. Each entry supports identifier resolution via: - `attribute_id`: Canonical attribute UUID - `attribute_slug`: Attribute slug identifier (e.g. `price`, `sku`, `status`)  ### Value Formatting Rules - **Dimension - Text / Markdown**: UTF-8 string value - **Dimension - Number**: Numeric string representation (e.g. `\"149.99\"`) - **Dimension - Boolean**: Boolean representation: `\"true\"`, `\"false\"`, `\"1\"`, or `\"0\"` - **Dimension - Date & Datetime**: Formatted as `YYYY-MM-DD` or `YYYY-MM-DD HH:MM:SS` / ISO 8601 `YYYY-MM-DDTHH:MM:SSZ` - **Dimension - File & Image**: UUID string of a pre-uploaded workspace file asset - **List Attribute**: Must provide the exact UUID string of a valid defined `ListItem` option - **Reference Attribute**: Must provide the exact UUID string of an existing referenced `Entity`  ### Audit Trail & Metrics - Dimension updates are recorded in the append-only entity dimension change history log. - Metric attribute values submitted here are dispatched to the metric streaming pipeline for time-series aggregation.
     * Update entity attribute values
     */
    updateEntity(requestParameters: UpdateEntityOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class EntityApi extends runtime.BaseAPI implements EntityApiInterface {

    /**
     * Creates request options for createEntity without sending the request
     */
    async createEntityRequestOpts(requestParameters: CreateEntityOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createEntityRequest'] == null) {
            throw new runtime.RequiredError(
                'createEntityRequest',
                'Required parameter "createEntityRequest" was null or undefined when calling createEntity().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/entities`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateEntityRequestToJSON(requestParameters['createEntityRequest']),
        };
    }

    /**
     * Creates a new dynamic entity record conforming to a template schema.  ### Template Association Specify the target schema via either `template_id` (UUID) or `template_slug` (human-readable slug).  ### Dynamic Attribute Values (`attribute_values`) Each attribute entry supports identifier resolution and accepts either: - `attribute_id`: Canonical attribute UUID - `attribute_slug`: Attribute slug identifier (e.g. `price`, `sku`, `status`)  ### Value Formatting Rules - **Dimension - Text / Markdown**: UTF-8 string value (e.g., `\"Wireless Headphones\"`) - **Dimension - Number**: Numeric string representation (e.g., `\"129.99\"`, `\"42\"`) - **Dimension - Boolean**: Strict boolean representation: `\"true\"`, `\"false\"`, `\"1\"`, or `\"0\"` - **Dimension - Date & Datetime**: Formatted as `YYYY-MM-DD` (date) or `YYYY-MM-DD HH:MM:SS` / ISO 8601 `YYYY-MM-DDTHH:MM:SSZ` (datetime) - **Dimension - File & Image**: UUID string of a pre-uploaded workspace file asset - **List Attribute**: Must provide the exact UUID string of a valid defined `ListItem` option - **Reference Attribute**: Must provide the exact UUID string of an existing referenced `Entity`  ### Metric Telemetry Persistence Any metric attributes included in `attribute_values` are published directly to the metric ingestion pipeline and recorded in time-series telemetry storage.
     * Create a new dynamic entity
     */
    async createEntityRaw(requestParameters: CreateEntityOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateEntity201Response>> {
        const requestOptions = await this.createEntityRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateEntity201ResponseFromJSON(jsonValue));
    }

    /**
     * Creates a new dynamic entity record conforming to a template schema.  ### Template Association Specify the target schema via either `template_id` (UUID) or `template_slug` (human-readable slug).  ### Dynamic Attribute Values (`attribute_values`) Each attribute entry supports identifier resolution and accepts either: - `attribute_id`: Canonical attribute UUID - `attribute_slug`: Attribute slug identifier (e.g. `price`, `sku`, `status`)  ### Value Formatting Rules - **Dimension - Text / Markdown**: UTF-8 string value (e.g., `\"Wireless Headphones\"`) - **Dimension - Number**: Numeric string representation (e.g., `\"129.99\"`, `\"42\"`) - **Dimension - Boolean**: Strict boolean representation: `\"true\"`, `\"false\"`, `\"1\"`, or `\"0\"` - **Dimension - Date & Datetime**: Formatted as `YYYY-MM-DD` (date) or `YYYY-MM-DD HH:MM:SS` / ISO 8601 `YYYY-MM-DDTHH:MM:SSZ` (datetime) - **Dimension - File & Image**: UUID string of a pre-uploaded workspace file asset - **List Attribute**: Must provide the exact UUID string of a valid defined `ListItem` option - **Reference Attribute**: Must provide the exact UUID string of an existing referenced `Entity`  ### Metric Telemetry Persistence Any metric attributes included in `attribute_values` are published directly to the metric ingestion pipeline and recorded in time-series telemetry storage.
     * Create a new dynamic entity
     */
    async createEntity(requestParameters: CreateEntityOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateEntity201Response> {
        const response = await this.createEntityRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteEntity without sending the request
     */
    async deleteEntityRequestOpts(requestParameters: DeleteEntityRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteEntity().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/entities/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Marks an entity record as soft-deleted by setting its `deleted_at` timestamp.  Soft-deleted entities are immediately excluded from standard entity searches, BI row queries, and direct retrieval endpoints. Associated historical change logs and time-series telemetry remain preserved for audit compliance.
     * Soft-delete an entity record
     */
    async deleteEntityRaw(requestParameters: DeleteEntityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteEntityRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Marks an entity record as soft-deleted by setting its `deleted_at` timestamp.  Soft-deleted entities are immediately excluded from standard entity searches, BI row queries, and direct retrieval endpoints. Associated historical change logs and time-series telemetry remain preserved for audit compliance.
     * Soft-delete an entity record
     */
    async deleteEntity(requestParameters: DeleteEntityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteEntityRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for exportEntities without sending the request
     */
    async exportEntitiesRequestOpts(requestParameters: ExportEntitiesOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['templateId'] == null) {
            throw new runtime.RequiredError(
                'templateId',
                'Required parameter "templateId" was null or undefined when calling exportEntities().'
            );
        }

        if (requestParameters['exportEntitiesRequest'] == null) {
            throw new runtime.RequiredError(
                'exportEntitiesRequest',
                'Required parameter "exportEntitiesRequest" was null or undefined when calling exportEntities().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['sortField'] != null) {
            queryParameters['sort_field'] = requestParameters['sortField'];
        }

        if (requestParameters['sortDirection'] != null) {
            queryParameters['sort_direction'] = requestParameters['sortDirection'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/entities/export/{template_id}`;
        urlPath = urlPath.replace(`{${"template_id"}}`, encodeURIComponent(String(requestParameters['templateId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ExportEntitiesRequestToJSON(requestParameters['exportEntitiesRequest']),
        };
    }

    /**
     * Exports entity records of a template schema matching filter criteria as a streaming CSV download.  ### Re-importable CSV Schema Format The generated CSV conforms to the Omnismith two-row metadata specification, making it directly compatible with `POST /entities/import/{template_id}`: - **Row 1**: Display column names and attribute aliases. - **Row 2**: Metadata row prefixed with `#` containing attribute UUIDs and column IDs (e.g. `#id`, `#018b2f1b-8c1a...`). - **Row 3+**: Entity data records.  ### Filter & Search Model Accepts the same filtering payload as `SearchEntities`: structured `filters` (supporting `eq`, `neq`, `gt`, `lt`, `like`, `not-like`, `empty`, `not-empty`) and `global_search` text queries.  ### Sorting Sort results via `sort_field` (attribute UUID, slug, or standard timestamp) and `sort_direction` (`asc`/`desc`).
     * Export entities to structured CSV file
     */
    async exportEntitiesRaw(requestParameters: ExportEntitiesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        const requestOptions = await this.exportEntitiesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Exports entity records of a template schema matching filter criteria as a streaming CSV download.  ### Re-importable CSV Schema Format The generated CSV conforms to the Omnismith two-row metadata specification, making it directly compatible with `POST /entities/import/{template_id}`: - **Row 1**: Display column names and attribute aliases. - **Row 2**: Metadata row prefixed with `#` containing attribute UUIDs and column IDs (e.g. `#id`, `#018b2f1b-8c1a...`). - **Row 3+**: Entity data records.  ### Filter & Search Model Accepts the same filtering payload as `SearchEntities`: structured `filters` (supporting `eq`, `neq`, `gt`, `lt`, `like`, `not-like`, `empty`, `not-empty`) and `global_search` text queries.  ### Sorting Sort results via `sort_field` (attribute UUID, slug, or standard timestamp) and `sort_direction` (`asc`/`desc`).
     * Export entities to structured CSV file
     */
    async exportEntities(requestParameters: ExportEntitiesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.exportEntitiesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getEntity without sending the request
     */
    async getEntityRequestOpts(requestParameters: GetEntityRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getEntity().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['attributeKey'] != null) {
            queryParameters['attribute_key'] = requestParameters['attributeKey'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/entities/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieves the full hydrated record for a dynamic entity by its unique identifier (UUID).  ### Attribute Key Formatting (`attribute_key`) The `attribute_key` query parameter controls the dictionary keys in `attribute_values`: - `\"id\"` (default): Keys are canonical attribute UUIDs (e.g. `018b2f1b-8c1a...`). - `\"slug\"`: Keys are human-readable attribute slugs (e.g. `price`, `sku`, `category`), which is recommended for API consumers and AI agent workflows.  ### Hydrated Attribute Values The returned `attribute_values` object includes both raw serialized values and resolved display labels (`custom_value`) for references and list options.
     * Get an entity record by ID
     */
    async getEntityRaw(requestParameters: GetEntityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityResponse>> {
        const requestOptions = await this.getEntityRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityResponseFromJSON(jsonValue));
    }

    /**
     * Retrieves the full hydrated record for a dynamic entity by its unique identifier (UUID).  ### Attribute Key Formatting (`attribute_key`) The `attribute_key` query parameter controls the dictionary keys in `attribute_values`: - `\"id\"` (default): Keys are canonical attribute UUIDs (e.g. `018b2f1b-8c1a...`). - `\"slug\"`: Keys are human-readable attribute slugs (e.g. `price`, `sku`, `category`), which is recommended for API consumers and AI agent workflows.  ### Hydrated Attribute Values The returned `attribute_values` object includes both raw serialized values and resolved display labels (`custom_value`) for references and list options.
     * Get an entity record by ID
     */
    async getEntity(requestParameters: GetEntityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityResponse> {
        const response = await this.getEntityRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getEntityChart without sending the request
     */
    async getEntityChartRequestOpts(requestParameters: GetEntityChartRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getEntityChart().'
            );
        }

        if (requestParameters['attributeIds'] == null) {
            throw new runtime.RequiredError(
                'attributeIds',
                'Required parameter "attributeIds" was null or undefined when calling getEntityChart().'
            );
        }

        if (requestParameters['start'] == null) {
            throw new runtime.RequiredError(
                'start',
                'Required parameter "start" was null or undefined when calling getEntityChart().'
            );
        }

        if (requestParameters['end'] == null) {
            throw new runtime.RequiredError(
                'end',
                'Required parameter "end" was null or undefined when calling getEntityChart().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['attributeIds'] != null) {
            queryParameters['attribute_ids'] = requestParameters['attributeIds'];
        }

        if (requestParameters['aggregateFunc'] != null) {
            queryParameters['aggregate_func'] = requestParameters['aggregateFunc'];
        }

        if (requestParameters['bucketWidth'] != null) {
            queryParameters['bucket_width'] = requestParameters['bucketWidth'];
        }

        if (requestParameters['start'] != null) {
            queryParameters['start'] = requestParameters['start'];
        }

        if (requestParameters['end'] != null) {
            queryParameters['end'] = requestParameters['end'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/entities/{id}/chart`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieves aggregated, time-bucketed metric time-series data for an entity.  ### Metric Attribute Filtering (`attribute_ids`) Pass one or more comma-separated metric attribute UUIDs to aggregate across the query window.  ### Aggregation Functions (`aggregate_func`) Supported aggregation operations within each bucket: - `avg` (default): Arithmetic mean of values - `sum`: Sum total of values - `min` / `max`: Minimum / Maximum observed value - `count`: Number of recorded observations - `first` / `last`: Earliest / Latest observation within the time bucket  ### Time Intervals & Bucket Widths (`bucket_width`) Values follow standard time interval notation: `1 second`, `5 seconds`, `10 seconds`, `1 minute` (1m), `5 minutes` (5m), `10 minutes`, `15 minutes`, `30 minutes`, `1 hour` (1h), `6 hours`, `12 hours`, `1 day` (1d), `1 week`, `1 month`.  ### Query Window (`start` & `end`) Query range is defined by `start` and `end` timestamps supplied as integer Unix epoch seconds.
     * Get entity chart time-series data
     */
    async getEntityChartRaw(requestParameters: GetEntityChartRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetEntityChart200Response>> {
        const requestOptions = await this.getEntityChartRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetEntityChart200ResponseFromJSON(jsonValue));
    }

    /**
     * Retrieves aggregated, time-bucketed metric time-series data for an entity.  ### Metric Attribute Filtering (`attribute_ids`) Pass one or more comma-separated metric attribute UUIDs to aggregate across the query window.  ### Aggregation Functions (`aggregate_func`) Supported aggregation operations within each bucket: - `avg` (default): Arithmetic mean of values - `sum`: Sum total of values - `min` / `max`: Minimum / Maximum observed value - `count`: Number of recorded observations - `first` / `last`: Earliest / Latest observation within the time bucket  ### Time Intervals & Bucket Widths (`bucket_width`) Values follow standard time interval notation: `1 second`, `5 seconds`, `10 seconds`, `1 minute` (1m), `5 minutes` (5m), `10 minutes`, `15 minutes`, `30 minutes`, `1 hour` (1h), `6 hours`, `12 hours`, `1 day` (1d), `1 week`, `1 month`.  ### Query Window (`start` & `end`) Query range is defined by `start` and `end` timestamps supplied as integer Unix epoch seconds.
     * Get entity chart time-series data
     */
    async getEntityChart(requestParameters: GetEntityChartRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetEntityChart200Response> {
        const response = await this.getEntityChartRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getEntityHistory without sending the request
     */
    async getEntityHistoryRequestOpts(requestParameters: GetEntityHistoryRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getEntityHistory().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['sortBy'] != null) {
            queryParameters['sort_by'] = requestParameters['sortBy'];
        }

        if (requestParameters['sortDirection'] != null) {
            queryParameters['sort_direction'] = requestParameters['sortDirection'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        if (requestParameters['attributeIds'] != null) {
            queryParameters['attribute_ids'] = requestParameters['attributeIds'];
        }

        if (requestParameters['start'] != null) {
            queryParameters['start'] = (requestParameters['start'] as any).toISOString();
        }

        if (requestParameters['end'] != null) {
            queryParameters['end'] = (requestParameters['end'] as any).toISOString();
        }

        if (requestParameters['authorEmail'] != null) {
            queryParameters['author_email'] = requestParameters['authorEmail'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/entities/{id}/history`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieves the immutable change audit log for an entity\'s dimension attribute mutations.  ### Dedicated Dimension Audit Log Records all historical mutations to dimension, list, and reference attribute values. High-volume metric telemetry observations bypass this log and are stored in dedicated time-series storage, keeping the audit log clean and performant.  ### Filtering & Search - `attribute_ids`: Filter by one or more comma-separated attribute UUIDs. - `search`: Text search matching historical serialized values. - `start` and `end`: Filter history records within a timestamp window (ISO 8601 or `YYYY-MM-DD HH:MM:SS`). - `author_email`: Filter by the actor who performed the mutation.  ### Pagination & Sorting Supports 1-indexed pagination (`page`, `limit` up to 100) and sorting by `created_at`, `attribute_id`, or `value` (`asc`/`desc`).
     * Get entity dimension change history
     */
    async getEntityHistoryRaw(requestParameters: GetEntityHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetEntityHistory200Response>> {
        const requestOptions = await this.getEntityHistoryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetEntityHistory200ResponseFromJSON(jsonValue));
    }

    /**
     * Retrieves the immutable change audit log for an entity\'s dimension attribute mutations.  ### Dedicated Dimension Audit Log Records all historical mutations to dimension, list, and reference attribute values. High-volume metric telemetry observations bypass this log and are stored in dedicated time-series storage, keeping the audit log clean and performant.  ### Filtering & Search - `attribute_ids`: Filter by one or more comma-separated attribute UUIDs. - `search`: Text search matching historical serialized values. - `start` and `end`: Filter history records within a timestamp window (ISO 8601 or `YYYY-MM-DD HH:MM:SS`). - `author_email`: Filter by the actor who performed the mutation.  ### Pagination & Sorting Supports 1-indexed pagination (`page`, `limit` up to 100) and sorting by `created_at`, `attribute_id`, or `value` (`asc`/`desc`).
     * Get entity dimension change history
     */
    async getEntityHistory(requestParameters: GetEntityHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetEntityHistory200Response> {
        const response = await this.getEntityHistoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for importEntities without sending the request
     */
    async importEntitiesRequestOpts(requestParameters: ImportEntitiesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['templateId'] == null) {
            throw new runtime.RequiredError(
                'templateId',
                'Required parameter "templateId" was null or undefined when calling importEntities().'
            );
        }

        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling importEntities().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }


        let urlPath = `/entities/import/{template_id}`;
        urlPath = urlPath.replace(`{${"template_id"}}`, encodeURIComponent(String(requestParameters['templateId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     * Bulk imports entity records into a template schema from a structured CSV file.  ### Upsert Semantics - **Update existing**: If a data row includes an `id` matching an existing entity UUID, that entity is updated. - **Create new**: If the `id` column is empty, omitted, or contains a new UUID, a new entity record is created.  ### Required 2-Row CSV Header Format The CSV file must follow the Omnismith two-row header format (identical to the output of `POST /entities/export/{template_id}`): - **Row 1 (Display Header)**: Human-readable attribute names or aliases (e.g. `ID`, `SKU`, `Price`, `Category`). - **Row 2 (Metadata Marker)**: Canonical attribute identifiers prefixed by `#` (e.g. `#id`, `#018b2f1b-8c1a...`, `#018b2f1b-8c1b...`). - **Row 3+ (Data Rows)**: Serialized entity values conforming to the template\'s attribute data types.  ### Attribute Value Validation - List attributes require valid `ListItem` option UUIDs. - Reference attributes require existing target `Entity` UUIDs. - Number/Date/Boolean fields must match required format syntax.  ### Execution Summary Returns an execution report detailing counts of created, updated, skipped, and failed rows, along with granular row/column error messages.
     * Import entities from structured CSV file
     */
    async importEntitiesRaw(requestParameters: ImportEntitiesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ImportEntities200Response>> {
        const requestOptions = await this.importEntitiesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ImportEntities200ResponseFromJSON(jsonValue));
    }

    /**
     * Bulk imports entity records into a template schema from a structured CSV file.  ### Upsert Semantics - **Update existing**: If a data row includes an `id` matching an existing entity UUID, that entity is updated. - **Create new**: If the `id` column is empty, omitted, or contains a new UUID, a new entity record is created.  ### Required 2-Row CSV Header Format The CSV file must follow the Omnismith two-row header format (identical to the output of `POST /entities/export/{template_id}`): - **Row 1 (Display Header)**: Human-readable attribute names or aliases (e.g. `ID`, `SKU`, `Price`, `Category`). - **Row 2 (Metadata Marker)**: Canonical attribute identifiers prefixed by `#` (e.g. `#id`, `#018b2f1b-8c1a...`, `#018b2f1b-8c1b...`). - **Row 3+ (Data Rows)**: Serialized entity values conforming to the template\'s attribute data types.  ### Attribute Value Validation - List attributes require valid `ListItem` option UUIDs. - Reference attributes require existing target `Entity` UUIDs. - Number/Date/Boolean fields must match required format syntax.  ### Execution Summary Returns an execution report detailing counts of created, updated, skipped, and failed rows, along with granular row/column error messages.
     * Import entities from structured CSV file
     */
    async importEntities(requestParameters: ImportEntitiesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ImportEntities200Response> {
        const response = await this.importEntitiesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for ingestEntityMetrics without sending the request
     */
    async ingestEntityMetricsRequestOpts(requestParameters: IngestEntityMetricsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling ingestEntityMetrics().'
            );
        }

        if (requestParameters['ingestMetricsRequest'] == null) {
            throw new runtime.RequiredError(
                'ingestMetricsRequest',
                'Required parameter "ingestMetricsRequest" was null or undefined when calling ingestEntityMetrics().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/entities/{id}/metrics`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: IngestMetricsRequestToJSON(requestParameters['ingestMetricsRequest']),
        };
    }

    /**
     * Ingests time-series metric observations for an entity record.  ### Batch Telemetry Ingestion Accepts a batch array of metric observations (`metric_values`). Each observation targets a metric attribute by `attribute_id` (UUID) or `attribute_slug` and specifies a numeric `value`.  ### High-Throughput Streaming Architecture Metric ingestion calls stream directly into the high-throughput telemetry ingestion pipeline. Asynchronous background consumers persist data points into tenant-scoped time-series storage configured with automated retention and continuous aggregation rollups.  ### Strict Metric Attribute Constraint Only attributes defined with `attribute_type: Metric` are accepted by this endpoint. Mutations to dimension, list, or reference attributes must use `PATCH /entities/{id}` instead.
     * Ingest high-frequency metric observations for an entity
     */
    async ingestEntityMetricsRaw(requestParameters: IngestEntityMetricsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.ingestEntityMetricsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Ingests time-series metric observations for an entity record.  ### Batch Telemetry Ingestion Accepts a batch array of metric observations (`metric_values`). Each observation targets a metric attribute by `attribute_id` (UUID) or `attribute_slug` and specifies a numeric `value`.  ### High-Throughput Streaming Architecture Metric ingestion calls stream directly into the high-throughput telemetry ingestion pipeline. Asynchronous background consumers persist data points into tenant-scoped time-series storage configured with automated retention and continuous aggregation rollups.  ### Strict Metric Attribute Constraint Only attributes defined with `attribute_type: Metric` are accepted by this endpoint. Mutations to dimension, list, or reference attributes must use `PATCH /entities/{id}` instead.
     * Ingest high-frequency metric observations for an entity
     */
    async ingestEntityMetrics(requestParameters: IngestEntityMetricsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.ingestEntityMetricsRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for searchEntities without sending the request
     */
    async searchEntitiesRequestOpts(requestParameters: SearchEntitiesOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['templateId'] == null) {
            throw new runtime.RequiredError(
                'templateId',
                'Required parameter "templateId" was null or undefined when calling searchEntities().'
            );
        }

        if (requestParameters['searchEntitiesRequest'] == null) {
            throw new runtime.RequiredError(
                'searchEntitiesRequest',
                'Required parameter "searchEntitiesRequest" was null or undefined when calling searchEntities().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['sortField'] != null) {
            queryParameters['sort_field'] = requestParameters['sortField'];
        }

        if (requestParameters['sortDirection'] != null) {
            queryParameters['sort_direction'] = requestParameters['sortDirection'];
        }

        if (requestParameters['attributeKey'] != null) {
            queryParameters['attribute_key'] = requestParameters['attributeKey'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/entities/search/{template_id}`;
        urlPath = urlPath.replace(`{${"template_id"}}`, encodeURIComponent(String(requestParameters['templateId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SearchEntitiesRequestToJSON(requestParameters['searchEntitiesRequest']),
        };
    }

    /**
     * Executes structured queries, full-text searches, and sorting across dynamic entities of a specified template schema.  ### Template Targeting (`template_id`) Accepts either a canonical template UUID (e.g. `018b2f1b-8c1a...`) or a human-readable template slug (e.g. `product_catalog`).  ### Structured Filters (`filters`) Filter conditions are specified in the request body as an array of filter objects: ```json [   {\"field\": \"status\", \"operator\": \"eq\", \"value\": \"018b2f1b-8c1a-75b3-8000-7f0000010020\"},   {\"field\": \"price\", \"operator\": \"gt\", \"value\": \"100\"},   {\"field\": \"name\", \"operator\": \"like\", \"value\": \"Pro\"} ] ``` - **`field`**: Target attribute UUID, attribute slug, or standard field (`id`, `created_at`, `updated_at`). - **`operator`**: Comparison operator: `eq` (equals), `neq` (not equals), `gt` (greater than), `lt` (less than), `like` (substring / trigram match), `not-like` (does not match), `empty` (is null or empty), `not-empty` (has value). - **`value`**: Target comparison value serialized as string.  ### Global Search (`global_search`) Performs accelerated full-text and GIN trigram matching across all string dimension attributes defined on the template.  ### Sorting & Pagination - **`sort_field`**: Attribute UUID, attribute slug, or standard entity fields (`id`, `created_at`, `updated_at`, `deleted_at`). - **`sort_direction`**: `asc` or `desc` (default: `asc` when `sort_field` is set, otherwise default sort is `created_at` DESC). - **`limit`** and **`offset`**: Bounded pagination (max 100 per page).  ### Attribute Key Formatting (`attribute_key`) Passing `attribute_key=\"slug\"` formats the returned `attribute_values` dictionary keys using human-readable attribute slugs instead of raw UUIDs.
     * Search entities with filtering, sorting, and pagination
     */
    async searchEntitiesRaw(requestParameters: SearchEntitiesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SearchEntities200Response>> {
        const requestOptions = await this.searchEntitiesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SearchEntities200ResponseFromJSON(jsonValue));
    }

    /**
     * Executes structured queries, full-text searches, and sorting across dynamic entities of a specified template schema.  ### Template Targeting (`template_id`) Accepts either a canonical template UUID (e.g. `018b2f1b-8c1a...`) or a human-readable template slug (e.g. `product_catalog`).  ### Structured Filters (`filters`) Filter conditions are specified in the request body as an array of filter objects: ```json [   {\"field\": \"status\", \"operator\": \"eq\", \"value\": \"018b2f1b-8c1a-75b3-8000-7f0000010020\"},   {\"field\": \"price\", \"operator\": \"gt\", \"value\": \"100\"},   {\"field\": \"name\", \"operator\": \"like\", \"value\": \"Pro\"} ] ``` - **`field`**: Target attribute UUID, attribute slug, or standard field (`id`, `created_at`, `updated_at`). - **`operator`**: Comparison operator: `eq` (equals), `neq` (not equals), `gt` (greater than), `lt` (less than), `like` (substring / trigram match), `not-like` (does not match), `empty` (is null or empty), `not-empty` (has value). - **`value`**: Target comparison value serialized as string.  ### Global Search (`global_search`) Performs accelerated full-text and GIN trigram matching across all string dimension attributes defined on the template.  ### Sorting & Pagination - **`sort_field`**: Attribute UUID, attribute slug, or standard entity fields (`id`, `created_at`, `updated_at`, `deleted_at`). - **`sort_direction`**: `asc` or `desc` (default: `asc` when `sort_field` is set, otherwise default sort is `created_at` DESC). - **`limit`** and **`offset`**: Bounded pagination (max 100 per page).  ### Attribute Key Formatting (`attribute_key`) Passing `attribute_key=\"slug\"` formats the returned `attribute_values` dictionary keys using human-readable attribute slugs instead of raw UUIDs.
     * Search entities with filtering, sorting, and pagination
     */
    async searchEntities(requestParameters: SearchEntitiesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SearchEntities200Response> {
        const response = await this.searchEntitiesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for semanticSearchEntities without sending the request
     */
    async semanticSearchEntitiesRequestOpts(requestParameters: SemanticSearchEntitiesOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['semanticSearchEntitiesRequest'] == null) {
            throw new runtime.RequiredError(
                'semanticSearchEntitiesRequest',
                'Required parameter "semanticSearchEntitiesRequest" was null or undefined when calling semanticSearchEntities().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/entities/semantic-search`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SemanticSearchEntitiesRequestToJSON(requestParameters['semanticSearchEntitiesRequest']),
        };
    }

    /**
     * Executes an approximate nearest neighbors (ANN) vector similarity search across entity dimension embeddings.  ### 768-Dimensional Embedding Vectors Requires a 768-dimensional float embedding array (`query_vector`) representing the query text or multimodal vector (e.g. generated by Google `text-embedding-004` or similar models).  ### Scoping & Filtering (`template_id`) Pass an optional `template_id` (UUID) or template slug to constrain the semantic search to records belonging to a specific template schema.  ### Cosine Similarity Threshold & Ranking (`threshold`) - `threshold`: Minimum cosine similarity score threshold (range `0.0` to `1.0`, default `0.5`). Observations below this similarity cutoff are discarded. - Matches are returned strictly ranked in descending order of `similarity_score`.  ### Attribute Key Formatting (`attribute_key`) Set `attribute_key=\"slug\"` to format the nested entity `attribute_values` dictionary keys as human-readable slugs instead of raw attribute UUIDs.
     * Perform semantic vector similarity search on entities
     */
    async semanticSearchEntitiesRaw(requestParameters: SemanticSearchEntitiesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SemanticSearchResultItem>>> {
        const requestOptions = await this.semanticSearchEntitiesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SemanticSearchResultItemFromJSON));
    }

    /**
     * Executes an approximate nearest neighbors (ANN) vector similarity search across entity dimension embeddings.  ### 768-Dimensional Embedding Vectors Requires a 768-dimensional float embedding array (`query_vector`) representing the query text or multimodal vector (e.g. generated by Google `text-embedding-004` or similar models).  ### Scoping & Filtering (`template_id`) Pass an optional `template_id` (UUID) or template slug to constrain the semantic search to records belonging to a specific template schema.  ### Cosine Similarity Threshold & Ranking (`threshold`) - `threshold`: Minimum cosine similarity score threshold (range `0.0` to `1.0`, default `0.5`). Observations below this similarity cutoff are discarded. - Matches are returned strictly ranked in descending order of `similarity_score`.  ### Attribute Key Formatting (`attribute_key`) Set `attribute_key=\"slug\"` to format the nested entity `attribute_values` dictionary keys as human-readable slugs instead of raw attribute UUIDs.
     * Perform semantic vector similarity search on entities
     */
    async semanticSearchEntities(requestParameters: SemanticSearchEntitiesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SemanticSearchResultItem>> {
        const response = await this.semanticSearchEntitiesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateEntity without sending the request
     */
    async updateEntityRequestOpts(requestParameters: UpdateEntityOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateEntity().'
            );
        }

        if (requestParameters['updateEntityRequest'] == null) {
            throw new runtime.RequiredError(
                'updateEntityRequest',
                'Required parameter "updateEntityRequest" was null or undefined when calling updateEntity().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/entities/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateEntityRequestToJSON(requestParameters['updateEntityRequest']),
        };
    }

    /**
     * Updates specific dynamic attribute values for an existing entity record.  ### Dynamic Attribute Values (`attribute_values`) Submit one or more attribute value updates. Each entry supports identifier resolution via: - `attribute_id`: Canonical attribute UUID - `attribute_slug`: Attribute slug identifier (e.g. `price`, `sku`, `status`)  ### Value Formatting Rules - **Dimension - Text / Markdown**: UTF-8 string value - **Dimension - Number**: Numeric string representation (e.g. `\"149.99\"`) - **Dimension - Boolean**: Boolean representation: `\"true\"`, `\"false\"`, `\"1\"`, or `\"0\"` - **Dimension - Date & Datetime**: Formatted as `YYYY-MM-DD` or `YYYY-MM-DD HH:MM:SS` / ISO 8601 `YYYY-MM-DDTHH:MM:SSZ` - **Dimension - File & Image**: UUID string of a pre-uploaded workspace file asset - **List Attribute**: Must provide the exact UUID string of a valid defined `ListItem` option - **Reference Attribute**: Must provide the exact UUID string of an existing referenced `Entity`  ### Audit Trail & Metrics - Dimension updates are recorded in the append-only entity dimension change history log. - Metric attribute values submitted here are dispatched to the metric streaming pipeline for time-series aggregation.
     * Update entity attribute values
     */
    async updateEntityRaw(requestParameters: UpdateEntityOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.updateEntityRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Updates specific dynamic attribute values for an existing entity record.  ### Dynamic Attribute Values (`attribute_values`) Submit one or more attribute value updates. Each entry supports identifier resolution via: - `attribute_id`: Canonical attribute UUID - `attribute_slug`: Attribute slug identifier (e.g. `price`, `sku`, `status`)  ### Value Formatting Rules - **Dimension - Text / Markdown**: UTF-8 string value - **Dimension - Number**: Numeric string representation (e.g. `\"149.99\"`) - **Dimension - Boolean**: Boolean representation: `\"true\"`, `\"false\"`, `\"1\"`, or `\"0\"` - **Dimension - Date & Datetime**: Formatted as `YYYY-MM-DD` or `YYYY-MM-DD HH:MM:SS` / ISO 8601 `YYYY-MM-DDTHH:MM:SSZ` - **Dimension - File & Image**: UUID string of a pre-uploaded workspace file asset - **List Attribute**: Must provide the exact UUID string of a valid defined `ListItem` option - **Reference Attribute**: Must provide the exact UUID string of an existing referenced `Entity`  ### Audit Trail & Metrics - Dimension updates are recorded in the append-only entity dimension change history log. - Metric attribute values submitted here are dispatched to the metric streaming pipeline for time-series aggregation.
     * Update entity attribute values
     */
    async updateEntity(requestParameters: UpdateEntityOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.updateEntityRaw(requestParameters, initOverrides);
    }

}

/**
  * @export
  * @enum {string}
  */
export enum ExportEntitiesOperationSortDirectionEnum {
    asc = 'asc',
    desc = 'desc'
}
/**
  * @export
  * @enum {string}
  */
export enum GetEntityAttributeKeyEnum {
    id = 'id',
    slug = 'slug'
}
/**
  * @export
  * @enum {string}
  */
export enum GetEntityChartAggregateFuncEnum {
    sum = 'sum',
    avg = 'avg',
    min = 'min',
    max = 'max',
    count = 'count',
    first = 'first',
    last = 'last'
}
/**
  * @export
  * @enum {string}
  */
export enum GetEntityChartBucketWidthEnum {
    _1_second = '1 second',
    _5_seconds = '5 seconds',
    _10_seconds = '10 seconds',
    _1_minute = '1 minute',
    _5_minutes = '5 minutes',
    _10_minutes = '10 minutes',
    _15_minutes = '15 minutes',
    _30_minutes = '30 minutes',
    _1_hour = '1 hour',
    _6_hours = '6 hours',
    _12_hours = '12 hours',
    _1_day = '1 day',
    _1_week = '1 week',
    _1_month = '1 month'
}
/**
  * @export
  * @enum {string}
  */
export enum GetEntityHistorySortByEnum {
    created_at = 'created_at',
    attribute_id = 'attribute_id',
    value = 'value'
}
/**
  * @export
  * @enum {string}
  */
export enum GetEntityHistorySortDirectionEnum {
    asc = 'asc',
    desc = 'desc'
}
/**
  * @export
  * @enum {string}
  */
export enum SearchEntitiesOperationSortDirectionEnum {
    asc = 'asc',
    desc = 'desc'
}
/**
  * @export
  * @enum {string}
  */
export enum SearchEntitiesOperationAttributeKeyEnum {
    id = 'id',
    slug = 'slug'
}
