/* tslint:disable */
/* eslint-disable */
/**
 * Omnismith API
 * API Documentation for Omnismith
 *
 * The version of the OpenAPI document: 1.0.14
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateProject201Response,
  CreateRoleRequest,
  ErrorResponse,
  GetRolePermissions200Response,
  GetRoleResources200Response,
  GetRoleScopes200Response,
  ListAvailablePermissions200Response,
  ListRoles200Response,
  RoleResponse,
  SetRolePermissionsRequest,
  SetRoleResourcesRequest,
  SetRoleScopesRequest,
  UpdateRoleRequest,
  ValidationErrorResponse,
} from '../models/index';
import {
    CreateProject201ResponseFromJSON,
    CreateProject201ResponseToJSON,
    CreateRoleRequestFromJSON,
    CreateRoleRequestToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    GetRolePermissions200ResponseFromJSON,
    GetRolePermissions200ResponseToJSON,
    GetRoleResources200ResponseFromJSON,
    GetRoleResources200ResponseToJSON,
    GetRoleScopes200ResponseFromJSON,
    GetRoleScopes200ResponseToJSON,
    ListAvailablePermissions200ResponseFromJSON,
    ListAvailablePermissions200ResponseToJSON,
    ListRoles200ResponseFromJSON,
    ListRoles200ResponseToJSON,
    RoleResponseFromJSON,
    RoleResponseToJSON,
    SetRolePermissionsRequestFromJSON,
    SetRolePermissionsRequestToJSON,
    SetRoleResourcesRequestFromJSON,
    SetRoleResourcesRequestToJSON,
    SetRoleScopesRequestFromJSON,
    SetRoleScopesRequestToJSON,
    UpdateRoleRequestFromJSON,
    UpdateRoleRequestToJSON,
    ValidationErrorResponseFromJSON,
    ValidationErrorResponseToJSON,
} from '../models/index';

export interface CreateRoleOperationRequest {
    createRoleRequest: CreateRoleRequest;
    xOmnismithProjectId?: string;
}

export interface DeleteRoleRequest {
    id: string;
    xOmnismithProjectId?: string;
}

export interface GetRoleRequest {
    id: string;
    xOmnismithProjectId?: string;
}

export interface GetRolePermissionsRequest {
    id: string;
    xOmnismithProjectId?: string;
}

export interface GetRoleResourcesRequest {
    id: string;
    xOmnismithProjectId?: string;
}

export interface GetRoleScopesRequest {
    id: string;
    xOmnismithProjectId?: string;
}

export interface ListAvailablePermissionsRequest {
    xOmnismithProjectId?: string;
}

export interface ListRolesRequest {
    xOmnismithProjectId?: string;
}

export interface SetRolePermissionsOperationRequest {
    id: string;
    setRolePermissionsRequest: SetRolePermissionsRequest;
    xOmnismithProjectId?: string;
}

export interface SetRoleResourcesOperationRequest {
    id: string;
    setRoleResourcesRequest: SetRoleResourcesRequest;
    xOmnismithProjectId?: string;
}

export interface SetRoleScopesOperationRequest {
    id: string;
    setRoleScopesRequest: SetRoleScopesRequest;
    xOmnismithProjectId?: string;
}

export interface UpdateRoleOperationRequest {
    id: string;
    updateRoleRequest: UpdateRoleRequest;
    xOmnismithProjectId?: string;
}

/**
 * RolesApi - interface
 * 
 * @export
 * @interface RolesApiInterface
 */
export interface RolesApiInterface {
    /**
     * Creates request options for createRole without sending the request
     * @param {CreateRoleRequest} createRoleRequest 
     * @param {string} [xOmnismithProjectId] The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential\&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time.
     * @throws {RequiredError}
     * @memberof RolesApiInterface
     */
    createRoleRequestOpts(requestParameters: CreateRoleOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * Creates a new custom role within the project. Role permissions, resource restrictions, and entity scopes can be configured subsequently.
     * @summary Create a new role
     * @param {CreateRoleRequest} createRoleRequest 
     * @param {string} [xOmnismithProjectId] The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential\&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RolesApiInterface
     */
    createRoleRaw(requestParameters: CreateRoleOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateProject201Response>>;

    /**
     * Creates a new custom role within the project. Role permissions, resource restrictions, and entity scopes can be configured subsequently.
     * Create a new role
     */
    createRole(requestParameters: CreateRoleOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateProject201Response>;

    /**
     * Creates request options for deleteRole without sending the request
     * @param {string} id Unique UUID of the role to delete
     * @param {string} [xOmnismithProjectId] The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential\&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time.
     * @throws {RequiredError}
     * @memberof RolesApiInterface
     */
    deleteRoleRequestOpts(requestParameters: DeleteRoleRequest): Promise<runtime.RequestOpts>;

    /**
     * Permanently deletes a custom role. System owner roles cannot be deleted. Any users assigned to this role must be reassigned.
     * @summary Delete a role
     * @param {string} id Unique UUID of the role to delete
     * @param {string} [xOmnismithProjectId] The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential\&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RolesApiInterface
     */
    deleteRoleRaw(requestParameters: DeleteRoleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Permanently deletes a custom role. System owner roles cannot be deleted. Any users assigned to this role must be reassigned.
     * Delete a role
     */
    deleteRole(requestParameters: DeleteRoleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for getRole without sending the request
     * @param {string} id Unique UUID of the role
     * @param {string} [xOmnismithProjectId] The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential\&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time.
     * @throws {RequiredError}
     * @memberof RolesApiInterface
     */
    getRoleRequestOpts(requestParameters: GetRoleRequest): Promise<runtime.RequestOpts>;

    /**
     * Retrieves role metadata (name, is_owner status, creation timestamp) by role UUID.
     * @summary Get a role
     * @param {string} id Unique UUID of the role
     * @param {string} [xOmnismithProjectId] The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential\&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RolesApiInterface
     */
    getRoleRaw(requestParameters: GetRoleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RoleResponse>>;

    /**
     * Retrieves role metadata (name, is_owner status, creation timestamp) by role UUID.
     * Get a role
     */
    getRole(requestParameters: GetRoleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RoleResponse>;

    /**
     * Creates request options for getRolePermissions without sending the request
     * @param {string} id Unique UUID of the role
     * @param {string} [xOmnismithProjectId] The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential\&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time.
     * @throws {RequiredError}
     * @memberof RolesApiInterface
     */
    getRolePermissionsRequestOpts(requestParameters: GetRolePermissionsRequest): Promise<runtime.RequestOpts>;

    /**
     * Returns the array of permission keys (e.g. \"template.view\", \"entity.create\", \"attribute.manage\") explicitly granted to the specified role.
     * @summary Get role permissions
     * @param {string} id Unique UUID of the role
     * @param {string} [xOmnismithProjectId] The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential\&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RolesApiInterface
     */
    getRolePermissionsRaw(requestParameters: GetRolePermissionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetRolePermissions200Response>>;

    /**
     * Returns the array of permission keys (e.g. \"template.view\", \"entity.create\", \"attribute.manage\") explicitly granted to the specified role.
     * Get role permissions
     */
    getRolePermissions(requestParameters: GetRolePermissionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetRolePermissions200Response>;

    /**
     * Creates request options for getRoleResources without sending the request
     * @param {string} id Unique UUID of the role
     * @param {string} [xOmnismithProjectId] The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential\&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time.
     * @throws {RequiredError}
     * @memberof RolesApiInterface
     */
    getRoleResourcesRequestOpts(requestParameters: GetRoleResourcesRequest): Promise<runtime.RequestOpts>;

    /**
     * Retrieves granular resource-level access restrictions configured for the role, specifying access levels (deny, view, edit, full) for particular templates or attributes.
     * @summary Get role resource restrictions
     * @param {string} id Unique UUID of the role
     * @param {string} [xOmnismithProjectId] The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential\&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RolesApiInterface
     */
    getRoleResourcesRaw(requestParameters: GetRoleResourcesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetRoleResources200Response>>;

    /**
     * Retrieves granular resource-level access restrictions configured for the role, specifying access levels (deny, view, edit, full) for particular templates or attributes.
     * Get role resource restrictions
     */
    getRoleResources(requestParameters: GetRoleResourcesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetRoleResources200Response>;

    /**
     * Creates request options for getRoleScopes without sending the request
     * @param {string} id Unique UUID of the role
     * @param {string} [xOmnismithProjectId] The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential\&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time.
     * @throws {RequiredError}
     * @memberof RolesApiInterface
     */
    getRoleScopesRequestOpts(requestParameters: GetRoleScopesRequest): Promise<runtime.RequestOpts>;

    /**
     * Retrieves row-level entity access scopes for the role, which restrict what entity records matching specific attribute conditions the role can access within given templates.
     * @summary Get role entity-access scopes
     * @param {string} id Unique UUID of the role
     * @param {string} [xOmnismithProjectId] The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential\&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RolesApiInterface
     */
    getRoleScopesRaw(requestParameters: GetRoleScopesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetRoleScopes200Response>>;

    /**
     * Retrieves row-level entity access scopes for the role, which restrict what entity records matching specific attribute conditions the role can access within given templates.
     * Get role entity-access scopes
     */
    getRoleScopes(requestParameters: GetRoleScopesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetRoleScopes200Response>;

    /**
     * Creates request options for listAvailablePermissions without sending the request
     * @param {string} [xOmnismithProjectId] The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential\&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time.
     * @throws {RequiredError}
     * @memberof RolesApiInterface
     */
    listAvailablePermissionsRequestOpts(requestParameters: ListAvailablePermissionsRequest): Promise<runtime.RequestOpts>;

    /**
     * Returns all user-assignable permissions grouped by module. Excludes internal-only permissions.
     * @summary List available permissions for role assignment
     * @param {string} [xOmnismithProjectId] The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential\&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RolesApiInterface
     */
    listAvailablePermissionsRaw(requestParameters: ListAvailablePermissionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListAvailablePermissions200Response>>;

    /**
     * Returns all user-assignable permissions grouped by module. Excludes internal-only permissions.
     * List available permissions for role assignment
     */
    listAvailablePermissions(requestParameters: ListAvailablePermissionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListAvailablePermissions200Response>;

    /**
     * Creates request options for listRoles without sending the request
     * @param {string} [xOmnismithProjectId] The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential\&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time.
     * @throws {RequiredError}
     * @memberof RolesApiInterface
     */
    listRolesRequestOpts(requestParameters: ListRolesRequest): Promise<runtime.RequestOpts>;

    /**
     * Lists all custom and predefined roles defined within the current project, including the project owner role.
     * @summary List roles
     * @param {string} [xOmnismithProjectId] The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential\&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RolesApiInterface
     */
    listRolesRaw(requestParameters: ListRolesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListRoles200Response>>;

    /**
     * Lists all custom and predefined roles defined within the current project, including the project owner role.
     * List roles
     */
    listRoles(requestParameters: ListRolesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListRoles200Response>;

    /**
     * Creates request options for setRolePermissions without sending the request
     * @param {string} id Unique UUID of the role
     * @param {SetRolePermissionsRequest} setRolePermissionsRequest 
     * @param {string} [xOmnismithProjectId] The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential\&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time.
     * @throws {RequiredError}
     * @memberof RolesApiInterface
     */
    setRolePermissionsRequestOpts(requestParameters: SetRolePermissionsOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * Replaces the entire set of permission keys assigned to the role with the provided list. Use GET /roles/permissions/available to inspect valid keys.
     * @summary Set role permissions
     * @param {string} id Unique UUID of the role
     * @param {SetRolePermissionsRequest} setRolePermissionsRequest 
     * @param {string} [xOmnismithProjectId] The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential\&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RolesApiInterface
     */
    setRolePermissionsRaw(requestParameters: SetRolePermissionsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Replaces the entire set of permission keys assigned to the role with the provided list. Use GET /roles/permissions/available to inspect valid keys.
     * Set role permissions
     */
    setRolePermissions(requestParameters: SetRolePermissionsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for setRoleResources without sending the request
     * @param {string} id Unique UUID of the role
     * @param {SetRoleResourcesRequest} setRoleResourcesRequest 
     * @param {string} [xOmnismithProjectId] The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential\&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time.
     * @throws {RequiredError}
     * @memberof RolesApiInterface
     */
    setRoleResourcesRequestOpts(requestParameters: SetRoleResourcesOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * Replaces all resource-level access restrictions for the role. Each item defines a resource type (\"template\" or \"attribute\"), target resource UUID, and granted access level (\"deny\", \"view\", \"edit\", \"full\").
     * @summary Set role resource restrictions
     * @param {string} id Unique UUID of the role
     * @param {SetRoleResourcesRequest} setRoleResourcesRequest 
     * @param {string} [xOmnismithProjectId] The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential\&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RolesApiInterface
     */
    setRoleResourcesRaw(requestParameters: SetRoleResourcesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Replaces all resource-level access restrictions for the role. Each item defines a resource type (\"template\" or \"attribute\"), target resource UUID, and granted access level (\"deny\", \"view\", \"edit\", \"full\").
     * Set role resource restrictions
     */
    setRoleResources(requestParameters: SetRoleResourcesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for setRoleScopes without sending the request
     * @param {string} id Unique UUID of the role
     * @param {SetRoleScopesRequest} setRoleScopesRequest 
     * @param {string} [xOmnismithProjectId] The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential\&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time.
     * @throws {RequiredError}
     * @memberof RolesApiInterface
     */
    setRoleScopesRequestOpts(requestParameters: SetRoleScopesOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * Replaces row-level entity access scopes for the role. Conditions filter entity visibility based on field/attribute comparisons (operators: eq, neq, gt, lt, like, not-like, empty, not-empty).
     * @summary Set role entity-access scopes
     * @param {string} id Unique UUID of the role
     * @param {SetRoleScopesRequest} setRoleScopesRequest 
     * @param {string} [xOmnismithProjectId] The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential\&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RolesApiInterface
     */
    setRoleScopesRaw(requestParameters: SetRoleScopesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Replaces row-level entity access scopes for the role. Conditions filter entity visibility based on field/attribute comparisons (operators: eq, neq, gt, lt, like, not-like, empty, not-empty).
     * Set role entity-access scopes
     */
    setRoleScopes(requestParameters: SetRoleScopesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for updateRole without sending the request
     * @param {string} id Unique UUID of the role
     * @param {UpdateRoleRequest} updateRoleRequest 
     * @param {string} [xOmnismithProjectId] The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential\&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time.
     * @throws {RequiredError}
     * @memberof RolesApiInterface
     */
    updateRoleRequestOpts(requestParameters: UpdateRoleOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * Updates the display name of an existing custom role. System owner roles cannot be modified.
     * @summary Update a role
     * @param {string} id Unique UUID of the role
     * @param {UpdateRoleRequest} updateRoleRequest 
     * @param {string} [xOmnismithProjectId] The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential\&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RolesApiInterface
     */
    updateRoleRaw(requestParameters: UpdateRoleOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Updates the display name of an existing custom role. System owner roles cannot be modified.
     * Update a role
     */
    updateRole(requestParameters: UpdateRoleOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class RolesApi extends runtime.BaseAPI implements RolesApiInterface {

    /**
     * Creates request options for createRole without sending the request
     */
    async createRoleRequestOpts(requestParameters: CreateRoleOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createRoleRequest'] == null) {
            throw new runtime.RequiredError(
                'createRoleRequest',
                'Required parameter "createRoleRequest" was null or undefined when calling createRole().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xOmnismithProjectId'] != null) {
            headerParameters['X-Omnismith-Project-Id'] = String(requestParameters['xOmnismithProjectId']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/roles`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateRoleRequestToJSON(requestParameters['createRoleRequest']),
        };
    }

    /**
     * Creates a new custom role within the project. Role permissions, resource restrictions, and entity scopes can be configured subsequently.
     * Create a new role
     */
    async createRoleRaw(requestParameters: CreateRoleOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateProject201Response>> {
        const requestOptions = await this.createRoleRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateProject201ResponseFromJSON(jsonValue));
    }

    /**
     * Creates a new custom role within the project. Role permissions, resource restrictions, and entity scopes can be configured subsequently.
     * Create a new role
     */
    async createRole(requestParameters: CreateRoleOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateProject201Response> {
        const response = await this.createRoleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteRole without sending the request
     */
    async deleteRoleRequestOpts(requestParameters: DeleteRoleRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteRole().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xOmnismithProjectId'] != null) {
            headerParameters['X-Omnismith-Project-Id'] = String(requestParameters['xOmnismithProjectId']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/roles/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Permanently deletes a custom role. System owner roles cannot be deleted. Any users assigned to this role must be reassigned.
     * Delete a role
     */
    async deleteRoleRaw(requestParameters: DeleteRoleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteRoleRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Permanently deletes a custom role. System owner roles cannot be deleted. Any users assigned to this role must be reassigned.
     * Delete a role
     */
    async deleteRole(requestParameters: DeleteRoleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteRoleRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getRole without sending the request
     */
    async getRoleRequestOpts(requestParameters: GetRoleRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getRole().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xOmnismithProjectId'] != null) {
            headerParameters['X-Omnismith-Project-Id'] = String(requestParameters['xOmnismithProjectId']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/roles/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieves role metadata (name, is_owner status, creation timestamp) by role UUID.
     * Get a role
     */
    async getRoleRaw(requestParameters: GetRoleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RoleResponse>> {
        const requestOptions = await this.getRoleRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RoleResponseFromJSON(jsonValue));
    }

    /**
     * Retrieves role metadata (name, is_owner status, creation timestamp) by role UUID.
     * Get a role
     */
    async getRole(requestParameters: GetRoleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RoleResponse> {
        const response = await this.getRoleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getRolePermissions without sending the request
     */
    async getRolePermissionsRequestOpts(requestParameters: GetRolePermissionsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getRolePermissions().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xOmnismithProjectId'] != null) {
            headerParameters['X-Omnismith-Project-Id'] = String(requestParameters['xOmnismithProjectId']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/roles/{id}/permissions`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the array of permission keys (e.g. \"template.view\", \"entity.create\", \"attribute.manage\") explicitly granted to the specified role.
     * Get role permissions
     */
    async getRolePermissionsRaw(requestParameters: GetRolePermissionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetRolePermissions200Response>> {
        const requestOptions = await this.getRolePermissionsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetRolePermissions200ResponseFromJSON(jsonValue));
    }

    /**
     * Returns the array of permission keys (e.g. \"template.view\", \"entity.create\", \"attribute.manage\") explicitly granted to the specified role.
     * Get role permissions
     */
    async getRolePermissions(requestParameters: GetRolePermissionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetRolePermissions200Response> {
        const response = await this.getRolePermissionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getRoleResources without sending the request
     */
    async getRoleResourcesRequestOpts(requestParameters: GetRoleResourcesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getRoleResources().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xOmnismithProjectId'] != null) {
            headerParameters['X-Omnismith-Project-Id'] = String(requestParameters['xOmnismithProjectId']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/roles/{id}/resources`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieves granular resource-level access restrictions configured for the role, specifying access levels (deny, view, edit, full) for particular templates or attributes.
     * Get role resource restrictions
     */
    async getRoleResourcesRaw(requestParameters: GetRoleResourcesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetRoleResources200Response>> {
        const requestOptions = await this.getRoleResourcesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetRoleResources200ResponseFromJSON(jsonValue));
    }

    /**
     * Retrieves granular resource-level access restrictions configured for the role, specifying access levels (deny, view, edit, full) for particular templates or attributes.
     * Get role resource restrictions
     */
    async getRoleResources(requestParameters: GetRoleResourcesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetRoleResources200Response> {
        const response = await this.getRoleResourcesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getRoleScopes without sending the request
     */
    async getRoleScopesRequestOpts(requestParameters: GetRoleScopesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getRoleScopes().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xOmnismithProjectId'] != null) {
            headerParameters['X-Omnismith-Project-Id'] = String(requestParameters['xOmnismithProjectId']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/roles/{id}/scopes`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieves row-level entity access scopes for the role, which restrict what entity records matching specific attribute conditions the role can access within given templates.
     * Get role entity-access scopes
     */
    async getRoleScopesRaw(requestParameters: GetRoleScopesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetRoleScopes200Response>> {
        const requestOptions = await this.getRoleScopesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetRoleScopes200ResponseFromJSON(jsonValue));
    }

    /**
     * Retrieves row-level entity access scopes for the role, which restrict what entity records matching specific attribute conditions the role can access within given templates.
     * Get role entity-access scopes
     */
    async getRoleScopes(requestParameters: GetRoleScopesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetRoleScopes200Response> {
        const response = await this.getRoleScopesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listAvailablePermissions without sending the request
     */
    async listAvailablePermissionsRequestOpts(requestParameters: ListAvailablePermissionsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xOmnismithProjectId'] != null) {
            headerParameters['X-Omnismith-Project-Id'] = String(requestParameters['xOmnismithProjectId']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/roles/permissions/available`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns all user-assignable permissions grouped by module. Excludes internal-only permissions.
     * List available permissions for role assignment
     */
    async listAvailablePermissionsRaw(requestParameters: ListAvailablePermissionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListAvailablePermissions200Response>> {
        const requestOptions = await this.listAvailablePermissionsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListAvailablePermissions200ResponseFromJSON(jsonValue));
    }

    /**
     * Returns all user-assignable permissions grouped by module. Excludes internal-only permissions.
     * List available permissions for role assignment
     */
    async listAvailablePermissions(requestParameters: ListAvailablePermissionsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListAvailablePermissions200Response> {
        const response = await this.listAvailablePermissionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listRoles without sending the request
     */
    async listRolesRequestOpts(requestParameters: ListRolesRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xOmnismithProjectId'] != null) {
            headerParameters['X-Omnismith-Project-Id'] = String(requestParameters['xOmnismithProjectId']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/roles`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Lists all custom and predefined roles defined within the current project, including the project owner role.
     * List roles
     */
    async listRolesRaw(requestParameters: ListRolesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListRoles200Response>> {
        const requestOptions = await this.listRolesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListRoles200ResponseFromJSON(jsonValue));
    }

    /**
     * Lists all custom and predefined roles defined within the current project, including the project owner role.
     * List roles
     */
    async listRoles(requestParameters: ListRolesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListRoles200Response> {
        const response = await this.listRolesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for setRolePermissions without sending the request
     */
    async setRolePermissionsRequestOpts(requestParameters: SetRolePermissionsOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling setRolePermissions().'
            );
        }

        if (requestParameters['setRolePermissionsRequest'] == null) {
            throw new runtime.RequiredError(
                'setRolePermissionsRequest',
                'Required parameter "setRolePermissionsRequest" was null or undefined when calling setRolePermissions().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xOmnismithProjectId'] != null) {
            headerParameters['X-Omnismith-Project-Id'] = String(requestParameters['xOmnismithProjectId']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/roles/{id}/permissions`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: SetRolePermissionsRequestToJSON(requestParameters['setRolePermissionsRequest']),
        };
    }

    /**
     * Replaces the entire set of permission keys assigned to the role with the provided list. Use GET /roles/permissions/available to inspect valid keys.
     * Set role permissions
     */
    async setRolePermissionsRaw(requestParameters: SetRolePermissionsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.setRolePermissionsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Replaces the entire set of permission keys assigned to the role with the provided list. Use GET /roles/permissions/available to inspect valid keys.
     * Set role permissions
     */
    async setRolePermissions(requestParameters: SetRolePermissionsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.setRolePermissionsRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for setRoleResources without sending the request
     */
    async setRoleResourcesRequestOpts(requestParameters: SetRoleResourcesOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling setRoleResources().'
            );
        }

        if (requestParameters['setRoleResourcesRequest'] == null) {
            throw new runtime.RequiredError(
                'setRoleResourcesRequest',
                'Required parameter "setRoleResourcesRequest" was null or undefined when calling setRoleResources().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xOmnismithProjectId'] != null) {
            headerParameters['X-Omnismith-Project-Id'] = String(requestParameters['xOmnismithProjectId']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/roles/{id}/resources`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: SetRoleResourcesRequestToJSON(requestParameters['setRoleResourcesRequest']),
        };
    }

    /**
     * Replaces all resource-level access restrictions for the role. Each item defines a resource type (\"template\" or \"attribute\"), target resource UUID, and granted access level (\"deny\", \"view\", \"edit\", \"full\").
     * Set role resource restrictions
     */
    async setRoleResourcesRaw(requestParameters: SetRoleResourcesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.setRoleResourcesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Replaces all resource-level access restrictions for the role. Each item defines a resource type (\"template\" or \"attribute\"), target resource UUID, and granted access level (\"deny\", \"view\", \"edit\", \"full\").
     * Set role resource restrictions
     */
    async setRoleResources(requestParameters: SetRoleResourcesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.setRoleResourcesRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for setRoleScopes without sending the request
     */
    async setRoleScopesRequestOpts(requestParameters: SetRoleScopesOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling setRoleScopes().'
            );
        }

        if (requestParameters['setRoleScopesRequest'] == null) {
            throw new runtime.RequiredError(
                'setRoleScopesRequest',
                'Required parameter "setRoleScopesRequest" was null or undefined when calling setRoleScopes().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xOmnismithProjectId'] != null) {
            headerParameters['X-Omnismith-Project-Id'] = String(requestParameters['xOmnismithProjectId']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/roles/{id}/scopes`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: SetRoleScopesRequestToJSON(requestParameters['setRoleScopesRequest']),
        };
    }

    /**
     * Replaces row-level entity access scopes for the role. Conditions filter entity visibility based on field/attribute comparisons (operators: eq, neq, gt, lt, like, not-like, empty, not-empty).
     * Set role entity-access scopes
     */
    async setRoleScopesRaw(requestParameters: SetRoleScopesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.setRoleScopesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Replaces row-level entity access scopes for the role. Conditions filter entity visibility based on field/attribute comparisons (operators: eq, neq, gt, lt, like, not-like, empty, not-empty).
     * Set role entity-access scopes
     */
    async setRoleScopes(requestParameters: SetRoleScopesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.setRoleScopesRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for updateRole without sending the request
     */
    async updateRoleRequestOpts(requestParameters: UpdateRoleOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateRole().'
            );
        }

        if (requestParameters['updateRoleRequest'] == null) {
            throw new runtime.RequiredError(
                'updateRoleRequest',
                'Required parameter "updateRoleRequest" was null or undefined when calling updateRole().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xOmnismithProjectId'] != null) {
            headerParameters['X-Omnismith-Project-Id'] = String(requestParameters['xOmnismithProjectId']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/roles/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateRoleRequestToJSON(requestParameters['updateRoleRequest']),
        };
    }

    /**
     * Updates the display name of an existing custom role. System owner roles cannot be modified.
     * Update a role
     */
    async updateRoleRaw(requestParameters: UpdateRoleOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.updateRoleRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Updates the display name of an existing custom role. System owner roles cannot be modified.
     * Update a role
     */
    async updateRole(requestParameters: UpdateRoleOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.updateRoleRaw(requestParameters, initOverrides);
    }

}
