/* tslint:disable */
/* eslint-disable */
/**
 * Omnismith API
 * API Documentation for Omnismith
 *
 * The version of the OpenAPI document: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ConfirmUserEmail200Response,
  CreateAttributeItem201Response,
  RegisterUserRequest,
  ResendConfirmationEmail200Response,
  ResendConfirmationEmailRequest,
  ValidationErrorResponse,
} from '../models/index';
import {
    ConfirmUserEmail200ResponseFromJSON,
    ConfirmUserEmail200ResponseToJSON,
    CreateAttributeItem201ResponseFromJSON,
    CreateAttributeItem201ResponseToJSON,
    RegisterUserRequestFromJSON,
    RegisterUserRequestToJSON,
    ResendConfirmationEmail200ResponseFromJSON,
    ResendConfirmationEmail200ResponseToJSON,
    ResendConfirmationEmailRequestFromJSON,
    ResendConfirmationEmailRequestToJSON,
    ValidationErrorResponseFromJSON,
    ValidationErrorResponseToJSON,
} from '../models/index';

export interface ConfirmUserEmailRequest {
    token: string;
}

export interface RegisterUserOperationRequest {
    registerUserRequest: RegisterUserRequest;
}

export interface ResendConfirmationEmailOperationRequest {
    resendConfirmationEmailRequest: ResendConfirmationEmailRequest;
}

/**
 * UserApi - interface
 * 
 * @export
 * @interface UserApiInterface
 */
export interface UserApiInterface {
    /**
     * Creates request options for confirmUserEmail without sending the request
     * @param {string} token The email confirmation token
     * @throws {RequiredError}
     * @memberof UserApiInterface
     */
    confirmUserEmailRequestOpts(requestParameters: ConfirmUserEmailRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Confirm a user\'s email address using a confirmation token
     * @param {string} token The email confirmation token
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApiInterface
     */
    confirmUserEmailRaw(requestParameters: ConfirmUserEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConfirmUserEmail200Response>>;

    /**
     * Confirm a user\'s email address using a confirmation token
     */
    confirmUserEmail(requestParameters: ConfirmUserEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConfirmUserEmail200Response>;

    /**
     * Creates request options for registerUser without sending the request
     * @param {RegisterUserRequest} registerUserRequest 
     * @throws {RequiredError}
     * @memberof UserApiInterface
     */
    registerUserRequestOpts(requestParameters: RegisterUserOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Register a new user
     * @param {RegisterUserRequest} registerUserRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApiInterface
     */
    registerUserRaw(requestParameters: RegisterUserOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateAttributeItem201Response>>;

    /**
     * Register a new user
     */
    registerUser(requestParameters: RegisterUserOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateAttributeItem201Response>;

    /**
     * Creates request options for resendConfirmationEmail without sending the request
     * @param {ResendConfirmationEmailRequest} resendConfirmationEmailRequest 
     * @throws {RequiredError}
     * @memberof UserApiInterface
     */
    resendConfirmationEmailRequestOpts(requestParameters: ResendConfirmationEmailOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Resend the email confirmation link
     * @param {ResendConfirmationEmailRequest} resendConfirmationEmailRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApiInterface
     */
    resendConfirmationEmailRaw(requestParameters: ResendConfirmationEmailOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResendConfirmationEmail200Response>>;

    /**
     * Resend the email confirmation link
     */
    resendConfirmationEmail(requestParameters: ResendConfirmationEmailOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResendConfirmationEmail200Response>;

}

/**
 * 
 */
export class UserApi extends runtime.BaseAPI implements UserApiInterface {

    /**
     * Creates request options for confirmUserEmail without sending the request
     */
    async confirmUserEmailRequestOpts(requestParameters: ConfirmUserEmailRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['token'] == null) {
            throw new runtime.RequiredError(
                'token',
                'Required parameter "token" was null or undefined when calling confirmUserEmail().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['token'] != null) {
            queryParameters['token'] = requestParameters['token'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/users/confirm-email`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Confirm a user\'s email address using a confirmation token
     */
    async confirmUserEmailRaw(requestParameters: ConfirmUserEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConfirmUserEmail200Response>> {
        const requestOptions = await this.confirmUserEmailRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConfirmUserEmail200ResponseFromJSON(jsonValue));
    }

    /**
     * Confirm a user\'s email address using a confirmation token
     */
    async confirmUserEmail(requestParameters: ConfirmUserEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConfirmUserEmail200Response> {
        const response = await this.confirmUserEmailRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for registerUser without sending the request
     */
    async registerUserRequestOpts(requestParameters: RegisterUserOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['registerUserRequest'] == null) {
            throw new runtime.RequiredError(
                'registerUserRequest',
                'Required parameter "registerUserRequest" was null or undefined when calling registerUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/users/register`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RegisterUserRequestToJSON(requestParameters['registerUserRequest']),
        };
    }

    /**
     * Register a new user
     */
    async registerUserRaw(requestParameters: RegisterUserOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateAttributeItem201Response>> {
        const requestOptions = await this.registerUserRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateAttributeItem201ResponseFromJSON(jsonValue));
    }

    /**
     * Register a new user
     */
    async registerUser(requestParameters: RegisterUserOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateAttributeItem201Response> {
        const response = await this.registerUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for resendConfirmationEmail without sending the request
     */
    async resendConfirmationEmailRequestOpts(requestParameters: ResendConfirmationEmailOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['resendConfirmationEmailRequest'] == null) {
            throw new runtime.RequiredError(
                'resendConfirmationEmailRequest',
                'Required parameter "resendConfirmationEmailRequest" was null or undefined when calling resendConfirmationEmail().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/users/resend-confirmation`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ResendConfirmationEmailRequestToJSON(requestParameters['resendConfirmationEmailRequest']),
        };
    }

    /**
     * Resend the email confirmation link
     */
    async resendConfirmationEmailRaw(requestParameters: ResendConfirmationEmailOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResendConfirmationEmail200Response>> {
        const requestOptions = await this.resendConfirmationEmailRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResendConfirmationEmail200ResponseFromJSON(jsonValue));
    }

    /**
     * Resend the email confirmation link
     */
    async resendConfirmationEmail(requestParameters: ResendConfirmationEmailOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResendConfirmationEmail200Response> {
        const response = await this.resendConfirmationEmailRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
