/* tslint:disable */
/* eslint-disable */
/**
 * Omnismith API
 * API Documentation for Omnismith
 *
 * The version of the OpenAPI document: 1.0.14
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateDashboard201Response,
  CreateDashboardBlock201Response,
  CreateWorkspaceRequest,
  CreateWorkspaceViewRequest,
  DuplicateWorkspace201Response,
  DuplicateWorkspaceRequest,
  ErrorResponse,
  ListTemplateViews200Response,
  ListWorkspaces200Response,
  ReorderWorkspaceViewsRequest,
  UpdateWorkspaceRequest,
  UpdateWorkspaceViewRequest,
  ValidationErrorResponse,
  WorkspaceDetailsResponse,
  WorkspaceViewResponse,
} from '../models/index';
import {
    CreateDashboard201ResponseFromJSON,
    CreateDashboard201ResponseToJSON,
    CreateDashboardBlock201ResponseFromJSON,
    CreateDashboardBlock201ResponseToJSON,
    CreateWorkspaceRequestFromJSON,
    CreateWorkspaceRequestToJSON,
    CreateWorkspaceViewRequestFromJSON,
    CreateWorkspaceViewRequestToJSON,
    DuplicateWorkspace201ResponseFromJSON,
    DuplicateWorkspace201ResponseToJSON,
    DuplicateWorkspaceRequestFromJSON,
    DuplicateWorkspaceRequestToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    ListTemplateViews200ResponseFromJSON,
    ListTemplateViews200ResponseToJSON,
    ListWorkspaces200ResponseFromJSON,
    ListWorkspaces200ResponseToJSON,
    ReorderWorkspaceViewsRequestFromJSON,
    ReorderWorkspaceViewsRequestToJSON,
    UpdateWorkspaceRequestFromJSON,
    UpdateWorkspaceRequestToJSON,
    UpdateWorkspaceViewRequestFromJSON,
    UpdateWorkspaceViewRequestToJSON,
    ValidationErrorResponseFromJSON,
    ValidationErrorResponseToJSON,
    WorkspaceDetailsResponseFromJSON,
    WorkspaceDetailsResponseToJSON,
    WorkspaceViewResponseFromJSON,
    WorkspaceViewResponseToJSON,
} from '../models/index';

export interface CreateWorkspaceOperationRequest {
    createWorkspaceRequest: CreateWorkspaceRequest;
    xOmnismithProjectId?: string;
}

export interface CreateWorkspaceViewOperationRequest {
    id: string;
    createWorkspaceViewRequest: CreateWorkspaceViewRequest;
    xOmnismithProjectId?: string;
}

export interface DeleteWorkspaceRequest {
    id: string;
    xOmnismithProjectId?: string;
}

export interface DeleteWorkspaceViewRequest {
    id: string;
    viewId: string;
    xOmnismithProjectId?: string;
}

export interface DuplicateWorkspaceOperationRequest {
    id: string;
    xOmnismithProjectId?: string;
    duplicateWorkspaceRequest?: DuplicateWorkspaceRequest;
}

export interface GetWorkspaceRequest {
    id: string;
    xOmnismithProjectId?: string;
}

export interface GetWorkspaceViewRequest {
    id: string;
    viewId: string;
    xOmnismithProjectId?: string;
}

export interface ListTemplateViewsRequest {
    templateId: string;
    xOmnismithProjectId?: string;
}

export interface ListWorkspacesRequest {
    xOmnismithProjectId?: string;
}

export interface ReorderWorkspaceViewsOperationRequest {
    id: string;
    reorderWorkspaceViewsRequest: ReorderWorkspaceViewsRequest;
    xOmnismithProjectId?: string;
}

export interface SetDefaultWorkspaceRequest {
    id: string;
    xOmnismithProjectId?: string;
}

export interface UpdateWorkspaceOperationRequest {
    id: string;
    updateWorkspaceRequest: UpdateWorkspaceRequest;
    xOmnismithProjectId?: string;
}

export interface UpdateWorkspaceViewOperationRequest {
    id: string;
    viewId: string;
    updateWorkspaceViewRequest: UpdateWorkspaceViewRequest;
    xOmnismithProjectId?: string;
}

/**
 * WorkspacesApi - interface
 * 
 * @export
 * @interface WorkspacesApiInterface
 */
export interface WorkspacesApiInterface {
    /**
     * Creates request options for createWorkspace without sending the request
     * @param {CreateWorkspaceRequest} createWorkspaceRequest Workspace creation payload
     * @param {string} [xOmnismithProjectId] The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential\&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time.
     * @throws {RequiredError}
     * @memberof WorkspacesApiInterface
     */
    createWorkspaceRequestOpts(requestParameters: CreateWorkspaceOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * Creates a top-level operational workspace (workbench) in the current project context grouping related views for a specific workflow (e.g. \"Editorial & Content Calendar\", \"Guidelines & Strategy\", \"Media Studio\"). Workspaces appear in the top-level workspace switcher and support multi-pane layouts (single, split-v, split-h, quad) and default workspace indicators.
     * @summary Create a new workspace
     * @param {CreateWorkspaceRequest} createWorkspaceRequest Workspace creation payload
     * @param {string} [xOmnismithProjectId] The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential\&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WorkspacesApiInterface
     */
    createWorkspaceRaw(requestParameters: CreateWorkspaceOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateDashboard201Response>>;

    /**
     * Creates a top-level operational workspace (workbench) in the current project context grouping related views for a specific workflow (e.g. \"Editorial & Content Calendar\", \"Guidelines & Strategy\", \"Media Studio\"). Workspaces appear in the top-level workspace switcher and support multi-pane layouts (single, split-v, split-h, quad) and default workspace indicators.
     * Create a new workspace
     */
    createWorkspace(requestParameters: CreateWorkspaceOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateDashboard201Response>;

    /**
     * Creates request options for createWorkspaceView without sending the request
     * @param {string} id Target workspace unique identifier (UUID)
     * @param {CreateWorkspaceViewRequest} createWorkspaceViewRequest Workspace view creation payload
     * @param {string} [xOmnismithProjectId] The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential\&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time.
     * @throws {RequiredError}
     * @memberof WorkspacesApiInterface
     */
    createWorkspaceViewRequestOpts(requestParameters: CreateWorkspaceViewOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * Creates and mounts a new view pane within an existing workspace bound to a specific entity schema template, configuring presentation mode (table, grid), visible columns, filter criteria, search queries (keyword or semantic), sorting preferences, and pane order. A workspace view represents a specialized filtered lens (e.g. \"Telegram Channel Hub\" filtered for platform=telegram) inside an operational workspace.
     * @summary Add a new view / pane to a workspace
     * @param {string} id Target workspace unique identifier (UUID)
     * @param {CreateWorkspaceViewRequest} createWorkspaceViewRequest Workspace view creation payload
     * @param {string} [xOmnismithProjectId] The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential\&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WorkspacesApiInterface
     */
    createWorkspaceViewRaw(requestParameters: CreateWorkspaceViewOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateDashboardBlock201Response>>;

    /**
     * Creates and mounts a new view pane within an existing workspace bound to a specific entity schema template, configuring presentation mode (table, grid), visible columns, filter criteria, search queries (keyword or semantic), sorting preferences, and pane order. A workspace view represents a specialized filtered lens (e.g. \"Telegram Channel Hub\" filtered for platform=telegram) inside an operational workspace.
     * Add a new view / pane to a workspace
     */
    createWorkspaceView(requestParameters: CreateWorkspaceViewOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateDashboardBlock201Response>;

    /**
     * Creates request options for deleteWorkspace without sending the request
     * @param {string} id Workspace unique identifier (UUID) to delete
     * @param {string} [xOmnismithProjectId] The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential\&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time.
     * @throws {RequiredError}
     * @memberof WorkspacesApiInterface
     */
    deleteWorkspaceRequestOpts(requestParameters: DeleteWorkspaceRequest): Promise<runtime.RequestOpts>;

    /**
     * Permanently removes a workspace and all nested view pane configurations from the project.
     * @summary Delete a workspace and its views
     * @param {string} id Workspace unique identifier (UUID) to delete
     * @param {string} [xOmnismithProjectId] The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential\&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WorkspacesApiInterface
     */
    deleteWorkspaceRaw(requestParameters: DeleteWorkspaceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Permanently removes a workspace and all nested view pane configurations from the project.
     * Delete a workspace and its views
     */
    deleteWorkspace(requestParameters: DeleteWorkspaceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for deleteWorkspaceView without sending the request
     * @param {string} id Workspace unique identifier (UUID)
     * @param {string} viewId Workspace view unique identifier (UUID) to delete
     * @param {string} [xOmnismithProjectId] The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential\&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time.
     * @throws {RequiredError}
     * @memberof WorkspacesApiInterface
     */
    deleteWorkspaceViewRequestOpts(requestParameters: DeleteWorkspaceViewRequest): Promise<runtime.RequestOpts>;

    /**
     * Permanently removes a view pane from a workspace.
     * @summary Delete a view / pane from a workspace
     * @param {string} id Workspace unique identifier (UUID)
     * @param {string} viewId Workspace view unique identifier (UUID) to delete
     * @param {string} [xOmnismithProjectId] The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential\&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WorkspacesApiInterface
     */
    deleteWorkspaceViewRaw(requestParameters: DeleteWorkspaceViewRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Permanently removes a view pane from a workspace.
     * Delete a view / pane from a workspace
     */
    deleteWorkspaceView(requestParameters: DeleteWorkspaceViewRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for duplicateWorkspace without sending the request
     * @param {string} id Source workspace unique identifier (UUID) to clone
     * @param {string} [xOmnismithProjectId] The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential\&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time.
     * @param {DuplicateWorkspaceRequest} [duplicateWorkspaceRequest] Optional configuration for the duplicated workspace
     * @throws {RequiredError}
     * @memberof WorkspacesApiInterface
     */
    duplicateWorkspaceRequestOpts(requestParameters: DuplicateWorkspaceOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * Creates a deep copy of an existing workspace, cloning all nested view panes, filter rules, display configurations, and layout settings into a new workspace with an optional customized name.
     * @summary Duplicate an existing workspace and its views
     * @param {string} id Source workspace unique identifier (UUID) to clone
     * @param {string} [xOmnismithProjectId] The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential\&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time.
     * @param {DuplicateWorkspaceRequest} [duplicateWorkspaceRequest] Optional configuration for the duplicated workspace
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WorkspacesApiInterface
     */
    duplicateWorkspaceRaw(requestParameters: DuplicateWorkspaceOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DuplicateWorkspace201Response>>;

    /**
     * Creates a deep copy of an existing workspace, cloning all nested view panes, filter rules, display configurations, and layout settings into a new workspace with an optional customized name.
     * Duplicate an existing workspace and its views
     */
    duplicateWorkspace(requestParameters: DuplicateWorkspaceOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DuplicateWorkspace201Response>;

    /**
     * Creates request options for getWorkspace without sending the request
     * @param {string} id Workspace unique identifier (UUID)
     * @param {string} [xOmnismithProjectId] The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential\&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time.
     * @throws {RequiredError}
     * @memberof WorkspacesApiInterface
     */
    getWorkspaceRequestOpts(requestParameters: GetWorkspaceRequest): Promise<runtime.RequestOpts>;

    /**
     * Retrieves detailed information for a specific workspace, including its multi-pane layout configuration and all hydrated view panes with their associated template schemas, filter rules, search criteria, column selections, and ordering.
     * @summary Get workspace details and its views
     * @param {string} id Workspace unique identifier (UUID)
     * @param {string} [xOmnismithProjectId] The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential\&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WorkspacesApiInterface
     */
    getWorkspaceRaw(requestParameters: GetWorkspaceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WorkspaceDetailsResponse>>;

    /**
     * Retrieves detailed information for a specific workspace, including its multi-pane layout configuration and all hydrated view panes with their associated template schemas, filter rules, search criteria, column selections, and ordering.
     * Get workspace details and its views
     */
    getWorkspace(requestParameters: GetWorkspaceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WorkspaceDetailsResponse>;

    /**
     * Creates request options for getWorkspaceView without sending the request
     * @param {string} id Workspace unique identifier (UUID)
     * @param {string} viewId Workspace view unique identifier (UUID)
     * @param {string} [xOmnismithProjectId] The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential\&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time.
     * @throws {RequiredError}
     * @memberof WorkspacesApiInterface
     */
    getWorkspaceViewRequestOpts(requestParameters: GetWorkspaceViewRequest): Promise<runtime.RequestOpts>;

    /**
     * Retrieves complete configuration details for a single workspace view pane, including its schema template binding, active filter rules, search parameters, column visibility, sort order, and layout positioning.
     * @summary Get details of a workspace view / pane
     * @param {string} id Workspace unique identifier (UUID)
     * @param {string} viewId Workspace view unique identifier (UUID)
     * @param {string} [xOmnismithProjectId] The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential\&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WorkspacesApiInterface
     */
    getWorkspaceViewRaw(requestParameters: GetWorkspaceViewRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WorkspaceViewResponse>>;

    /**
     * Retrieves complete configuration details for a single workspace view pane, including its schema template binding, active filter rules, search parameters, column visibility, sort order, and layout positioning.
     * Get details of a workspace view / pane
     */
    getWorkspaceView(requestParameters: GetWorkspaceViewRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WorkspaceViewResponse>;

    /**
     * Creates request options for listTemplateViews without sending the request
     * @param {string} templateId Schema template unique identifier (UUID)
     * @param {string} [xOmnismithProjectId] The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential\&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time.
     * @throws {RequiredError}
     * @memberof WorkspacesApiInterface
     */
    listTemplateViewsRequestOpts(requestParameters: ListTemplateViewsRequest): Promise<runtime.RequestOpts>;

    /**
     * Searches and returns all saved workspace view panes configured across any workspace that are bound to a specific entity schema template, facilitating cross-workspace view reuse and discovery.
     * @summary List saved views for a specific template across workspaces
     * @param {string} templateId Schema template unique identifier (UUID)
     * @param {string} [xOmnismithProjectId] The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential\&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WorkspacesApiInterface
     */
    listTemplateViewsRaw(requestParameters: ListTemplateViewsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListTemplateViews200Response>>;

    /**
     * Searches and returns all saved workspace view panes configured across any workspace that are bound to a specific entity schema template, facilitating cross-workspace view reuse and discovery.
     * List saved views for a specific template across workspaces
     */
    listTemplateViews(requestParameters: ListTemplateViewsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListTemplateViews200Response>;

    /**
     * Creates request options for listWorkspaces without sending the request
     * @param {string} [xOmnismithProjectId] The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential\&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time.
     * @throws {RequiredError}
     * @memberof WorkspacesApiInterface
     */
    listWorkspacesRequestOpts(requestParameters: ListWorkspacesRequest): Promise<runtime.RequestOpts>;

    /**
     * Retrieves all top-level operational workspaces configured within the authenticated project context, including multi-pane layout structures (single, split-v, split-h, quad), view pane counts, sort ordering, and default workspace indicators for workbench navigation.
     * @summary List all workspaces for current project
     * @param {string} [xOmnismithProjectId] The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential\&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WorkspacesApiInterface
     */
    listWorkspacesRaw(requestParameters: ListWorkspacesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListWorkspaces200Response>>;

    /**
     * Retrieves all top-level operational workspaces configured within the authenticated project context, including multi-pane layout structures (single, split-v, split-h, quad), view pane counts, sort ordering, and default workspace indicators for workbench navigation.
     * List all workspaces for current project
     */
    listWorkspaces(requestParameters: ListWorkspacesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListWorkspaces200Response>;

    /**
     * Creates request options for reorderWorkspaceViews without sending the request
     * @param {string} id Workspace unique identifier (UUID)
     * @param {ReorderWorkspaceViewsRequest} reorderWorkspaceViewsRequest Payload containing ordered view IDs
     * @param {string} [xOmnismithProjectId] The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential\&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time.
     * @throws {RequiredError}
     * @memberof WorkspacesApiInterface
     */
    reorderWorkspaceViewsRequestOpts(requestParameters: ReorderWorkspaceViewsOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * Updates the visual sequence and tab ordering of view panes inside a workspace by supplying an ordered list of view IDs matching the desired layout arrangement.
     * @summary Reorder views inside a workspace
     * @param {string} id Workspace unique identifier (UUID)
     * @param {ReorderWorkspaceViewsRequest} reorderWorkspaceViewsRequest Payload containing ordered view IDs
     * @param {string} [xOmnismithProjectId] The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential\&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WorkspacesApiInterface
     */
    reorderWorkspaceViewsRaw(requestParameters: ReorderWorkspaceViewsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Updates the visual sequence and tab ordering of view panes inside a workspace by supplying an ordered list of view IDs matching the desired layout arrangement.
     * Reorder views inside a workspace
     */
    reorderWorkspaceViews(requestParameters: ReorderWorkspaceViewsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for setDefaultWorkspace without sending the request
     * @param {string} id Workspace unique identifier (UUID) to designate as default
     * @param {string} [xOmnismithProjectId] The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential\&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time.
     * @throws {RequiredError}
     * @memberof WorkspacesApiInterface
     */
    setDefaultWorkspaceRequestOpts(requestParameters: SetDefaultWorkspaceRequest): Promise<runtime.RequestOpts>;

    /**
     * Designates the specified workspace as the primary/default landing view for the project, automatically demoting any existing default workspace.
     * @summary Set workspace as the default workspace
     * @param {string} id Workspace unique identifier (UUID) to designate as default
     * @param {string} [xOmnismithProjectId] The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential\&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WorkspacesApiInterface
     */
    setDefaultWorkspaceRaw(requestParameters: SetDefaultWorkspaceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Designates the specified workspace as the primary/default landing view for the project, automatically demoting any existing default workspace.
     * Set workspace as the default workspace
     */
    setDefaultWorkspace(requestParameters: SetDefaultWorkspaceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for updateWorkspace without sending the request
     * @param {string} id Workspace unique identifier (UUID) to update
     * @param {UpdateWorkspaceRequest} updateWorkspaceRequest Workspace update payload
     * @param {string} [xOmnismithProjectId] The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential\&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time.
     * @throws {RequiredError}
     * @memberof WorkspacesApiInterface
     */
    updateWorkspaceRequestOpts(requestParameters: UpdateWorkspaceOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * Updates workspace attributes including display name, description, multi-pane layout arrangement (single, split-v, split-h, quad), sort order sequence, and default workspace status.
     * @summary Update workspace metadata and layout
     * @param {string} id Workspace unique identifier (UUID) to update
     * @param {UpdateWorkspaceRequest} updateWorkspaceRequest Workspace update payload
     * @param {string} [xOmnismithProjectId] The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential\&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WorkspacesApiInterface
     */
    updateWorkspaceRaw(requestParameters: UpdateWorkspaceOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Updates workspace attributes including display name, description, multi-pane layout arrangement (single, split-v, split-h, quad), sort order sequence, and default workspace status.
     * Update workspace metadata and layout
     */
    updateWorkspace(requestParameters: UpdateWorkspaceOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for updateWorkspaceView without sending the request
     * @param {string} id Workspace unique identifier (UUID)
     * @param {string} viewId Workspace view unique identifier (UUID) to update
     * @param {UpdateWorkspaceViewRequest} updateWorkspaceViewRequest Workspace view update payload
     * @param {string} [xOmnismithProjectId] The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential\&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time.
     * @throws {RequiredError}
     * @memberof WorkspacesApiInterface
     */
    updateWorkspaceViewRequestOpts(requestParameters: UpdateWorkspaceViewOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * Updates the configuration of a specific workspace view pane, modifying its title, filtering rules, search query and mode, sorting preferences, presentation display mode (table or grid), column visibility lists, or pane display sequence. A workspace view represents a specialized filtered lens (e.g. \"Telegram Channel Hub\") inside an operational workspace.
     * @summary Update workspace view / pane filters, sort, display mode, or columns
     * @param {string} id Workspace unique identifier (UUID)
     * @param {string} viewId Workspace view unique identifier (UUID) to update
     * @param {UpdateWorkspaceViewRequest} updateWorkspaceViewRequest Workspace view update payload
     * @param {string} [xOmnismithProjectId] The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential\&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WorkspacesApiInterface
     */
    updateWorkspaceViewRaw(requestParameters: UpdateWorkspaceViewOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Updates the configuration of a specific workspace view pane, modifying its title, filtering rules, search query and mode, sorting preferences, presentation display mode (table or grid), column visibility lists, or pane display sequence. A workspace view represents a specialized filtered lens (e.g. \"Telegram Channel Hub\") inside an operational workspace.
     * Update workspace view / pane filters, sort, display mode, or columns
     */
    updateWorkspaceView(requestParameters: UpdateWorkspaceViewOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class WorkspacesApi extends runtime.BaseAPI implements WorkspacesApiInterface {

    /**
     * Creates request options for createWorkspace without sending the request
     */
    async createWorkspaceRequestOpts(requestParameters: CreateWorkspaceOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createWorkspaceRequest'] == null) {
            throw new runtime.RequiredError(
                'createWorkspaceRequest',
                'Required parameter "createWorkspaceRequest" was null or undefined when calling createWorkspace().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xOmnismithProjectId'] != null) {
            headerParameters['X-Omnismith-Project-Id'] = String(requestParameters['xOmnismithProjectId']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/workspaces`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateWorkspaceRequestToJSON(requestParameters['createWorkspaceRequest']),
        };
    }

    /**
     * Creates a top-level operational workspace (workbench) in the current project context grouping related views for a specific workflow (e.g. \"Editorial & Content Calendar\", \"Guidelines & Strategy\", \"Media Studio\"). Workspaces appear in the top-level workspace switcher and support multi-pane layouts (single, split-v, split-h, quad) and default workspace indicators.
     * Create a new workspace
     */
    async createWorkspaceRaw(requestParameters: CreateWorkspaceOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateDashboard201Response>> {
        const requestOptions = await this.createWorkspaceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateDashboard201ResponseFromJSON(jsonValue));
    }

    /**
     * Creates a top-level operational workspace (workbench) in the current project context grouping related views for a specific workflow (e.g. \"Editorial & Content Calendar\", \"Guidelines & Strategy\", \"Media Studio\"). Workspaces appear in the top-level workspace switcher and support multi-pane layouts (single, split-v, split-h, quad) and default workspace indicators.
     * Create a new workspace
     */
    async createWorkspace(requestParameters: CreateWorkspaceOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateDashboard201Response> {
        const response = await this.createWorkspaceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createWorkspaceView without sending the request
     */
    async createWorkspaceViewRequestOpts(requestParameters: CreateWorkspaceViewOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling createWorkspaceView().'
            );
        }

        if (requestParameters['createWorkspaceViewRequest'] == null) {
            throw new runtime.RequiredError(
                'createWorkspaceViewRequest',
                'Required parameter "createWorkspaceViewRequest" was null or undefined when calling createWorkspaceView().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xOmnismithProjectId'] != null) {
            headerParameters['X-Omnismith-Project-Id'] = String(requestParameters['xOmnismithProjectId']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/workspaces/{id}/views`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateWorkspaceViewRequestToJSON(requestParameters['createWorkspaceViewRequest']),
        };
    }

    /**
     * Creates and mounts a new view pane within an existing workspace bound to a specific entity schema template, configuring presentation mode (table, grid), visible columns, filter criteria, search queries (keyword or semantic), sorting preferences, and pane order. A workspace view represents a specialized filtered lens (e.g. \"Telegram Channel Hub\" filtered for platform=telegram) inside an operational workspace.
     * Add a new view / pane to a workspace
     */
    async createWorkspaceViewRaw(requestParameters: CreateWorkspaceViewOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateDashboardBlock201Response>> {
        const requestOptions = await this.createWorkspaceViewRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateDashboardBlock201ResponseFromJSON(jsonValue));
    }

    /**
     * Creates and mounts a new view pane within an existing workspace bound to a specific entity schema template, configuring presentation mode (table, grid), visible columns, filter criteria, search queries (keyword or semantic), sorting preferences, and pane order. A workspace view represents a specialized filtered lens (e.g. \"Telegram Channel Hub\" filtered for platform=telegram) inside an operational workspace.
     * Add a new view / pane to a workspace
     */
    async createWorkspaceView(requestParameters: CreateWorkspaceViewOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateDashboardBlock201Response> {
        const response = await this.createWorkspaceViewRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteWorkspace without sending the request
     */
    async deleteWorkspaceRequestOpts(requestParameters: DeleteWorkspaceRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteWorkspace().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xOmnismithProjectId'] != null) {
            headerParameters['X-Omnismith-Project-Id'] = String(requestParameters['xOmnismithProjectId']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/workspaces/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Permanently removes a workspace and all nested view pane configurations from the project.
     * Delete a workspace and its views
     */
    async deleteWorkspaceRaw(requestParameters: DeleteWorkspaceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteWorkspaceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Permanently removes a workspace and all nested view pane configurations from the project.
     * Delete a workspace and its views
     */
    async deleteWorkspace(requestParameters: DeleteWorkspaceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteWorkspaceRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for deleteWorkspaceView without sending the request
     */
    async deleteWorkspaceViewRequestOpts(requestParameters: DeleteWorkspaceViewRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteWorkspaceView().'
            );
        }

        if (requestParameters['viewId'] == null) {
            throw new runtime.RequiredError(
                'viewId',
                'Required parameter "viewId" was null or undefined when calling deleteWorkspaceView().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xOmnismithProjectId'] != null) {
            headerParameters['X-Omnismith-Project-Id'] = String(requestParameters['xOmnismithProjectId']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/workspaces/{id}/views/{viewId}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"viewId"}}`, encodeURIComponent(String(requestParameters['viewId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Permanently removes a view pane from a workspace.
     * Delete a view / pane from a workspace
     */
    async deleteWorkspaceViewRaw(requestParameters: DeleteWorkspaceViewRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteWorkspaceViewRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Permanently removes a view pane from a workspace.
     * Delete a view / pane from a workspace
     */
    async deleteWorkspaceView(requestParameters: DeleteWorkspaceViewRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteWorkspaceViewRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for duplicateWorkspace without sending the request
     */
    async duplicateWorkspaceRequestOpts(requestParameters: DuplicateWorkspaceOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling duplicateWorkspace().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xOmnismithProjectId'] != null) {
            headerParameters['X-Omnismith-Project-Id'] = String(requestParameters['xOmnismithProjectId']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/workspaces/{id}/duplicate`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DuplicateWorkspaceRequestToJSON(requestParameters['duplicateWorkspaceRequest']),
        };
    }

    /**
     * Creates a deep copy of an existing workspace, cloning all nested view panes, filter rules, display configurations, and layout settings into a new workspace with an optional customized name.
     * Duplicate an existing workspace and its views
     */
    async duplicateWorkspaceRaw(requestParameters: DuplicateWorkspaceOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DuplicateWorkspace201Response>> {
        const requestOptions = await this.duplicateWorkspaceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DuplicateWorkspace201ResponseFromJSON(jsonValue));
    }

    /**
     * Creates a deep copy of an existing workspace, cloning all nested view panes, filter rules, display configurations, and layout settings into a new workspace with an optional customized name.
     * Duplicate an existing workspace and its views
     */
    async duplicateWorkspace(requestParameters: DuplicateWorkspaceOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DuplicateWorkspace201Response> {
        const response = await this.duplicateWorkspaceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getWorkspace without sending the request
     */
    async getWorkspaceRequestOpts(requestParameters: GetWorkspaceRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getWorkspace().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xOmnismithProjectId'] != null) {
            headerParameters['X-Omnismith-Project-Id'] = String(requestParameters['xOmnismithProjectId']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/workspaces/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieves detailed information for a specific workspace, including its multi-pane layout configuration and all hydrated view panes with their associated template schemas, filter rules, search criteria, column selections, and ordering.
     * Get workspace details and its views
     */
    async getWorkspaceRaw(requestParameters: GetWorkspaceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WorkspaceDetailsResponse>> {
        const requestOptions = await this.getWorkspaceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WorkspaceDetailsResponseFromJSON(jsonValue));
    }

    /**
     * Retrieves detailed information for a specific workspace, including its multi-pane layout configuration and all hydrated view panes with their associated template schemas, filter rules, search criteria, column selections, and ordering.
     * Get workspace details and its views
     */
    async getWorkspace(requestParameters: GetWorkspaceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WorkspaceDetailsResponse> {
        const response = await this.getWorkspaceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getWorkspaceView without sending the request
     */
    async getWorkspaceViewRequestOpts(requestParameters: GetWorkspaceViewRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getWorkspaceView().'
            );
        }

        if (requestParameters['viewId'] == null) {
            throw new runtime.RequiredError(
                'viewId',
                'Required parameter "viewId" was null or undefined when calling getWorkspaceView().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xOmnismithProjectId'] != null) {
            headerParameters['X-Omnismith-Project-Id'] = String(requestParameters['xOmnismithProjectId']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/workspaces/{id}/views/{viewId}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"viewId"}}`, encodeURIComponent(String(requestParameters['viewId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieves complete configuration details for a single workspace view pane, including its schema template binding, active filter rules, search parameters, column visibility, sort order, and layout positioning.
     * Get details of a workspace view / pane
     */
    async getWorkspaceViewRaw(requestParameters: GetWorkspaceViewRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WorkspaceViewResponse>> {
        const requestOptions = await this.getWorkspaceViewRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WorkspaceViewResponseFromJSON(jsonValue));
    }

    /**
     * Retrieves complete configuration details for a single workspace view pane, including its schema template binding, active filter rules, search parameters, column visibility, sort order, and layout positioning.
     * Get details of a workspace view / pane
     */
    async getWorkspaceView(requestParameters: GetWorkspaceViewRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WorkspaceViewResponse> {
        const response = await this.getWorkspaceViewRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listTemplateViews without sending the request
     */
    async listTemplateViewsRequestOpts(requestParameters: ListTemplateViewsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['templateId'] == null) {
            throw new runtime.RequiredError(
                'templateId',
                'Required parameter "templateId" was null or undefined when calling listTemplateViews().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xOmnismithProjectId'] != null) {
            headerParameters['X-Omnismith-Project-Id'] = String(requestParameters['xOmnismithProjectId']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/workspaces/template/{templateId}`;
        urlPath = urlPath.replace(`{${"templateId"}}`, encodeURIComponent(String(requestParameters['templateId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Searches and returns all saved workspace view panes configured across any workspace that are bound to a specific entity schema template, facilitating cross-workspace view reuse and discovery.
     * List saved views for a specific template across workspaces
     */
    async listTemplateViewsRaw(requestParameters: ListTemplateViewsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListTemplateViews200Response>> {
        const requestOptions = await this.listTemplateViewsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListTemplateViews200ResponseFromJSON(jsonValue));
    }

    /**
     * Searches and returns all saved workspace view panes configured across any workspace that are bound to a specific entity schema template, facilitating cross-workspace view reuse and discovery.
     * List saved views for a specific template across workspaces
     */
    async listTemplateViews(requestParameters: ListTemplateViewsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListTemplateViews200Response> {
        const response = await this.listTemplateViewsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listWorkspaces without sending the request
     */
    async listWorkspacesRequestOpts(requestParameters: ListWorkspacesRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xOmnismithProjectId'] != null) {
            headerParameters['X-Omnismith-Project-Id'] = String(requestParameters['xOmnismithProjectId']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/workspaces`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieves all top-level operational workspaces configured within the authenticated project context, including multi-pane layout structures (single, split-v, split-h, quad), view pane counts, sort ordering, and default workspace indicators for workbench navigation.
     * List all workspaces for current project
     */
    async listWorkspacesRaw(requestParameters: ListWorkspacesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListWorkspaces200Response>> {
        const requestOptions = await this.listWorkspacesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListWorkspaces200ResponseFromJSON(jsonValue));
    }

    /**
     * Retrieves all top-level operational workspaces configured within the authenticated project context, including multi-pane layout structures (single, split-v, split-h, quad), view pane counts, sort ordering, and default workspace indicators for workbench navigation.
     * List all workspaces for current project
     */
    async listWorkspaces(requestParameters: ListWorkspacesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListWorkspaces200Response> {
        const response = await this.listWorkspacesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for reorderWorkspaceViews without sending the request
     */
    async reorderWorkspaceViewsRequestOpts(requestParameters: ReorderWorkspaceViewsOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling reorderWorkspaceViews().'
            );
        }

        if (requestParameters['reorderWorkspaceViewsRequest'] == null) {
            throw new runtime.RequiredError(
                'reorderWorkspaceViewsRequest',
                'Required parameter "reorderWorkspaceViewsRequest" was null or undefined when calling reorderWorkspaceViews().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xOmnismithProjectId'] != null) {
            headerParameters['X-Omnismith-Project-Id'] = String(requestParameters['xOmnismithProjectId']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/workspaces/{id}/reorder-views`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ReorderWorkspaceViewsRequestToJSON(requestParameters['reorderWorkspaceViewsRequest']),
        };
    }

    /**
     * Updates the visual sequence and tab ordering of view panes inside a workspace by supplying an ordered list of view IDs matching the desired layout arrangement.
     * Reorder views inside a workspace
     */
    async reorderWorkspaceViewsRaw(requestParameters: ReorderWorkspaceViewsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.reorderWorkspaceViewsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Updates the visual sequence and tab ordering of view panes inside a workspace by supplying an ordered list of view IDs matching the desired layout arrangement.
     * Reorder views inside a workspace
     */
    async reorderWorkspaceViews(requestParameters: ReorderWorkspaceViewsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.reorderWorkspaceViewsRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for setDefaultWorkspace without sending the request
     */
    async setDefaultWorkspaceRequestOpts(requestParameters: SetDefaultWorkspaceRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling setDefaultWorkspace().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xOmnismithProjectId'] != null) {
            headerParameters['X-Omnismith-Project-Id'] = String(requestParameters['xOmnismithProjectId']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/workspaces/{id}/default`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Designates the specified workspace as the primary/default landing view for the project, automatically demoting any existing default workspace.
     * Set workspace as the default workspace
     */
    async setDefaultWorkspaceRaw(requestParameters: SetDefaultWorkspaceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.setDefaultWorkspaceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Designates the specified workspace as the primary/default landing view for the project, automatically demoting any existing default workspace.
     * Set workspace as the default workspace
     */
    async setDefaultWorkspace(requestParameters: SetDefaultWorkspaceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.setDefaultWorkspaceRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for updateWorkspace without sending the request
     */
    async updateWorkspaceRequestOpts(requestParameters: UpdateWorkspaceOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateWorkspace().'
            );
        }

        if (requestParameters['updateWorkspaceRequest'] == null) {
            throw new runtime.RequiredError(
                'updateWorkspaceRequest',
                'Required parameter "updateWorkspaceRequest" was null or undefined when calling updateWorkspace().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xOmnismithProjectId'] != null) {
            headerParameters['X-Omnismith-Project-Id'] = String(requestParameters['xOmnismithProjectId']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/workspaces/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateWorkspaceRequestToJSON(requestParameters['updateWorkspaceRequest']),
        };
    }

    /**
     * Updates workspace attributes including display name, description, multi-pane layout arrangement (single, split-v, split-h, quad), sort order sequence, and default workspace status.
     * Update workspace metadata and layout
     */
    async updateWorkspaceRaw(requestParameters: UpdateWorkspaceOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.updateWorkspaceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Updates workspace attributes including display name, description, multi-pane layout arrangement (single, split-v, split-h, quad), sort order sequence, and default workspace status.
     * Update workspace metadata and layout
     */
    async updateWorkspace(requestParameters: UpdateWorkspaceOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.updateWorkspaceRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for updateWorkspaceView without sending the request
     */
    async updateWorkspaceViewRequestOpts(requestParameters: UpdateWorkspaceViewOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateWorkspaceView().'
            );
        }

        if (requestParameters['viewId'] == null) {
            throw new runtime.RequiredError(
                'viewId',
                'Required parameter "viewId" was null or undefined when calling updateWorkspaceView().'
            );
        }

        if (requestParameters['updateWorkspaceViewRequest'] == null) {
            throw new runtime.RequiredError(
                'updateWorkspaceViewRequest',
                'Required parameter "updateWorkspaceViewRequest" was null or undefined when calling updateWorkspaceView().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xOmnismithProjectId'] != null) {
            headerParameters['X-Omnismith-Project-Id'] = String(requestParameters['xOmnismithProjectId']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/workspaces/{id}/views/{viewId}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"viewId"}}`, encodeURIComponent(String(requestParameters['viewId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateWorkspaceViewRequestToJSON(requestParameters['updateWorkspaceViewRequest']),
        };
    }

    /**
     * Updates the configuration of a specific workspace view pane, modifying its title, filtering rules, search query and mode, sorting preferences, presentation display mode (table or grid), column visibility lists, or pane display sequence. A workspace view represents a specialized filtered lens (e.g. \"Telegram Channel Hub\") inside an operational workspace.
     * Update workspace view / pane filters, sort, display mode, or columns
     */
    async updateWorkspaceViewRaw(requestParameters: UpdateWorkspaceViewOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.updateWorkspaceViewRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Updates the configuration of a specific workspace view pane, modifying its title, filtering rules, search query and mode, sorting preferences, presentation display mode (table or grid), column visibility lists, or pane display sequence. A workspace view represents a specialized filtered lens (e.g. \"Telegram Channel Hub\") inside an operational workspace.
     * Update workspace view / pane filters, sort, display mode, or columns
     */
    async updateWorkspaceView(requestParameters: UpdateWorkspaceViewOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.updateWorkspaceViewRaw(requestParameters, initOverrides);
    }

}
