/* tslint:disable */
/* eslint-disable */
/**
 * Omnismith API
 * API Documentation for Omnismith
 *
 * The version of the OpenAPI document: 1.0.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AttributeResponseReferenceConfig } from './AttributeResponseReferenceConfig';
import {
    AttributeResponseReferenceConfigFromJSON,
    AttributeResponseReferenceConfigFromJSONTyped,
    AttributeResponseReferenceConfigToJSON,
    AttributeResponseReferenceConfigToJSONTyped,
} from './AttributeResponseReferenceConfig';

/**
 * Attribute details
 * @export
 * @interface AttributeResponse
 */
export interface AttributeResponse {
    /**
     * 
     * @type {string}
     * @memberof AttributeResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof AttributeResponse
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof AttributeResponse
     */
    description?: string | null;
    /**
     * 0: Dimension, 1: Metric, 2: List, 3: Reference
     * @type {number}
     * @memberof AttributeResponse
     */
    attribute_type?: number;
    /**
     * 0: String, 1: Number, 2: Boolean, 3: Datetime, 4: Date, 5: File, 6: Image
     * @type {number}
     * @memberof AttributeResponse
     */
    data_type?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof AttributeResponse
     */
    template_ids?: Array<string>;
    /**
     * 
     * @type {AttributeResponseReferenceConfig}
     * @memberof AttributeResponse
     */
    reference_config?: AttributeResponseReferenceConfig | null;
    /**
     * 
     * @type {Date}
     * @memberof AttributeResponse
     */
    created_at?: Date;
    /**
     * 
     * @type {Date}
     * @memberof AttributeResponse
     */
    updated_at?: Date;
    /**
     * 
     * @type {Date}
     * @memberof AttributeResponse
     */
    deleted_at?: Date | null;
}

/**
 * Check if a given object implements the AttributeResponse interface.
 */
export function instanceOfAttributeResponse(value: object): value is AttributeResponse {
    return true;
}

export function AttributeResponseFromJSON(json: any): AttributeResponse {
    return AttributeResponseFromJSONTyped(json, false);
}

export function AttributeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttributeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'attribute_type': json['attribute_type'] == null ? undefined : json['attribute_type'],
        'data_type': json['data_type'] == null ? undefined : json['data_type'],
        'template_ids': json['template_ids'] == null ? undefined : json['template_ids'],
        'reference_config': json['reference_config'] == null ? undefined : AttributeResponseReferenceConfigFromJSON(json['reference_config']),
        'created_at': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updated_at': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'deleted_at': json['deleted_at'] == null ? undefined : (new Date(json['deleted_at'])),
    };
}

export function AttributeResponseToJSON(json: any): AttributeResponse {
    return AttributeResponseToJSONTyped(json, false);
}

export function AttributeResponseToJSONTyped(value?: AttributeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'attribute_type': value['attribute_type'],
        'data_type': value['data_type'],
        'template_ids': value['template_ids'],
        'reference_config': AttributeResponseReferenceConfigToJSON(value['reference_config']),
        'created_at': value['created_at'] == null ? value['created_at'] : value['created_at'].toISOString(),
        'updated_at': value['updated_at'] == null ? value['updated_at'] : value['updated_at'].toISOString(),
        'deleted_at': value['deleted_at'] == null ? value['deleted_at'] : value['deleted_at'].toISOString(),
    };
}

