/* tslint:disable */
/* eslint-disable */
/**
 * Omnismith API
 * API Documentation for Omnismith
 *
 * The version of the OpenAPI document: 1.0.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntityAttributesInputValue } from './EntityAttributesInputValue';
import {
    EntityAttributesInputValueFromJSON,
    EntityAttributesInputValueFromJSONTyped,
    EntityAttributesInputValueToJSON,
    EntityAttributesInputValueToJSONTyped,
} from './EntityAttributesInputValue';

/**
 * One write in a batch. Exact field set per op — create: template, id?, attributes · update: id, attributes · replace: id, attributes · delete: id. Any other field is rejected.
 * @export
 * @interface BatchOperationInput
 */
export interface BatchOperationInput {
    /**
     * Which write to perform for this entry.
     * @type {BatchOperationInputOpEnum}
     * @memberof BatchOperationInput
     */
    op: BatchOperationInputOpEnum;
    /**
     * Entity identifier to act on. Required for update, replace, and delete. Optional on create (client-assigned UUIDv7).
     * @type {string}
     * @memberof BatchOperationInput
     */
    id?: string | null;
    /**
     * Template UUID or slug to instantiate on create. Forbidden on other operations.
     * @type {string}
     * @memberof BatchOperationInput
     */
    template?: string | null;
    /**
     * Map of attribute slug or UUID → value. Keys may be mixed freely in one request; each attribute may appear once.
     * 
     * ### Values
     * - **Plain scalar** — `"text"`, `42`, `129.99`, `true`, or `null`. Numbers and booleans are serialized for you (`42` → `"42"`, `true` → `"true"`); floats keep exactly the digits you sent.
     * - **`null`** — clears the attribute.
     * - **Backfill object** — `{ "value": <scalar|null>, "updated_at": "2026-09-12T12:23:52Z" }` records the value as observed at that moment (history import). `updated_at` must be RFC 3339 with an explicit offset (`Z` or `±HH:MM`); it defaults to now when omitted.
     * - **Operation object** — `{ "op": "increment", "value": 1 }` adds the number to the stored value instead of overwriting it: you never need to read the current value, and concurrent increments are serialized so none is lost. Allowed on **Number** attributes and **Metrics** only (a metric increment appends `latest + value` as a new observation); a never-set attribute counts as `0`; a negative `value` subtracts. `op` cannot be combined with `updated_at`. Not accepted on create. The change log records the resolved value, never the operand.
     * 
     * ### Value format by attribute type
     * - **Text / Markdown**: UTF-8 string
     * - **Number**: number or numeric string (`129.99`, `"42"`)
     * - **Boolean**: `true` / `false` (or `"true"` / `"false"`, `"1"` / `"0"`)
     * - **Date**: `YYYY-MM-DD`; **Datetime**: `YYYY-MM-DD HH:MM:SS` or ISO 8601 `YYYY-MM-DDTHH:MM:SSZ`
     * - **File / Image**: UUID of a previously uploaded file asset
     * - **List**: UUID of one of the attribute's list items
     * - **Reference**: UUID of the referenced entity
     * - **Metric**: numeric observation; appended to the time series (never overwritten)
     * 
     * ### Example
     * ```json
     * {
     *   "hostname": "edge-fra-01",
     *   "cpu_cores": 8,
     *   "notes": null,
     *   "operational_status": { "value": "Active", "updated_at": "2026-09-12T12:23:52Z" },
     *   "restart_count": { "op": "increment", "value": 1 }
     * }
     * ```
     * @type {{ [key: string]: EntityAttributesInputValue; }}
     * @memberof BatchOperationInput
     */
    attributes?: { [key: string]: EntityAttributesInputValue; } | null;
}

/**
* @export
* @enum {string}
*/
export enum BatchOperationInputOpEnum {
    create = 'create',
    update = 'update',
    replace = 'replace',
    delete = 'delete'
}


/**
 * Check if a given object implements the BatchOperationInput interface.
 */
export function instanceOfBatchOperationInput(value: object): value is BatchOperationInput {
    if (!('op' in value) || value['op'] === undefined) return false;
    return true;
}

export function BatchOperationInputFromJSON(json: any): BatchOperationInput {
    return BatchOperationInputFromJSONTyped(json, false);
}

export function BatchOperationInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): BatchOperationInput {
    if (json == null) {
        return json;
    }
    return {
        
        'op': json['op'],
        'id': json['id'] == null ? undefined : json['id'],
        'template': json['template'] == null ? undefined : json['template'],
        'attributes': json['attributes'] == null ? undefined : (mapValues(json['attributes'], EntityAttributesInputValueFromJSON)),
    };
}

export function BatchOperationInputToJSON(json: any): BatchOperationInput {
    return BatchOperationInputToJSONTyped(json, false);
}

export function BatchOperationInputToJSONTyped(value?: BatchOperationInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'op': value['op'],
        'id': value['id'],
        'template': value['template'],
        'attributes': value['attributes'] == null ? undefined : (mapValues(value['attributes'], EntityAttributesInputValueToJSON)),
    };
}

