/* tslint:disable */
/* eslint-disable */
/**
 * Omnismith API
 * API Documentation for Omnismith
 *
 * The version of the OpenAPI document: 1.0.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Checkout session details
 * @export
 * @interface CheckoutResponse
 */
export interface CheckoutResponse {
    /**
     * URL to redirect user to complete checkout
     * @type {string}
     * @memberof CheckoutResponse
     */
    checkout_url?: string;
    /**
     * LemonSqueezy checkout session ID
     * @type {string}
     * @memberof CheckoutResponse
     */
    checkout_id?: string;
}

/**
 * Check if a given object implements the CheckoutResponse interface.
 */
export function instanceOfCheckoutResponse(value: object): value is CheckoutResponse {
    return true;
}

export function CheckoutResponseFromJSON(json: any): CheckoutResponse {
    return CheckoutResponseFromJSONTyped(json, false);
}

export function CheckoutResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckoutResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'checkout_url': json['checkout_url'] == null ? undefined : json['checkout_url'],
        'checkout_id': json['checkout_id'] == null ? undefined : json['checkout_id'],
    };
}

export function CheckoutResponseToJSON(json: any): CheckoutResponse {
    return CheckoutResponseToJSONTyped(json, false);
}

export function CheckoutResponseToJSONTyped(value?: CheckoutResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'checkout_url': value['checkout_url'],
        'checkout_id': value['checkout_id'],
    };
}

