/* tslint:disable */
/* eslint-disable */
/**
 * Omnismith API
 * API Documentation for Omnismith
 *
 * The version of the OpenAPI document: 1.0.14
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAutomation201Response
 */
export interface CreateAutomation201Response {
    /**
     * Created automation UUID
     * @type {string}
     * @memberof CreateAutomation201Response
     */
    id?: string;
}

/**
 * Check if a given object implements the CreateAutomation201Response interface.
 */
export function instanceOfCreateAutomation201Response(value: object): value is CreateAutomation201Response {
    return true;
}

export function CreateAutomation201ResponseFromJSON(json: any): CreateAutomation201Response {
    return CreateAutomation201ResponseFromJSONTyped(json, false);
}

export function CreateAutomation201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAutomation201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function CreateAutomation201ResponseToJSON(json: any): CreateAutomation201Response {
    return CreateAutomation201ResponseToJSONTyped(json, false);
}

export function CreateAutomation201ResponseToJSONTyped(value?: CreateAutomation201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

