/* tslint:disable */
/* eslint-disable */
/**
 * Omnismith API
 * API Documentation for Omnismith
 *
 * The version of the OpenAPI document: 1.0.16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AutomationTrigger } from './AutomationTrigger';
import {
    AutomationTriggerFromJSON,
    AutomationTriggerFromJSONTyped,
    AutomationTriggerToJSON,
    AutomationTriggerToJSONTyped,
} from './AutomationTrigger';
import type { AutomationAction } from './AutomationAction';
import {
    AutomationActionFromJSON,
    AutomationActionFromJSONTyped,
    AutomationActionToJSON,
    AutomationActionToJSONTyped,
} from './AutomationAction';
import type { CreateAutomationRequestConditionsInner } from './CreateAutomationRequestConditionsInner';
import {
    CreateAutomationRequestConditionsInnerFromJSON,
    CreateAutomationRequestConditionsInnerFromJSONTyped,
    CreateAutomationRequestConditionsInnerToJSON,
    CreateAutomationRequestConditionsInnerToJSONTyped,
} from './CreateAutomationRequestConditionsInner';

/**
 * 
 * @export
 * @interface CreateAutomationRequest
 */
export interface CreateAutomationRequest {
    /**
     * Descriptive display name of the automation rule
     * @type {string}
     * @memberof CreateAutomationRequest
     */
    name: string;
    /**
     * Optional summary describing the purpose and behavior of the automation
     * @type {string}
     * @memberof CreateAutomationRequest
     */
    description?: string | null;
    /**
     * 
     * @type {AutomationTrigger}
     * @memberof CreateAutomationRequest
     */
    trigger: AutomationTrigger;
    /**
     * Condition expressions that must all evaluate to true against the entity for actions to run
     * @type {Array<CreateAutomationRequestConditionsInner>}
     * @memberof CreateAutomationRequest
     */
    conditions: Array<CreateAutomationRequestConditionsInner>;
    /**
     * List of dispatch actions to execute when trigger and conditions are met
     * @type {Array<AutomationAction>}
     * @memberof CreateAutomationRequest
     */
    actions: Array<AutomationAction>;
    /**
     * Minimum throttle cooldown window in seconds between firings for the same entity
     * @type {number}
     * @memberof CreateAutomationRequest
     */
    cooldownSeconds?: number | null;
}

/**
 * Check if a given object implements the CreateAutomationRequest interface.
 */
export function instanceOfCreateAutomationRequest(value: object): value is CreateAutomationRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('trigger' in value) || value['trigger'] === undefined) return false;
    if (!('conditions' in value) || value['conditions'] === undefined) return false;
    if (!('actions' in value) || value['actions'] === undefined) return false;
    return true;
}

export function CreateAutomationRequestFromJSON(json: any): CreateAutomationRequest {
    return CreateAutomationRequestFromJSONTyped(json, false);
}

export function CreateAutomationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAutomationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'trigger': AutomationTriggerFromJSON(json['trigger']),
        'conditions': ((json['conditions'] as Array<any>).map(CreateAutomationRequestConditionsInnerFromJSON)),
        'actions': ((json['actions'] as Array<any>).map(AutomationActionFromJSON)),
        'cooldownSeconds': json['cooldownSeconds'] == null ? undefined : json['cooldownSeconds'],
    };
}

export function CreateAutomationRequestToJSON(json: any): CreateAutomationRequest {
    return CreateAutomationRequestToJSONTyped(json, false);
}

export function CreateAutomationRequestToJSONTyped(value?: CreateAutomationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'trigger': AutomationTriggerToJSON(value['trigger']),
        'conditions': ((value['conditions'] as Array<any>).map(CreateAutomationRequestConditionsInnerToJSON)),
        'actions': ((value['actions'] as Array<any>).map(AutomationActionToJSON)),
        'cooldownSeconds': value['cooldownSeconds'],
    };
}

