/* tslint:disable */
/* eslint-disable */
/**
 * Omnismith API
 * API Documentation for Omnismith
 *
 * The version of the OpenAPI document: 1.0.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateDashboardBlockRequestConfigFiltersInner
 */
export interface CreateDashboardBlockRequestConfigFiltersInner {
    /**
     * 
     * @type {string}
     * @memberof CreateDashboardBlockRequestConfigFiltersInner
     */
    field: string;
    /**
     * 
     * @type {CreateDashboardBlockRequestConfigFiltersInnerOperatorEnum}
     * @memberof CreateDashboardBlockRequestConfigFiltersInner
     */
    operator: CreateDashboardBlockRequestConfigFiltersInnerOperatorEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateDashboardBlockRequestConfigFiltersInner
     */
    value?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof CreateDashboardBlockRequestConfigFiltersInner
     */
    is_active?: boolean;
}

/**
* @export
* @enum {string}
*/
export enum CreateDashboardBlockRequestConfigFiltersInnerOperatorEnum {
    eq = 'eq',
    neq = 'neq',
    gt = 'gt',
    gte = 'gte',
    lt = 'lt',
    lte = 'lte',
    contains = 'contains',
    in = 'in'
}


/**
 * Check if a given object implements the CreateDashboardBlockRequestConfigFiltersInner interface.
 */
export function instanceOfCreateDashboardBlockRequestConfigFiltersInner(value: object): value is CreateDashboardBlockRequestConfigFiltersInner {
    if (!('field' in value) || value['field'] === undefined) return false;
    if (!('operator' in value) || value['operator'] === undefined) return false;
    return true;
}

export function CreateDashboardBlockRequestConfigFiltersInnerFromJSON(json: any): CreateDashboardBlockRequestConfigFiltersInner {
    return CreateDashboardBlockRequestConfigFiltersInnerFromJSONTyped(json, false);
}

export function CreateDashboardBlockRequestConfigFiltersInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDashboardBlockRequestConfigFiltersInner {
    if (json == null) {
        return json;
    }
    return {
        
        'field': json['field'],
        'operator': json['operator'],
        'value': json['value'] == null ? undefined : json['value'],
        'is_active': json['is_active'] == null ? undefined : json['is_active'],
    };
}

export function CreateDashboardBlockRequestConfigFiltersInnerToJSON(json: any): CreateDashboardBlockRequestConfigFiltersInner {
    return CreateDashboardBlockRequestConfigFiltersInnerToJSONTyped(json, false);
}

export function CreateDashboardBlockRequestConfigFiltersInnerToJSONTyped(value?: CreateDashboardBlockRequestConfigFiltersInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'field': value['field'],
        'operator': value['operator'],
        'value': value['value'],
        'is_active': value['is_active'],
    };
}

