/* tslint:disable */
/* eslint-disable */
/**
 * Omnismith API
 * API Documentation for Omnismith
 *
 * The version of the OpenAPI document: 1.0.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateDashboardBlockRequestConfigFiltersInner } from './CreateDashboardBlockRequestConfigFiltersInner';
import {
    CreateDashboardBlockRequestConfigFiltersInnerFromJSON,
    CreateDashboardBlockRequestConfigFiltersInnerFromJSONTyped,
    CreateDashboardBlockRequestConfigFiltersInnerToJSON,
    CreateDashboardBlockRequestConfigFiltersInnerToJSONTyped,
} from './CreateDashboardBlockRequestConfigFiltersInner';
import type { CreateDashboardBlockRequestConfigAggregationsInner } from './CreateDashboardBlockRequestConfigAggregationsInner';
import {
    CreateDashboardBlockRequestConfigAggregationsInnerFromJSON,
    CreateDashboardBlockRequestConfigAggregationsInnerFromJSONTyped,
    CreateDashboardBlockRequestConfigAggregationsInnerToJSON,
    CreateDashboardBlockRequestConfigAggregationsInnerToJSONTyped,
} from './CreateDashboardBlockRequestConfigAggregationsInner';

/**
 * Widget configuration object containing data source, metrics, time windows, and 12-column grid layout properties.
 * @export
 * @interface CreateDashboardBlockRequestConfig
 */
export interface CreateDashboardBlockRequestConfig {
    /**
     * UUID of the entity template serving as the data source (required for all block types).
     * @type {string}
     * @memberof CreateDashboardBlockRequestConfig
     */
    template_id?: string;
    /**
     * UUID of the metric attribute to aggregate/plot (required for chart and metric gauge blocks).
     * @type {string}
     * @memberof CreateDashboardBlockRequestConfig
     */
    metric_attribute_id?: string | null;
    /**
     * Time range query window in seconds for historical telemetry. CRITICAL for chart and time-series gauge blocks to query Entity Log data points. Presets: 3600 (1 hour), 10800 (3 hours), 21600 (6 hours), 43200 (12 hours), 86400 (24 hours / 1 day, recommended default), 604800 (7 days / 1 week), 2592000 (30 days / 1 month).
     * @type {number}
     * @memberof CreateDashboardBlockRequestConfig
     */
    time_window?: number | null;
    /**
     * Time bucket interval for chart data aggregation. Standard values: "1 min", "5 min", "10 min", "15 min", "1 hour" (default), "6 hours", "12 hours", "1 day", "1 week", "1 month".
     * @type {CreateDashboardBlockRequestConfigBucketWidthEnum}
     * @memberof CreateDashboardBlockRequestConfig
     */
    bucket_width?: CreateDashboardBlockRequestConfigBucketWidthEnum;
    /**
     * Aggregation function for telemetry metric points: "avg" (default for gauge/chart), "sum", "min", "max", "first", "last", "count".
     * @type {CreateDashboardBlockRequestConfigAggregateEnum}
     * @memberof CreateDashboardBlockRequestConfig
     */
    aggregate?: CreateDashboardBlockRequestConfigAggregateEnum;
    /**
     * Maximum number of entity series lines to plot concurrently in chart blocks (1-50, default: 10).
     * @type {number}
     * @memberof CreateDashboardBlockRequestConfig
     */
    entity_limit?: number;
    /**
     * Minimum scale value for gauge blocks (default: 0).
     * @type {number}
     * @memberof CreateDashboardBlockRequestConfig
     */
    min?: number;
    /**
     * Maximum scale value for gauge blocks (default: 100).
     * @type {number}
     * @memberof CreateDashboardBlockRequestConfig
     */
    max?: number;
    /**
     * Optional unit suffix for gauge blocks (e.g. "%", "°C", "MB/s", "req/s").
     * @type {string}
     * @memberof CreateDashboardBlockRequestConfig
     */
    unit?: string | null;
    /**
     * Start gradient hex color for gauge blocks (e.g. "#3b82f6").
     * @type {string}
     * @memberof CreateDashboardBlockRequestConfig
     */
    start_color?: string | null;
    /**
     * Middle gradient hex color for gauge blocks (optional).
     * @type {string}
     * @memberof CreateDashboardBlockRequestConfig
     */
    mid_color?: string | null;
    /**
     * End gradient hex color for gauge blocks (e.g. "#06b6d4").
     * @type {string}
     * @memberof CreateDashboardBlockRequestConfig
     */
    end_color?: string | null;
    /**
     * Maximum number of rows to return for list table blocks (default: 10).
     * @type {number}
     * @memberof CreateDashboardBlockRequestConfig
     */
    limit?: number;
    /**
     * Sort configuration object for list table blocks (e.g. {"created_at": "desc"}).
     * @type {object}
     * @memberof CreateDashboardBlockRequestConfig
     */
    sort?: object;
    /**
     * Ordered list of attribute UUIDs (or "created_at", "updated_at") to display as columns in list table blocks.
     * @type {Array<string>}
     * @memberof CreateDashboardBlockRequestConfig
     */
    visible_attributes?: Array<string>;
    /**
     * Attribute slugs or UUIDs to group by, at most 3 (required for aggregate blocks). Lists, references, strings, numbers, booleans and dates can be keys; metrics, markdown, files and images cannot. Empty groups the whole filtered set into one row.
     * @type {Array<string>}
     * @memberof CreateDashboardBlockRequestConfig
     */
    group_by?: Array<string>;
    /**
     * Reduces computed per group for aggregate blocks, reported back in this order (1-10 entries; defaults to a single `count` when omitted). `count` takes no field; `sum` and `avg` need a number attribute; `min` and `max` accept number, date and datetime attributes.
     * @type {Array<CreateDashboardBlockRequestConfigAggregationsInner>}
     * @memberof CreateDashboardBlockRequestConfig
     */
    aggregations?: Array<CreateDashboardBlockRequestConfigAggregationsInner>;
    /**
     * Optional entity filtering conditions applied to block data.
     * @type {Array<CreateDashboardBlockRequestConfigFiltersInner>}
     * @memberof CreateDashboardBlockRequestConfig
     */
    filters?: Array<CreateDashboardBlockRequestConfigFiltersInner>;
    /**
     * Horizontal grid column position (0 to 11 on the 12-column grid canvas).
     * @type {number}
     * @memberof CreateDashboardBlockRequestConfig
     */
    x?: number;
    /**
     * Vertical grid row position (0 to N, 0-indexed).
     * @type {number}
     * @memberof CreateDashboardBlockRequestConfig
     */
    y?: number;
    /**
     * Block width in columns on the 12-column grid canvas (1 to 12). Guidelines: 12 = full-width (chart/list), 6 = half-width (chart/gauge, 2 per row), 4 = one-third width (stat/gauge, 3 per row), 3 = one-fourth width (stat, 4 per row). Sum of cols in a row should equal 12 for edge-to-edge alignment.
     * @type {number}
     * @memberof CreateDashboardBlockRequestConfig
     */
    cols?: number;
    /**
     * Block height in grid rows (1 to N). Guidelines: 2 = KPI stat / radial gauge, 3-4 = time-series chart, 4-5 = list table.
     * @type {number}
     * @memberof CreateDashboardBlockRequestConfig
     */
    rows?: number;
}

/**
* @export
* @enum {string}
*/
export enum CreateDashboardBlockRequestConfigBucketWidthEnum {
    _1_sec = '1 sec',
    _5_sec = '5 sec',
    _10_sec = '10 sec',
    _1_min = '1 min',
    _5_min = '5 min',
    _10_min = '10 min',
    _15_min = '15 min',
    _30_min = '30 min',
    _1_hour = '1 hour',
    _6_hours = '6 hours',
    _12_hours = '12 hours',
    _1_day = '1 day',
    _1_week = '1 week',
    _1_month = '1 month'
}
/**
* @export
* @enum {string}
*/
export enum CreateDashboardBlockRequestConfigAggregateEnum {
    avg = 'avg',
    sum = 'sum',
    min = 'min',
    max = 'max',
    first = 'first',
    last = 'last',
    count = 'count'
}


/**
 * Check if a given object implements the CreateDashboardBlockRequestConfig interface.
 */
export function instanceOfCreateDashboardBlockRequestConfig(value: object): value is CreateDashboardBlockRequestConfig {
    return true;
}

export function CreateDashboardBlockRequestConfigFromJSON(json: any): CreateDashboardBlockRequestConfig {
    return CreateDashboardBlockRequestConfigFromJSONTyped(json, false);
}

export function CreateDashboardBlockRequestConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDashboardBlockRequestConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'template_id': json['template_id'] == null ? undefined : json['template_id'],
        'metric_attribute_id': json['metric_attribute_id'] == null ? undefined : json['metric_attribute_id'],
        'time_window': json['time_window'] == null ? undefined : json['time_window'],
        'bucket_width': json['bucket_width'] == null ? undefined : json['bucket_width'],
        'aggregate': json['aggregate'] == null ? undefined : json['aggregate'],
        'entity_limit': json['entity_limit'] == null ? undefined : json['entity_limit'],
        'min': json['min'] == null ? undefined : json['min'],
        'max': json['max'] == null ? undefined : json['max'],
        'unit': json['unit'] == null ? undefined : json['unit'],
        'start_color': json['start_color'] == null ? undefined : json['start_color'],
        'mid_color': json['mid_color'] == null ? undefined : json['mid_color'],
        'end_color': json['end_color'] == null ? undefined : json['end_color'],
        'limit': json['limit'] == null ? undefined : json['limit'],
        'sort': json['sort'] == null ? undefined : json['sort'],
        'visible_attributes': json['visible_attributes'] == null ? undefined : json['visible_attributes'],
        'group_by': json['group_by'] == null ? undefined : json['group_by'],
        'aggregations': json['aggregations'] == null ? undefined : ((json['aggregations'] as Array<any>).map(CreateDashboardBlockRequestConfigAggregationsInnerFromJSON)),
        'filters': json['filters'] == null ? undefined : ((json['filters'] as Array<any>).map(CreateDashboardBlockRequestConfigFiltersInnerFromJSON)),
        'x': json['x'] == null ? undefined : json['x'],
        'y': json['y'] == null ? undefined : json['y'],
        'cols': json['cols'] == null ? undefined : json['cols'],
        'rows': json['rows'] == null ? undefined : json['rows'],
    };
}

export function CreateDashboardBlockRequestConfigToJSON(json: any): CreateDashboardBlockRequestConfig {
    return CreateDashboardBlockRequestConfigToJSONTyped(json, false);
}

export function CreateDashboardBlockRequestConfigToJSONTyped(value?: CreateDashboardBlockRequestConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'template_id': value['template_id'],
        'metric_attribute_id': value['metric_attribute_id'],
        'time_window': value['time_window'],
        'bucket_width': value['bucket_width'],
        'aggregate': value['aggregate'],
        'entity_limit': value['entity_limit'],
        'min': value['min'],
        'max': value['max'],
        'unit': value['unit'],
        'start_color': value['start_color'],
        'mid_color': value['mid_color'],
        'end_color': value['end_color'],
        'limit': value['limit'],
        'sort': value['sort'],
        'visible_attributes': value['visible_attributes'],
        'group_by': value['group_by'],
        'aggregations': value['aggregations'] == null ? undefined : ((value['aggregations'] as Array<any>).map(CreateDashboardBlockRequestConfigAggregationsInnerToJSON)),
        'filters': value['filters'] == null ? undefined : ((value['filters'] as Array<any>).map(CreateDashboardBlockRequestConfigFiltersInnerToJSON)),
        'x': value['x'],
        'y': value['y'],
        'cols': value['cols'],
        'rows': value['rows'],
    };
}

