/* tslint:disable */
/* eslint-disable */
/**
 * Omnismith API
 * API Documentation for Omnismith
 *
 * The version of the OpenAPI document: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAccessTokenRequest
 */
export interface CreateAccessTokenRequest {
    /**
     * A label for the access token
     * @type {string}
     * @memberof CreateAccessTokenRequest
     */
    name: string;
    /**
     * Expiration date in ISO 8601 format
     * @type {Date}
     * @memberof CreateAccessTokenRequest
     */
    expires_at: Date;
}

/**
 * Check if a given object implements the CreateAccessTokenRequest interface.
 */
export function instanceOfCreateAccessTokenRequest(value: object): value is CreateAccessTokenRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('expires_at' in value) || value['expires_at'] === undefined) return false;
    return true;
}

export function CreateAccessTokenRequestFromJSON(json: any): CreateAccessTokenRequest {
    return CreateAccessTokenRequestFromJSONTyped(json, false);
}

export function CreateAccessTokenRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAccessTokenRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'expires_at': (new Date(json['expires_at'])),
    };
}

export function CreateAccessTokenRequestToJSON(json: any): CreateAccessTokenRequest {
    return CreateAccessTokenRequestToJSONTyped(json, false);
}

export function CreateAccessTokenRequestToJSONTyped(value?: CreateAccessTokenRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'expires_at': value['expires_at'].toISOString(),
    };
}

