/* tslint:disable */
/* eslint-disable */
/**
 * Omnismith API
 * API Documentation for Omnismith
 *
 * The version of the OpenAPI document: 1.0.11
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateNotificationChannel201Response
 */
export interface CreateNotificationChannel201Response {
    /**
     * Created notification channel UUID
     * @type {string}
     * @memberof CreateNotificationChannel201Response
     */
    id?: string;
}

/**
 * Check if a given object implements the CreateNotificationChannel201Response interface.
 */
export function instanceOfCreateNotificationChannel201Response(value: object): value is CreateNotificationChannel201Response {
    return true;
}

export function CreateNotificationChannel201ResponseFromJSON(json: any): CreateNotificationChannel201Response {
    return CreateNotificationChannel201ResponseFromJSONTyped(json, false);
}

export function CreateNotificationChannel201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateNotificationChannel201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function CreateNotificationChannel201ResponseToJSON(json: any): CreateNotificationChannel201Response {
    return CreateNotificationChannel201ResponseToJSONTyped(json, false);
}

export function CreateNotificationChannel201ResponseToJSONTyped(value?: CreateNotificationChannel201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

