/* tslint:disable */
/* eslint-disable */
/**
 * Omnismith API
 * API Documentation for Omnismith
 *
 * The version of the OpenAPI document: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Dashboard details
 * @export
 * @interface DashboardResponse
 */
export interface DashboardResponse {
    /**
     * 
     * @type {string}
     * @memberof DashboardResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof DashboardResponse
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof DashboardResponse
     */
    description?: string;
    /**
     * 
     * @type {object}
     * @memberof DashboardResponse
     */
    config?: object;
    /**
     * 
     * @type {Date}
     * @memberof DashboardResponse
     */
    created_at?: Date;
    /**
     * 
     * @type {Date}
     * @memberof DashboardResponse
     */
    updated_at?: Date | null;
}

/**
 * Check if a given object implements the DashboardResponse interface.
 */
export function instanceOfDashboardResponse(value: object): value is DashboardResponse {
    return true;
}

export function DashboardResponseFromJSON(json: any): DashboardResponse {
    return DashboardResponseFromJSONTyped(json, false);
}

export function DashboardResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DashboardResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'config': json['config'] == null ? undefined : json['config'],
        'created_at': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updated_at': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
    };
}

export function DashboardResponseToJSON(json: any): DashboardResponse {
    return DashboardResponseToJSONTyped(json, false);
}

export function DashboardResponseToJSONTyped(value?: DashboardResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'config': value['config'],
        'created_at': value['created_at'] == null ? value['created_at'] : value['created_at'].toISOString(),
        'updated_at': value['updated_at'] == null ? value['updated_at'] : value['updated_at'].toISOString(),
    };
}

