/* tslint:disable */
/* eslint-disable */
/**
 * Omnismith API
 * API Documentation for Omnismith
 *
 * The version of the OpenAPI document: 1.0.11
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DuplicateWorkspace201Response
 */
export interface DuplicateWorkspace201Response {
    /**
     * 
     * @type {string}
     * @memberof DuplicateWorkspace201Response
     */
    id?: string;
}

/**
 * Check if a given object implements the DuplicateWorkspace201Response interface.
 */
export function instanceOfDuplicateWorkspace201Response(value: object): value is DuplicateWorkspace201Response {
    return true;
}

export function DuplicateWorkspace201ResponseFromJSON(json: any): DuplicateWorkspace201Response {
    return DuplicateWorkspace201ResponseFromJSONTyped(json, false);
}

export function DuplicateWorkspace201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DuplicateWorkspace201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function DuplicateWorkspace201ResponseToJSON(json: any): DuplicateWorkspace201Response {
    return DuplicateWorkspace201ResponseToJSONTyped(json, false);
}

export function DuplicateWorkspace201ResponseToJSONTyped(value?: DuplicateWorkspace201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

