/* tslint:disable */
/* eslint-disable */
/**
 * Omnismith API
 * API Documentation for Omnismith
 *
 * The version of the OpenAPI document: 1.0.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntityAttributesInputValueAnyOf1 } from './EntityAttributesInputValueAnyOf1';
import {
    EntityAttributesInputValueAnyOf1FromJSON,
    EntityAttributesInputValueAnyOf1FromJSONTyped,
    EntityAttributesInputValueAnyOf1ToJSON,
    EntityAttributesInputValueAnyOf1ToJSONTyped,
} from './EntityAttributesInputValueAnyOf1';
import type { EntityAttributesInputValueAnyOf } from './EntityAttributesInputValueAnyOf';
import {
    EntityAttributesInputValueAnyOfFromJSON,
    EntityAttributesInputValueAnyOfFromJSONTyped,
    EntityAttributesInputValueAnyOfToJSON,
    EntityAttributesInputValueAnyOfToJSONTyped,
} from './EntityAttributesInputValueAnyOf';

/**
 * 
 * @export
 * @interface EntityAttributesInputValue
 */
export interface EntityAttributesInputValue {
    /**
     * The operand, as a JSON number.
     * @type {number}
     * @memberof EntityAttributesInputValue
     */
    value: number;
    /**
     * RFC 3339 timestamp with an explicit offset (`Z` or `±HH:MM`). Defaults to now when omitted.
     * @type {Date}
     * @memberof EntityAttributesInputValue
     */
    updated_at?: Date;
    /**
     * The operation. `increment` adds `value` (negative to subtract).
     * @type {EntityAttributesInputValueOpEnum}
     * @memberof EntityAttributesInputValue
     */
    op: EntityAttributesInputValueOpEnum;
}

/**
* @export
* @enum {string}
*/
export enum EntityAttributesInputValueOpEnum {
    increment = 'increment'
}


/**
 * Check if a given object implements the EntityAttributesInputValue interface.
 */
export function instanceOfEntityAttributesInputValue(value: object): value is EntityAttributesInputValue {
    if (!('value' in value) || value['value'] === undefined) return false;
    if (!('op' in value) || value['op'] === undefined) return false;
    return true;
}

export function EntityAttributesInputValueFromJSON(json: any): EntityAttributesInputValue {
    return EntityAttributesInputValueFromJSONTyped(json, false);
}

export function EntityAttributesInputValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntityAttributesInputValue {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'],
        'updated_at': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'op': json['op'],
    };
}

export function EntityAttributesInputValueToJSON(json: any): EntityAttributesInputValue {
    return EntityAttributesInputValueToJSONTyped(json, false);
}

export function EntityAttributesInputValueToJSONTyped(value?: EntityAttributesInputValue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'value': value['value'],
        'updated_at': value['updated_at'] == null ? value['updated_at'] : value['updated_at'].toISOString(),
        'op': value['op'],
    };
}

