/* tslint:disable */
/* eslint-disable */
/**
 * Omnismith API
 * API Documentation for Omnismith
 *
 * The version of the OpenAPI document: 1.0.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntityRulePredicate } from './EntityRulePredicate';
import {
    EntityRulePredicateFromJSON,
    EntityRulePredicateFromJSONTyped,
    EntityRulePredicateToJSON,
    EntityRulePredicateToJSONTyped,
} from './EntityRulePredicate';
import type { EntityActionPreset } from './EntityActionPreset';
import {
    EntityActionPresetFromJSON,
    EntityActionPresetFromJSONTyped,
    EntityActionPresetToJSON,
    EntityActionPresetToJSONTyped,
} from './EntityActionPreset';
import type { EntityActionField } from './EntityActionField';
import {
    EntityActionFieldFromJSON,
    EntityActionFieldFromJSONTyped,
    EntityActionFieldToJSON,
    EntityActionFieldToJSONTyped,
} from './EntityActionField';

/**
 * A named, template-scoped operation on one record: a precondition that gates it, the fields the operator is asked for, and presets applied silently. Executing an action is one entity write that passes the template's rules like any other. A status transition is `precondition: [status eq draft]`, `presets: [status = confirmed]`.
 * @export
 * @interface EntityActionResponse
 */
export interface EntityActionResponse {
    /**
     * Action UUID
     * @type {string}
     * @memberof EntityActionResponse
     */
    id?: string;
    /**
     * UUID of the template the action belongs to
     * @type {string}
     * @memberof EntityActionResponse
     */
    template_id?: string;
    /**
     * Identifier used in URLs and by agents; unique per template
     * @type {string}
     * @memberof EntityActionResponse
     */
    slug?: string;
    /**
     * Label shown in menus and dialogs
     * @type {string}
     * @memberof EntityActionResponse
     */
    name?: string;
    /**
     * What the action does, shown in the dialog
     * @type {string}
     * @memberof EntityActionResponse
     */
    description?: string | null;
    /**
     * Material icon name
     * @type {string}
     * @memberof EntityActionResponse
     */
    icon?: string | null;
    /**
     * Disabled actions are stored but neither listed for records nor executable
     * @type {boolean}
     * @memberof EntityActionResponse
     */
    is_enabled?: boolean;
    /**
     * Conditions on the record's current values that must all hold for the action to be available. Empty means always available.
     * @type {Array<EntityRulePredicate>}
     * @memberof EntityActionResponse
     */
    precondition?: Array<EntityRulePredicate>;
    /**
     * Values the operator is asked for, in dialog order
     * @type {Array<EntityActionField>}
     * @memberof EntityActionResponse
     */
    fields?: Array<EntityActionField>;
    /**
     * Values written silently on execution
     * @type {Array<EntityActionPreset>}
     * @memberof EntityActionResponse
     */
    presets?: Array<EntityActionPreset>;
    /**
     * Position among the template's actions, zero-based
     * @type {number}
     * @memberof EntityActionResponse
     */
    sort_order?: number;
    /**
     * 
     * @type {Date}
     * @memberof EntityActionResponse
     */
    created_at?: Date;
    /**
     * 
     * @type {Date}
     * @memberof EntityActionResponse
     */
    updated_at?: Date;
}

/**
 * Check if a given object implements the EntityActionResponse interface.
 */
export function instanceOfEntityActionResponse(value: object): value is EntityActionResponse {
    return true;
}

export function EntityActionResponseFromJSON(json: any): EntityActionResponse {
    return EntityActionResponseFromJSONTyped(json, false);
}

export function EntityActionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntityActionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'template_id': json['template_id'] == null ? undefined : json['template_id'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'icon': json['icon'] == null ? undefined : json['icon'],
        'is_enabled': json['is_enabled'] == null ? undefined : json['is_enabled'],
        'precondition': json['precondition'] == null ? undefined : ((json['precondition'] as Array<any>).map(EntityRulePredicateFromJSON)),
        'fields': json['fields'] == null ? undefined : ((json['fields'] as Array<any>).map(EntityActionFieldFromJSON)),
        'presets': json['presets'] == null ? undefined : ((json['presets'] as Array<any>).map(EntityActionPresetFromJSON)),
        'sort_order': json['sort_order'] == null ? undefined : json['sort_order'],
        'created_at': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updated_at': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
    };
}

export function EntityActionResponseToJSON(json: any): EntityActionResponse {
    return EntityActionResponseToJSONTyped(json, false);
}

export function EntityActionResponseToJSONTyped(value?: EntityActionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'template_id': value['template_id'],
        'slug': value['slug'],
        'name': value['name'],
        'description': value['description'],
        'icon': value['icon'],
        'is_enabled': value['is_enabled'],
        'precondition': value['precondition'] == null ? undefined : ((value['precondition'] as Array<any>).map(EntityRulePredicateToJSON)),
        'fields': value['fields'] == null ? undefined : ((value['fields'] as Array<any>).map(EntityActionFieldToJSON)),
        'presets': value['presets'] == null ? undefined : ((value['presets'] as Array<any>).map(EntityActionPresetToJSON)),
        'sort_order': value['sort_order'],
        'created_at': value['created_at'] == null ? value['created_at'] : value['created_at'].toISOString(),
        'updated_at': value['updated_at'] == null ? value['updated_at'] : value['updated_at'].toISOString(),
    };
}

