/* tslint:disable */
/* eslint-disable */
/**
 * Omnismith API
 * API Documentation for Omnismith
 *
 * The version of the OpenAPI document: 1.0.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntityAttributeValue } from './EntityAttributeValue';
import {
    EntityAttributeValueFromJSON,
    EntityAttributeValueFromJSONTyped,
    EntityAttributeValueToJSON,
    EntityAttributeValueToJSONTyped,
} from './EntityAttributeValue';

/**
 * 
 * @export
 * @interface EntityResponse
 */
export interface EntityResponse {
    /**
     * 
     * @type {string}
     * @memberof EntityResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof EntityResponse
     */
    template_id?: string;
    /**
     * 
     * @type {string}
     * @memberof EntityResponse
     */
    created_at?: string;
    /**
     * 
     * @type {string}
     * @memberof EntityResponse
     */
    updated_at?: string;
    /**
     * 
     * @type {{ [key: string]: EntityAttributeValue; }}
     * @memberof EntityResponse
     */
    attribute_values?: { [key: string]: EntityAttributeValue; };
}

/**
 * Check if a given object implements the EntityResponse interface.
 */
export function instanceOfEntityResponse(value: object): value is EntityResponse {
    return true;
}

export function EntityResponseFromJSON(json: any): EntityResponse {
    return EntityResponseFromJSONTyped(json, false);
}

export function EntityResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntityResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'template_id': json['template_id'] == null ? undefined : json['template_id'],
        'created_at': json['created_at'] == null ? undefined : json['created_at'],
        'updated_at': json['updated_at'] == null ? undefined : json['updated_at'],
        'attribute_values': json['attribute_values'] == null ? undefined : (mapValues(json['attribute_values'], EntityAttributeValueFromJSON)),
    };
}

export function EntityResponseToJSON(json: any): EntityResponse {
    return EntityResponseToJSONTyped(json, false);
}

export function EntityResponseToJSONTyped(value?: EntityResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'template_id': value['template_id'],
        'created_at': value['created_at'],
        'updated_at': value['updated_at'],
        'attribute_values': value['attribute_values'] == null ? undefined : (mapValues(value['attribute_values'], EntityAttributeValueToJSON)),
    };
}

