/* tslint:disable */
/* eslint-disable */
/**
 * Omnismith API
 * API Documentation for Omnismith
 *
 * The version of the OpenAPI document: 1.0.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExecuteSavedQuery200Response
 */
export interface ExecuteSavedQuery200Response {
    /**
     * 
     * @type {string}
     * @memberof ExecuteSavedQuery200Response
     */
    saved_query_id?: string;
    /**
     * 
     * @type {number}
     * @memberof ExecuteSavedQuery200Response
     */
    count?: number;
}

/**
 * Check if a given object implements the ExecuteSavedQuery200Response interface.
 */
export function instanceOfExecuteSavedQuery200Response(value: object): value is ExecuteSavedQuery200Response {
    return true;
}

export function ExecuteSavedQuery200ResponseFromJSON(json: any): ExecuteSavedQuery200Response {
    return ExecuteSavedQuery200ResponseFromJSONTyped(json, false);
}

export function ExecuteSavedQuery200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExecuteSavedQuery200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'saved_query_id': json['saved_query_id'] == null ? undefined : json['saved_query_id'],
        'count': json['count'] == null ? undefined : json['count'],
    };
}

export function ExecuteSavedQuery200ResponseToJSON(json: any): ExecuteSavedQuery200Response {
    return ExecuteSavedQuery200ResponseToJSONTyped(json, false);
}

export function ExecuteSavedQuery200ResponseToJSONTyped(value?: ExecuteSavedQuery200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'saved_query_id': value['saved_query_id'],
        'count': value['count'],
    };
}

