/* tslint:disable */
/* eslint-disable */
/**
 * Omnismith API
 * API Documentation for Omnismith
 *
 * The version of the OpenAPI document: 1.0.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MarketplaceBlueprintDetailResponse } from './MarketplaceBlueprintDetailResponse';
import {
    MarketplaceBlueprintDetailResponseFromJSON,
    MarketplaceBlueprintDetailResponseFromJSONTyped,
    MarketplaceBlueprintDetailResponseToJSON,
    MarketplaceBlueprintDetailResponseToJSONTyped,
} from './MarketplaceBlueprintDetailResponse';

/**
 * 
 * @export
 * @interface GetMarketplaceBlueprint200Response
 */
export interface GetMarketplaceBlueprint200Response {
    /**
     * 
     * @type {MarketplaceBlueprintDetailResponse}
     * @memberof GetMarketplaceBlueprint200Response
     */
    data?: MarketplaceBlueprintDetailResponse;
}

/**
 * Check if a given object implements the GetMarketplaceBlueprint200Response interface.
 */
export function instanceOfGetMarketplaceBlueprint200Response(value: object): value is GetMarketplaceBlueprint200Response {
    return true;
}

export function GetMarketplaceBlueprint200ResponseFromJSON(json: any): GetMarketplaceBlueprint200Response {
    return GetMarketplaceBlueprint200ResponseFromJSONTyped(json, false);
}

export function GetMarketplaceBlueprint200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetMarketplaceBlueprint200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : MarketplaceBlueprintDetailResponseFromJSON(json['data']),
    };
}

export function GetMarketplaceBlueprint200ResponseToJSON(json: any): GetMarketplaceBlueprint200Response {
    return GetMarketplaceBlueprint200ResponseToJSONTyped(json, false);
}

export function GetMarketplaceBlueprint200ResponseToJSONTyped(value?: GetMarketplaceBlueprint200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': MarketplaceBlueprintDetailResponseToJSON(value['data']),
    };
}

