/* tslint:disable */
/* eslint-disable */
/**
 * Omnismith API
 * API Documentation for Omnismith
 *
 * The version of the OpenAPI document: 1.0.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ImportEntities200ResponseAffectedEntitiesInnerExpectedAttributesInner } from './ImportEntities200ResponseAffectedEntitiesInnerExpectedAttributesInner';
import {
    ImportEntities200ResponseAffectedEntitiesInnerExpectedAttributesInnerFromJSON,
    ImportEntities200ResponseAffectedEntitiesInnerExpectedAttributesInnerFromJSONTyped,
    ImportEntities200ResponseAffectedEntitiesInnerExpectedAttributesInnerToJSON,
    ImportEntities200ResponseAffectedEntitiesInnerExpectedAttributesInnerToJSONTyped,
} from './ImportEntities200ResponseAffectedEntitiesInnerExpectedAttributesInner';

/**
 * 
 * @export
 * @interface ImportEntities200ResponseAffectedEntitiesInner
 */
export interface ImportEntities200ResponseAffectedEntitiesInner {
    /**
     * 
     * @type {string}
     * @memberof ImportEntities200ResponseAffectedEntitiesInner
     */
    entity_id?: string;
    /**
     * 
     * @type {ImportEntities200ResponseAffectedEntitiesInnerActionEnum}
     * @memberof ImportEntities200ResponseAffectedEntitiesInner
     */
    action?: ImportEntities200ResponseAffectedEntitiesInnerActionEnum;
    /**
     * 
     * @type {Array<ImportEntities200ResponseAffectedEntitiesInnerExpectedAttributesInner>}
     * @memberof ImportEntities200ResponseAffectedEntitiesInner
     */
    expected_attributes?: Array<ImportEntities200ResponseAffectedEntitiesInnerExpectedAttributesInner>;
}

/**
* @export
* @enum {string}
*/
export enum ImportEntities200ResponseAffectedEntitiesInnerActionEnum {
    created = 'created',
    updated = 'updated'
}


/**
 * Check if a given object implements the ImportEntities200ResponseAffectedEntitiesInner interface.
 */
export function instanceOfImportEntities200ResponseAffectedEntitiesInner(value: object): value is ImportEntities200ResponseAffectedEntitiesInner {
    return true;
}

export function ImportEntities200ResponseAffectedEntitiesInnerFromJSON(json: any): ImportEntities200ResponseAffectedEntitiesInner {
    return ImportEntities200ResponseAffectedEntitiesInnerFromJSONTyped(json, false);
}

export function ImportEntities200ResponseAffectedEntitiesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImportEntities200ResponseAffectedEntitiesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'entity_id': json['entity_id'] == null ? undefined : json['entity_id'],
        'action': json['action'] == null ? undefined : json['action'],
        'expected_attributes': json['expected_attributes'] == null ? undefined : ((json['expected_attributes'] as Array<any>).map(ImportEntities200ResponseAffectedEntitiesInnerExpectedAttributesInnerFromJSON)),
    };
}

export function ImportEntities200ResponseAffectedEntitiesInnerToJSON(json: any): ImportEntities200ResponseAffectedEntitiesInner {
    return ImportEntities200ResponseAffectedEntitiesInnerToJSONTyped(json, false);
}

export function ImportEntities200ResponseAffectedEntitiesInnerToJSONTyped(value?: ImportEntities200ResponseAffectedEntitiesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'entity_id': value['entity_id'],
        'action': value['action'],
        'expected_attributes': value['expected_attributes'] == null ? undefined : ((value['expected_attributes'] as Array<any>).map(ImportEntities200ResponseAffectedEntitiesInnerExpectedAttributesInnerToJSON)),
    };
}

