/* tslint:disable */
/* eslint-disable */
/**
 * Omnismith API
 * API Documentation for Omnismith
 *
 * The version of the OpenAPI document: 1.0.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Selectable choice option item for a List-type attribute.
 * @export
 * @interface ListItemResponse
 */
export interface ListItemResponse {
    /**
     * Unique identifier for the list item
     * @type {string}
     * @memberof ListItemResponse
     */
    id?: string;
    /**
     * UUID of the parent List attribute
     * @type {string}
     * @memberof ListItemResponse
     */
    attribute_id?: string;
    /**
     * Display label / choice value
     * @type {string}
     * @memberof ListItemResponse
     */
    value?: string;
    /**
     * Display sorting rank (lower numbers first)
     * @type {number}
     * @memberof ListItemResponse
     */
    sort_order?: number;
}

/**
 * Check if a given object implements the ListItemResponse interface.
 */
export function instanceOfListItemResponse(value: object): value is ListItemResponse {
    return true;
}

export function ListItemResponseFromJSON(json: any): ListItemResponse {
    return ListItemResponseFromJSONTyped(json, false);
}

export function ListItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListItemResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'attribute_id': json['attribute_id'] == null ? undefined : json['attribute_id'],
        'value': json['value'] == null ? undefined : json['value'],
        'sort_order': json['sort_order'] == null ? undefined : json['sort_order'],
    };
}

export function ListItemResponseToJSON(json: any): ListItemResponse {
    return ListItemResponseToJSONTyped(json, false);
}

export function ListItemResponseToJSONTyped(value?: ListItemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'attribute_id': value['attribute_id'],
        'value': value['value'],
        'sort_order': value['sort_order'],
    };
}

