/* tslint:disable */
/* eslint-disable */
/**
 * Omnismith API
 * API Documentation for Omnismith
 *
 * The version of the OpenAPI document: 1.0.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Selectable choice option for a list attribute.
 * @export
 * @interface ListOptionOverviewResponse
 */
export interface ListOptionOverviewResponse {
    /**
     * List option UUID
     * @type {string}
     * @memberof ListOptionOverviewResponse
     */
    id: string;
    /**
     * Option display value / choice label
     * @type {string}
     * @memberof ListOptionOverviewResponse
     */
    value: string;
}

/**
 * Check if a given object implements the ListOptionOverviewResponse interface.
 */
export function instanceOfListOptionOverviewResponse(value: object): value is ListOptionOverviewResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function ListOptionOverviewResponseFromJSON(json: any): ListOptionOverviewResponse {
    return ListOptionOverviewResponseFromJSONTyped(json, false);
}

export function ListOptionOverviewResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListOptionOverviewResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'value': json['value'],
    };
}

export function ListOptionOverviewResponseToJSON(json: any): ListOptionOverviewResponse {
    return ListOptionOverviewResponseToJSONTyped(json, false);
}

export function ListOptionOverviewResponseToJSONTyped(value?: ListOptionOverviewResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'value': value['value'],
    };
}

