/* tslint:disable */
/* eslint-disable */
/**
 * Omnismith API
 * API Documentation for Omnismith
 *
 * The version of the OpenAPI document: 1.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DashboardBlockResponse } from './DashboardBlockResponse';
import {
    DashboardBlockResponseFromJSON,
    DashboardBlockResponseFromJSONTyped,
    DashboardBlockResponseToJSON,
    DashboardBlockResponseToJSONTyped,
} from './DashboardBlockResponse';

/**
 * 
 * @export
 * @interface ListDashboardBlocks200Response
 */
export interface ListDashboardBlocks200Response {
    /**
     * 
     * @type {Array<DashboardBlockResponse>}
     * @memberof ListDashboardBlocks200Response
     */
    data?: Array<DashboardBlockResponse>;
}

/**
 * Check if a given object implements the ListDashboardBlocks200Response interface.
 */
export function instanceOfListDashboardBlocks200Response(value: object): value is ListDashboardBlocks200Response {
    return true;
}

export function ListDashboardBlocks200ResponseFromJSON(json: any): ListDashboardBlocks200Response {
    return ListDashboardBlocks200ResponseFromJSONTyped(json, false);
}

export function ListDashboardBlocks200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListDashboardBlocks200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(DashboardBlockResponseFromJSON)),
    };
}

export function ListDashboardBlocks200ResponseToJSON(json: any): ListDashboardBlocks200Response {
    return ListDashboardBlocks200ResponseToJSONTyped(json, false);
}

export function ListDashboardBlocks200ResponseToJSONTyped(value?: ListDashboardBlocks200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(DashboardBlockResponseToJSON)),
    };
}

