/* tslint:disable */
/* eslint-disable */
/**
 * Omnismith API
 * API Documentation for Omnismith
 *
 * The version of the OpenAPI document: 1.0.16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TemplateGroupInput } from './TemplateGroupInput';
import {
    TemplateGroupInputFromJSON,
    TemplateGroupInputFromJSONTyped,
    TemplateGroupInputToJSON,
    TemplateGroupInputToJSONTyped,
} from './TemplateGroupInput';
import type { TemplateAttributeInput } from './TemplateAttributeInput';
import {
    TemplateAttributeInputFromJSON,
    TemplateAttributeInputFromJSONTyped,
    TemplateAttributeInputToJSON,
    TemplateAttributeInputToJSONTyped,
} from './TemplateAttributeInput';

/**
 * Payload for partial template modification. All properties are optional; only supplied values are updated.
 * @export
 * @interface PatchTemplateRequest
 */
export interface PatchTemplateRequest {
    /**
     * Structured template attributes with optional per-template default values. If provided, replaces attribute associations.
     * @type {Array<TemplateAttributeInput>}
     * @memberof PatchTemplateRequest
     */
    attributes?: Array<TemplateAttributeInput> | null;
    /**
     * Ordered attribute groups for organizing template fields into visual UI sections.
     * @type {Array<TemplateGroupInput>}
     * @memberof PatchTemplateRequest
     */
    groups?: Array<TemplateGroupInput> | null;
    /**
     * Ordered list of metric attributes (UUIDs or slugs) summarised on the record details view, at most 8. Each must be a metric attribute of this template. Omit to keep the current pins; send an empty array to clear them.
     * @type {Array<string>}
     * @memberof PatchTemplateRequest
     */
    pinned_metric_ids?: Array<string> | null;
    /**
     * New human-readable name of the template.
     * @type {string}
     * @memberof PatchTemplateRequest
     */
    name?: string | null;
    /**
     * New description for the template.
     * @type {string}
     * @memberof PatchTemplateRequest
     */
    description?: string | null;
    /**
     * New category tag for navigation grouping.
     * @type {string}
     * @memberof PatchTemplateRequest
     */
    category?: string | null;
    /**
     * Flat list of attribute UUIDs to associate.
     * @type {Array<string>}
     * @memberof PatchTemplateRequest
     */
    attribute_ids?: Array<string> | null;
    /**
     * Flat list of attribute slugs to associate.
     * @type {Array<string>}
     * @memberof PatchTemplateRequest
     */
    attribute_slugs?: Array<string> | null;
    /**
     * New unique slug identifier within the project.
     * @type {string}
     * @memberof PatchTemplateRequest
     */
    slug?: string | null;
}

/**
 * Check if a given object implements the PatchTemplateRequest interface.
 */
export function instanceOfPatchTemplateRequest(value: object): value is PatchTemplateRequest {
    return true;
}

export function PatchTemplateRequestFromJSON(json: any): PatchTemplateRequest {
    return PatchTemplateRequestFromJSONTyped(json, false);
}

export function PatchTemplateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchTemplateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'attributes': json['attributes'] == null ? undefined : ((json['attributes'] as Array<any>).map(TemplateAttributeInputFromJSON)),
        'groups': json['groups'] == null ? undefined : ((json['groups'] as Array<any>).map(TemplateGroupInputFromJSON)),
        'pinned_metric_ids': json['pinned_metric_ids'] == null ? undefined : json['pinned_metric_ids'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'category': json['category'] == null ? undefined : json['category'],
        'attribute_ids': json['attribute_ids'] == null ? undefined : json['attribute_ids'],
        'attribute_slugs': json['attribute_slugs'] == null ? undefined : json['attribute_slugs'],
        'slug': json['slug'] == null ? undefined : json['slug'],
    };
}

export function PatchTemplateRequestToJSON(json: any): PatchTemplateRequest {
    return PatchTemplateRequestToJSONTyped(json, false);
}

export function PatchTemplateRequestToJSONTyped(value?: PatchTemplateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'attributes': value['attributes'] == null ? undefined : ((value['attributes'] as Array<any>).map(TemplateAttributeInputToJSON)),
        'groups': value['groups'] == null ? undefined : ((value['groups'] as Array<any>).map(TemplateGroupInputToJSON)),
        'pinned_metric_ids': value['pinned_metric_ids'],
        'name': value['name'],
        'description': value['description'],
        'category': value['category'],
        'attribute_ids': value['attribute_ids'],
        'attribute_slugs': value['attribute_slugs'],
        'slug': value['slug'],
    };
}

