/* tslint:disable */
/* eslint-disable */
/**
 * Omnismith API
 * API Documentation for Omnismith
 *
 * The version of the OpenAPI document: 1.0.14
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Updated reference configuration for Reference (3) attributes.
 * @export
 * @interface PatchAttributeRequestReferenceConfig
 */
export interface PatchAttributeRequestReferenceConfig {
    /**
     * Target template UUID
     * @type {string}
     * @memberof PatchAttributeRequestReferenceConfig
     */
    target_template_id?: string;
    /**
     * Target display attribute UUID
     * @type {string}
     * @memberof PatchAttributeRequestReferenceConfig
     */
    target_attribute_id?: string;
}

/**
 * Check if a given object implements the PatchAttributeRequestReferenceConfig interface.
 */
export function instanceOfPatchAttributeRequestReferenceConfig(value: object): value is PatchAttributeRequestReferenceConfig {
    return true;
}

export function PatchAttributeRequestReferenceConfigFromJSON(json: any): PatchAttributeRequestReferenceConfig {
    return PatchAttributeRequestReferenceConfigFromJSONTyped(json, false);
}

export function PatchAttributeRequestReferenceConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchAttributeRequestReferenceConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'target_template_id': json['target_template_id'] == null ? undefined : json['target_template_id'],
        'target_attribute_id': json['target_attribute_id'] == null ? undefined : json['target_attribute_id'],
    };
}

export function PatchAttributeRequestReferenceConfigToJSON(json: any): PatchAttributeRequestReferenceConfig {
    return PatchAttributeRequestReferenceConfigToJSONTyped(json, false);
}

export function PatchAttributeRequestReferenceConfigToJSONTyped(value?: PatchAttributeRequestReferenceConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'target_template_id': value['target_template_id'],
        'target_attribute_id': value['target_attribute_id'],
    };
}

