/* tslint:disable */
/* eslint-disable */
/**
 * Omnismith API
 * API Documentation for Omnismith
 *
 * The version of the OpenAPI document: 1.0.18
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Send exactly one of `body` and `delivery_id`.
 * @export
 * @interface PreviewInboundMappingRequest
 */
export interface PreviewInboundMappingRequest {
    /**
     * A sample payload, as the sender would post it: for example the sample event in the sender's webhook documentation.
     * @type {{ [key: string]: any; }}
     * @memberof PreviewInboundMappingRequest
     */
    body?: { [key: string]: any; };
    /**
     * A delivery from the endpoint's log to use as the sample instead: the `log_id` the sender was answered with.
     * @type {string}
     * @memberof PreviewInboundMappingRequest
     */
    delivery_id?: string;
    /**
     * A mapping to try instead of the saved one, in the same shape as the endpoint's `mapping`. It is not saved.
     * @type {{ [key: string]: any; }}
     * @memberof PreviewInboundMappingRequest
     */
    mapping?: { [key: string]: any; };
}

/**
 * Check if a given object implements the PreviewInboundMappingRequest interface.
 */
export function instanceOfPreviewInboundMappingRequest(value: object): value is PreviewInboundMappingRequest {
    return true;
}

export function PreviewInboundMappingRequestFromJSON(json: any): PreviewInboundMappingRequest {
    return PreviewInboundMappingRequestFromJSONTyped(json, false);
}

export function PreviewInboundMappingRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PreviewInboundMappingRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'body': json['body'] == null ? undefined : json['body'],
        'delivery_id': json['delivery_id'] == null ? undefined : json['delivery_id'],
        'mapping': json['mapping'] == null ? undefined : json['mapping'],
    };
}

export function PreviewInboundMappingRequestToJSON(json: any): PreviewInboundMappingRequest {
    return PreviewInboundMappingRequestToJSONTyped(json, false);
}

export function PreviewInboundMappingRequestToJSONTyped(value?: PreviewInboundMappingRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'body': value['body'],
        'delivery_id': value['delivery_id'],
        'mapping': value['mapping'],
    };
}

