/* tslint:disable */
/* eslint-disable */
/**
 * Omnismith API
 * API Documentation for Omnismith
 *
 * The version of the OpenAPI document: 1.0.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PushDeviceResponse
 */
export interface PushDeviceResponse {
    /**
     * 
     * @type {string}
     * @memberof PushDeviceResponse
     */
    id?: string;
    /**
     * FCM device token (masked)
     * @type {string}
     * @memberof PushDeviceResponse
     */
    token?: string;
    /**
     * 
     * @type {string}
     * @memberof PushDeviceResponse
     */
    device_name?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof PushDeviceResponse
     */
    created_at?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PushDeviceResponse
     */
    updated_at?: Date;
}

/**
 * Check if a given object implements the PushDeviceResponse interface.
 */
export function instanceOfPushDeviceResponse(value: object): value is PushDeviceResponse {
    return true;
}

export function PushDeviceResponseFromJSON(json: any): PushDeviceResponse {
    return PushDeviceResponseFromJSONTyped(json, false);
}

export function PushDeviceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PushDeviceResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'token': json['token'] == null ? undefined : json['token'],
        'device_name': json['device_name'] == null ? undefined : json['device_name'],
        'created_at': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updated_at': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
    };
}

export function PushDeviceResponseToJSON(json: any): PushDeviceResponse {
    return PushDeviceResponseToJSONTyped(json, false);
}

export function PushDeviceResponseToJSONTyped(value?: PushDeviceResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'token': value['token'],
        'device_name': value['device_name'],
        'created_at': value['created_at'] == null ? value['created_at'] : value['created_at'].toISOString(),
        'updated_at': value['updated_at'] == null ? value['updated_at'] : value['updated_at'].toISOString(),
    };
}

