/* tslint:disable */
/* eslint-disable */
/**
 * Omnismith API
 * API Documentation for Omnismith
 *
 * The version of the OpenAPI document: 1.0.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Foreign entity reference target configuration for reference-type attributes.
 * @export
 * @interface ReferenceOverviewResponse
 */
export interface ReferenceOverviewResponse {
    /**
     * UUID of target template
     * @type {string}
     * @memberof ReferenceOverviewResponse
     */
    target_template_id: string;
    /**
     * Slug identifier of target template
     * @type {string}
     * @memberof ReferenceOverviewResponse
     */
    target_template_slug?: string | null;
    /**
     * UUID of target display attribute
     * @type {string}
     * @memberof ReferenceOverviewResponse
     */
    target_attribute_id: string;
    /**
     * Slug identifier of target display attribute
     * @type {string}
     * @memberof ReferenceOverviewResponse
     */
    target_attribute_slug?: string | null;
}

/**
 * Check if a given object implements the ReferenceOverviewResponse interface.
 */
export function instanceOfReferenceOverviewResponse(value: object): value is ReferenceOverviewResponse {
    if (!('target_template_id' in value) || value['target_template_id'] === undefined) return false;
    if (!('target_attribute_id' in value) || value['target_attribute_id'] === undefined) return false;
    return true;
}

export function ReferenceOverviewResponseFromJSON(json: any): ReferenceOverviewResponse {
    return ReferenceOverviewResponseFromJSONTyped(json, false);
}

export function ReferenceOverviewResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReferenceOverviewResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'target_template_id': json['target_template_id'],
        'target_template_slug': json['target_template_slug'] == null ? undefined : json['target_template_slug'],
        'target_attribute_id': json['target_attribute_id'],
        'target_attribute_slug': json['target_attribute_slug'] == null ? undefined : json['target_attribute_slug'],
    };
}

export function ReferenceOverviewResponseToJSON(json: any): ReferenceOverviewResponse {
    return ReferenceOverviewResponseToJSONTyped(json, false);
}

export function ReferenceOverviewResponseToJSONTyped(value?: ReferenceOverviewResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'target_template_id': value['target_template_id'],
        'target_template_slug': value['target_template_slug'],
        'target_attribute_id': value['target_attribute_id'],
        'target_attribute_slug': value['target_attribute_slug'],
    };
}

