/* tslint:disable */
/* eslint-disable */
/**
 * Omnismith API
 * API Documentation for Omnismith
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterPushDeviceRequest
 */
export interface RegisterPushDeviceRequest {
    /**
     * FCM device registration token
     * @type {string}
     * @memberof RegisterPushDeviceRequest
     */
    token: string;
    /**
     * Optional device name for identification
     * @type {string}
     * @memberof RegisterPushDeviceRequest
     */
    device_name?: string | null;
}

/**
 * Check if a given object implements the RegisterPushDeviceRequest interface.
 */
export function instanceOfRegisterPushDeviceRequest(value: object): value is RegisterPushDeviceRequest {
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function RegisterPushDeviceRequestFromJSON(json: any): RegisterPushDeviceRequest {
    return RegisterPushDeviceRequestFromJSONTyped(json, false);
}

export function RegisterPushDeviceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterPushDeviceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
        'device_name': json['device_name'] == null ? undefined : json['device_name'],
    };
}

export function RegisterPushDeviceRequestToJSON(json: any): RegisterPushDeviceRequest {
    return RegisterPushDeviceRequestToJSONTyped(json, false);
}

export function RegisterPushDeviceRequestToJSONTyped(value?: RegisterPushDeviceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
        'device_name': value['device_name'],
    };
}

