/* tslint:disable */
/* eslint-disable */
/**
 * Omnismith API
 * API Documentation for Omnismith
 *
 * The version of the OpenAPI document: 1.0.11
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResolvedChartBlockResponseSeriesInnerDataPointsInner
 */
export interface ResolvedChartBlockResponseSeriesInnerDataPointsInner {
    /**
     * Bucket start timestamp in ISO 8601 format
     * @type {Date}
     * @memberof ResolvedChartBlockResponseSeriesInnerDataPointsInner
     */
    time?: Date;
    /**
     * Aggregated metric value in bucket
     * @type {number}
     * @memberof ResolvedChartBlockResponseSeriesInnerDataPointsInner
     */
    value?: number;
}

/**
 * Check if a given object implements the ResolvedChartBlockResponseSeriesInnerDataPointsInner interface.
 */
export function instanceOfResolvedChartBlockResponseSeriesInnerDataPointsInner(value: object): value is ResolvedChartBlockResponseSeriesInnerDataPointsInner {
    return true;
}

export function ResolvedChartBlockResponseSeriesInnerDataPointsInnerFromJSON(json: any): ResolvedChartBlockResponseSeriesInnerDataPointsInner {
    return ResolvedChartBlockResponseSeriesInnerDataPointsInnerFromJSONTyped(json, false);
}

export function ResolvedChartBlockResponseSeriesInnerDataPointsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResolvedChartBlockResponseSeriesInnerDataPointsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'time': json['time'] == null ? undefined : (new Date(json['time'])),
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function ResolvedChartBlockResponseSeriesInnerDataPointsInnerToJSON(json: any): ResolvedChartBlockResponseSeriesInnerDataPointsInner {
    return ResolvedChartBlockResponseSeriesInnerDataPointsInnerToJSONTyped(json, false);
}

export function ResolvedChartBlockResponseSeriesInnerDataPointsInnerToJSONTyped(value?: ResolvedChartBlockResponseSeriesInnerDataPointsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'time': value['time'] == null ? value['time'] : value['time'].toISOString(),
        'value': value['value'],
    };
}

