/* tslint:disable */
/* eslint-disable */
/**
 * Omnismith API
 * API Documentation for Omnismith
 *
 * The version of the OpenAPI document: 1.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResourceAccessInput
 */
export interface ResourceAccessInput {
    /**
     * 
     * @type {ResourceAccessInputResourceTypeEnum}
     * @memberof ResourceAccessInput
     */
    resource_type: ResourceAccessInputResourceTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ResourceAccessInput
     */
    resource_id: string;
    /**
     * 
     * @type {ResourceAccessInputAccessLevelEnum}
     * @memberof ResourceAccessInput
     */
    access_level: ResourceAccessInputAccessLevelEnum;
}

/**
* @export
* @enum {string}
*/
export enum ResourceAccessInputResourceTypeEnum {
    template = 'template',
    attribute = 'attribute'
}
/**
* @export
* @enum {string}
*/
export enum ResourceAccessInputAccessLevelEnum {
    deny = 'deny',
    view = 'view',
    edit = 'edit',
    full = 'full'
}


/**
 * Check if a given object implements the ResourceAccessInput interface.
 */
export function instanceOfResourceAccessInput(value: object): value is ResourceAccessInput {
    if (!('resource_type' in value) || value['resource_type'] === undefined) return false;
    if (!('resource_id' in value) || value['resource_id'] === undefined) return false;
    if (!('access_level' in value) || value['access_level'] === undefined) return false;
    return true;
}

export function ResourceAccessInputFromJSON(json: any): ResourceAccessInput {
    return ResourceAccessInputFromJSONTyped(json, false);
}

export function ResourceAccessInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourceAccessInput {
    if (json == null) {
        return json;
    }
    return {
        
        'resource_type': json['resource_type'],
        'resource_id': json['resource_id'],
        'access_level': json['access_level'],
    };
}

export function ResourceAccessInputToJSON(json: any): ResourceAccessInput {
    return ResourceAccessInputToJSONTyped(json, false);
}

export function ResourceAccessInputToJSONTyped(value?: ResourceAccessInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'resource_type': value['resource_type'],
        'resource_id': value['resource_id'],
        'access_level': value['access_level'],
    };
}

