/* tslint:disable */
/* eslint-disable */
/**
 * Omnismith API
 * API Documentation for Omnismith
 *
 * The version of the OpenAPI document: 1.0.11
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntityResponse } from './EntityResponse';
import {
    EntityResponseFromJSON,
    EntityResponseFromJSONTyped,
    EntityResponseToJSON,
    EntityResponseToJSONTyped,
} from './EntityResponse';

/**
 * Entity search match ranked by cosine similarity score
 * @export
 * @interface SemanticSearchResultItem
 */
export interface SemanticSearchResultItem {
    /**
     * 
     * @type {EntityResponse}
     * @memberof SemanticSearchResultItem
     */
    entity?: EntityResponse;
    /**
     * Cosine similarity score (0.0 to 1.0, where 1.0 is exact match)
     * @type {number}
     * @memberof SemanticSearchResultItem
     */
    similarity_score?: number;
}

/**
 * Check if a given object implements the SemanticSearchResultItem interface.
 */
export function instanceOfSemanticSearchResultItem(value: object): value is SemanticSearchResultItem {
    return true;
}

export function SemanticSearchResultItemFromJSON(json: any): SemanticSearchResultItem {
    return SemanticSearchResultItemFromJSONTyped(json, false);
}

export function SemanticSearchResultItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): SemanticSearchResultItem {
    if (json == null) {
        return json;
    }
    return {
        
        'entity': json['entity'] == null ? undefined : EntityResponseFromJSON(json['entity']),
        'similarity_score': json['similarity_score'] == null ? undefined : json['similarity_score'],
    };
}

export function SemanticSearchResultItemToJSON(json: any): SemanticSearchResultItem {
    return SemanticSearchResultItemToJSONTyped(json, false);
}

export function SemanticSearchResultItemToJSONTyped(value?: SemanticSearchResultItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'entity': EntityResponseToJSON(value['entity']),
        'similarity_score': value['similarity_score'],
    };
}

