/* tslint:disable */
/* eslint-disable */
/**
 * Omnismith API
 * API Documentation for Omnismith
 *
 * The version of the OpenAPI document: 1.0.14
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Template attribute association with optional per-template default value.
 * @export
 * @interface TemplateAttributeOverviewResponse
 */
export interface TemplateAttributeOverviewResponse {
    /**
     * Attribute UUID
     * @type {string}
     * @memberof TemplateAttributeOverviewResponse
     */
    id: string;
    /**
     * Attribute slug identifier
     * @type {string}
     * @memberof TemplateAttributeOverviewResponse
     */
    slug?: string | null;
    /**
     * Per-template default value for newly created entities
     * @type {string}
     * @memberof TemplateAttributeOverviewResponse
     */
    default_value?: string | null;
}

/**
 * Check if a given object implements the TemplateAttributeOverviewResponse interface.
 */
export function instanceOfTemplateAttributeOverviewResponse(value: object): value is TemplateAttributeOverviewResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function TemplateAttributeOverviewResponseFromJSON(json: any): TemplateAttributeOverviewResponse {
    return TemplateAttributeOverviewResponseFromJSONTyped(json, false);
}

export function TemplateAttributeOverviewResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplateAttributeOverviewResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'default_value': json['default_value'] == null ? undefined : json['default_value'],
    };
}

export function TemplateAttributeOverviewResponseToJSON(json: any): TemplateAttributeOverviewResponse {
    return TemplateAttributeOverviewResponseToJSONTyped(json, false);
}

export function TemplateAttributeOverviewResponseToJSONTyped(value?: TemplateAttributeOverviewResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'slug': value['slug'],
        'default_value': value['default_value'],
    };
}

