/* tslint:disable */
/* eslint-disable */
/**
 * Omnismith API
 * API Documentation for Omnismith
 *
 * The version of the OpenAPI document: 1.0.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntityActionOverviewResponse } from './EntityActionOverviewResponse';
import {
    EntityActionOverviewResponseFromJSON,
    EntityActionOverviewResponseFromJSONTyped,
    EntityActionOverviewResponseToJSON,
    EntityActionOverviewResponseToJSONTyped,
} from './EntityActionOverviewResponse';
import type { TemplateAttributeOverviewResponse } from './TemplateAttributeOverviewResponse';
import {
    TemplateAttributeOverviewResponseFromJSON,
    TemplateAttributeOverviewResponseFromJSONTyped,
    TemplateAttributeOverviewResponseToJSON,
    TemplateAttributeOverviewResponseToJSONTyped,
} from './TemplateAttributeOverviewResponse';
import type { EntityRuleOverviewResponse } from './EntityRuleOverviewResponse';
import {
    EntityRuleOverviewResponseFromJSON,
    EntityRuleOverviewResponseFromJSONTyped,
    EntityRuleOverviewResponseToJSON,
    EntityRuleOverviewResponseToJSONTyped,
} from './EntityRuleOverviewResponse';

/**
 * Template schema definition with bound attributes, validation rules, and executable actions.
 * @export
 * @interface TemplateOverviewResponse
 */
export interface TemplateOverviewResponse {
    /**
     * Template UUID
     * @type {string}
     * @memberof TemplateOverviewResponse
     */
    id: string;
    /**
     * Unique template slug identifier
     * @type {string}
     * @memberof TemplateOverviewResponse
     */
    slug?: string | null;
    /**
     * Human-readable template name
     * @type {string}
     * @memberof TemplateOverviewResponse
     */
    name: string;
    /**
     * Template description
     * @type {string}
     * @memberof TemplateOverviewResponse
     */
    description?: string | null;
    /**
     * Ordered list of attributes belonging to this template
     * @type {Array<TemplateAttributeOverviewResponse>}
     * @memberof TemplateOverviewResponse
     */
    attributes: Array<TemplateAttributeOverviewResponse>;
    /**
     * Business validation rules enforced for this template
     * @type {Array<EntityRuleOverviewResponse>}
     * @memberof TemplateOverviewResponse
     */
    rules: Array<EntityRuleOverviewResponse>;
    /**
     * Executable workflow actions and transitions for records of this template
     * @type {Array<EntityActionOverviewResponse>}
     * @memberof TemplateOverviewResponse
     */
    actions: Array<EntityActionOverviewResponse>;
}

/**
 * Check if a given object implements the TemplateOverviewResponse interface.
 */
export function instanceOfTemplateOverviewResponse(value: object): value is TemplateOverviewResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('attributes' in value) || value['attributes'] === undefined) return false;
    if (!('rules' in value) || value['rules'] === undefined) return false;
    if (!('actions' in value) || value['actions'] === undefined) return false;
    return true;
}

export function TemplateOverviewResponseFromJSON(json: any): TemplateOverviewResponse {
    return TemplateOverviewResponseFromJSONTyped(json, false);
}

export function TemplateOverviewResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplateOverviewResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'attributes': ((json['attributes'] as Array<any>).map(TemplateAttributeOverviewResponseFromJSON)),
        'rules': ((json['rules'] as Array<any>).map(EntityRuleOverviewResponseFromJSON)),
        'actions': ((json['actions'] as Array<any>).map(EntityActionOverviewResponseFromJSON)),
    };
}

export function TemplateOverviewResponseToJSON(json: any): TemplateOverviewResponse {
    return TemplateOverviewResponseToJSONTyped(json, false);
}

export function TemplateOverviewResponseToJSONTyped(value?: TemplateOverviewResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'slug': value['slug'],
        'name': value['name'],
        'description': value['description'],
        'attributes': ((value['attributes'] as Array<any>).map(TemplateAttributeOverviewResponseToJSON)),
        'rules': ((value['rules'] as Array<any>).map(EntityRuleOverviewResponseToJSON)),
        'actions': ((value['actions'] as Array<any>).map(EntityActionOverviewResponseToJSON)),
    };
}

