/* tslint:disable */
/* eslint-disable */
/**
 * Omnismith API
 * API Documentation for Omnismith
 *
 * The version of the OpenAPI document: 1.0.18
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AutomationTrigger } from './AutomationTrigger';
import {
    AutomationTriggerFromJSON,
    AutomationTriggerFromJSONTyped,
    AutomationTriggerToJSON,
    AutomationTriggerToJSONTyped,
} from './AutomationTrigger';
import type { AutomationAction } from './AutomationAction';
import {
    AutomationActionFromJSON,
    AutomationActionFromJSONTyped,
    AutomationActionToJSON,
    AutomationActionToJSONTyped,
} from './AutomationAction';
import type { UpdateAutomationRequestConditionsInner } from './UpdateAutomationRequestConditionsInner';
import {
    UpdateAutomationRequestConditionsInnerFromJSON,
    UpdateAutomationRequestConditionsInnerFromJSONTyped,
    UpdateAutomationRequestConditionsInnerToJSON,
    UpdateAutomationRequestConditionsInnerToJSONTyped,
} from './UpdateAutomationRequestConditionsInner';

/**
 * 
 * @export
 * @interface UpdateAutomationRequest
 */
export interface UpdateAutomationRequest {
    /**
     * Updated display name of the automation rule
     * @type {string}
     * @memberof UpdateAutomationRequest
     */
    name?: string | null;
    /**
     * Updated description of the automation rule
     * @type {string}
     * @memberof UpdateAutomationRequest
     */
    description?: string | null;
    /**
     * 
     * @type {AutomationTrigger}
     * @memberof UpdateAutomationRequest
     */
    trigger?: AutomationTrigger | null;
    /**
     * Updated array of condition criteria evaluated against entity state
     * @type {Array<UpdateAutomationRequestConditionsInner>}
     * @memberof UpdateAutomationRequest
     */
    conditions?: Array<UpdateAutomationRequestConditionsInner> | null;
    /**
     * Updated list of dispatch actions
     * @type {Array<AutomationAction>}
     * @memberof UpdateAutomationRequest
     */
    actions?: Array<AutomationAction> | null;
    /**
     * Updated cooldown throttle duration in seconds
     * @type {number}
     * @memberof UpdateAutomationRequest
     */
    cooldownSeconds?: number | null;
}

/**
 * Check if a given object implements the UpdateAutomationRequest interface.
 */
export function instanceOfUpdateAutomationRequest(value: object): value is UpdateAutomationRequest {
    return true;
}

export function UpdateAutomationRequestFromJSON(json: any): UpdateAutomationRequest {
    return UpdateAutomationRequestFromJSONTyped(json, false);
}

export function UpdateAutomationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateAutomationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'trigger': json['trigger'] == null ? undefined : AutomationTriggerFromJSON(json['trigger']),
        'conditions': json['conditions'] == null ? undefined : ((json['conditions'] as Array<any>).map(UpdateAutomationRequestConditionsInnerFromJSON)),
        'actions': json['actions'] == null ? undefined : ((json['actions'] as Array<any>).map(AutomationActionFromJSON)),
        'cooldownSeconds': json['cooldownSeconds'] == null ? undefined : json['cooldownSeconds'],
    };
}

export function UpdateAutomationRequestToJSON(json: any): UpdateAutomationRequest {
    return UpdateAutomationRequestToJSONTyped(json, false);
}

export function UpdateAutomationRequestToJSONTyped(value?: UpdateAutomationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'trigger': AutomationTriggerToJSON(value['trigger']),
        'conditions': value['conditions'] == null ? undefined : ((value['conditions'] as Array<any>).map(UpdateAutomationRequestConditionsInnerToJSON)),
        'actions': value['actions'] == null ? undefined : ((value['actions'] as Array<any>).map(AutomationActionToJSON)),
        'cooldownSeconds': value['cooldownSeconds'],
    };
}

