/* tslint:disable */
/* eslint-disable */
/**
 * Omnismith API
 * API Documentation for Omnismith
 *
 * The version of the OpenAPI document: 1.0.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateAutomationRequestConditionsInner
 */
export interface UpdateAutomationRequestConditionsInner {
    /**
     * Attribute UUID to evaluate
     * @type {string}
     * @memberof UpdateAutomationRequestConditionsInner
     */
    attributeId?: string;
    /**
     * Comparison operator
     * @type {UpdateAutomationRequestConditionsInnerOperatorEnum}
     * @memberof UpdateAutomationRequestConditionsInner
     */
    operator?: UpdateAutomationRequestConditionsInnerOperatorEnum;
    /**
     * Expected comparison value
     * @type {any}
     * @memberof UpdateAutomationRequestConditionsInner
     */
    value?: any | null;
    /**
     * Evaluation mode: current value, absolute numeric change, or percentage change
     * @type {UpdateAutomationRequestConditionsInnerModeEnum}
     * @memberof UpdateAutomationRequestConditionsInner
     */
    mode?: UpdateAutomationRequestConditionsInnerModeEnum;
}

/**
* @export
* @enum {string}
*/
export enum UpdateAutomationRequestConditionsInnerOperatorEnum {
    eq = 'eq',
    neq = 'neq',
    gt = 'gt',
    gte = 'gte',
    lt = 'lt',
    lte = 'lte',
    contains = 'contains',
    not_contains = 'not_contains',
    is_empty = 'is_empty',
    is_not_empty = 'is_not_empty'
}
/**
* @export
* @enum {string}
*/
export enum UpdateAutomationRequestConditionsInnerModeEnum {
    current = 'current',
    change_absolute = 'change_absolute',
    change_percent = 'change_percent'
}


/**
 * Check if a given object implements the UpdateAutomationRequestConditionsInner interface.
 */
export function instanceOfUpdateAutomationRequestConditionsInner(value: object): value is UpdateAutomationRequestConditionsInner {
    return true;
}

export function UpdateAutomationRequestConditionsInnerFromJSON(json: any): UpdateAutomationRequestConditionsInner {
    return UpdateAutomationRequestConditionsInnerFromJSONTyped(json, false);
}

export function UpdateAutomationRequestConditionsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateAutomationRequestConditionsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'attributeId': json['attributeId'] == null ? undefined : json['attributeId'],
        'operator': json['operator'] == null ? undefined : json['operator'],
        'value': json['value'] == null ? undefined : json['value'],
        'mode': json['mode'] == null ? undefined : json['mode'],
    };
}

export function UpdateAutomationRequestConditionsInnerToJSON(json: any): UpdateAutomationRequestConditionsInner {
    return UpdateAutomationRequestConditionsInnerToJSONTyped(json, false);
}

export function UpdateAutomationRequestConditionsInnerToJSONTyped(value?: UpdateAutomationRequestConditionsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'attributeId': value['attributeId'],
        'operator': value['operator'],
        'value': value['value'],
        'mode': value['mode'],
    };
}

