/* tslint:disable */
/* eslint-disable */
/**
 * Omnismith API
 * API Documentation for Omnismith
 *
 * The version of the OpenAPI document: 1.0.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ValidationErrorResponseViolationsInnerRule } from './ValidationErrorResponseViolationsInnerRule';
import {
    ValidationErrorResponseViolationsInnerRuleFromJSON,
    ValidationErrorResponseViolationsInnerRuleFromJSONTyped,
    ValidationErrorResponseViolationsInnerRuleToJSON,
    ValidationErrorResponseViolationsInnerRuleToJSONTyped,
} from './ValidationErrorResponseViolationsInnerRule';

/**
 * 
 * @export
 * @interface ValidationErrorResponseViolationsInner
 */
export interface ValidationErrorResponseViolationsInner {
    /**
     * 
     * @type {string}
     * @memberof ValidationErrorResponseViolationsInner
     */
    field: string;
    /**
     * 
     * @type {string}
     * @memberof ValidationErrorResponseViolationsInner
     */
    message: string;
    /**
     * 
     * @type {ValidationErrorResponseViolationsInnerRule}
     * @memberof ValidationErrorResponseViolationsInner
     */
    rule: ValidationErrorResponseViolationsInnerRule;
}

/**
 * Check if a given object implements the ValidationErrorResponseViolationsInner interface.
 */
export function instanceOfValidationErrorResponseViolationsInner(value: object): value is ValidationErrorResponseViolationsInner {
    if (!('field' in value) || value['field'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('rule' in value) || value['rule'] === undefined) return false;
    return true;
}

export function ValidationErrorResponseViolationsInnerFromJSON(json: any): ValidationErrorResponseViolationsInner {
    return ValidationErrorResponseViolationsInnerFromJSONTyped(json, false);
}

export function ValidationErrorResponseViolationsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidationErrorResponseViolationsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'field': json['field'],
        'message': json['message'],
        'rule': ValidationErrorResponseViolationsInnerRuleFromJSON(json['rule']),
    };
}

export function ValidationErrorResponseViolationsInnerToJSON(json: any): ValidationErrorResponseViolationsInner {
    return ValidationErrorResponseViolationsInnerToJSONTyped(json, false);
}

export function ValidationErrorResponseViolationsInnerToJSONTyped(value?: ValidationErrorResponseViolationsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'field': value['field'],
        'message': value['message'],
        'rule': ValidationErrorResponseViolationsInnerRuleToJSON(value['rule']),
    };
}

